### ISSUE TITLE
Ingest error handling issues (parent)

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#1007]
Batch jobs with children who failed image processing claim to be successful, and appear to schedule future jobs (such as solr ingest), which also appear to not happen.

Currently, if you go to the production management app and check process ID 134 under the "batch process" page, it will show "12 out of 65 parent objects have a failure." However, if you click into that batch process, even some of the parent OID's that have a status of "complete", have actually failed.

- [x] Manually check which of the 65 items in process ID 134 are failing and note them.
- [ ] Failure in image processing script will halt further processing (solr, pdf jobs etc) (check exit code?)
- [x] failure in image processing script will mark the parent object ingest as failed in the batch job interface

**Comment by alishaevn** [comment]
https://collections.library.yale.edu/management/batch_processes
- the `status` column on the data table appears to be correctly calculated

https://collections.library.yale.edu/management/batch_processes/134
- looking at parent OID 16457727, the status on the data table shows `failed`
- data table status = BatchConnection.joins(sql).where(batch_process_id: params[:id]).status

https://collections.library.yale.edu/management/batch_processes/134/parent_objects/16457727
- the status at the top of the page shows `complete`, but if we look at the [parent object](https://collections.library.yale.edu/management/batch_processes/134), the solr record is null
- status at the top of the page = `"#{ParentObject.find_by(oid: params[:oid]).status_for_batch_process(@batch_process)}"`
- child objects status in the data table = ChildObject.where(parent_object_oid: params[:oid])&.status_for_batch_process(@batch_process).to_s

- when looking for the solr document at http://localhost:8983/solr/blacklight-core/select?q=oid_ssi%3A16457727, we don't get an empty object, but we also don't get a complete solr document
- trying to find a way to determine whether the solr document is null and if so, to show the status of that parent object as failed.

we locally imported the `reup.csv` file 1.5 hours ago, but the ingest hasn't finished

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/477

# Summary
- we were displaying all events for a batch…for each parent
- if any parent in the batch had successfully generated a manifest, then a given parent in that batch would show that it had generated a manifest…even if it hadn't
- we're now making sure that the status that returns for a child object or parent object, is specific to that object
- updated the tests

# Expected Behavior
- when a batch process is created, the proper status will be shown on the batch processES,  batch process, parent batch process and single child batch process pages

# Demo
- We pushed this branch to https://collections-test.library.yale.edu/management, uploaded the file of 65 oids and verified the proper statuses were showing
- The [list of 65 items](https://docs.google.com/spreadsheets/d/1HvbMAxP1T1AjIMWLcqRxDqoX7HNQIixkTxdcIXyWNVQ/edit#gid=0) that we went through shows that only 10 out of 65 oids were actually successful
- The batch process page does show 10 "complete" oids, whose oids match the successful oids on the list of 65.

https://collections-test.library.yale.edu/management/batch_processes
![65](https://user-images.githubusercontent.com/29032869/105930041-b69c6700-5ffd-11eb-87ee-f205d1d3f246.jpg)

https://collections-test.library.yale.edu/management/batch_processes/89
![image](https://user-images.githubusercontent.com/29032869/105930063-c451ec80-5ffd-11eb-89b2-c14e51ce3a22.png)

https://collections-test.library.yale.edu/management/batch_processes/89/parent_objects/16590537
![image](https://user-images.githubusercontent.com/29032869/105930093-d5026280-5ffd-11eb-886f-aa8ebdd534fd.png)
