### ISSUE TITLE
Updated Beinecke analytics

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#101]
**STORY**
As a team, we'd like to review current usage patterns for BRBL DL based on increased remote learning to help start setting the performance benchmarks the system will need to meet.

**ACCEPTANCE**
- [ ] Average work-level request per hour
- [ ] Max work-level requests per hour in the last quarter
- [ ] Max work-level all-time requests per hour  

[Bonus if available]
- [ ] Number of unique visitors associated with each of the above (i.e. is this a few people using the system really heavily, or lots of folks doing just a few requests each)
- [ ] Number of image-level requests (same as above avg/hour, max/hour this quarter, max/hour ever)
- [ ] Minimum & Average search response time
- [ ] Minimum & Average work page load time
- [ ] Any other stats that seem relevant

**Comment by dl-maura** [comment]
I've grabbed some Google Analytics reports (usage report limited to sites with brbl-dl as our GA tracks non DL traffic as well), and I've reached out to Jay to ask if he has any reports he runs for usage. The GA reports indicate we haven't have an increase in use in the past month. If there are more useful GA reports to run than what I did, let me know!

**Comment by dl-maura** [comment]
Here are the reports:

BRBL Feb March
[https://app.zenhub.com/files/242185115/35a47b12-9c21-4ca3-add5-8eda81c6c263/download](https://app.zenhub.com/files/242185115/35a47b12-9c21-4ca3-add5-8eda81c6c263/download)

BRBL March April
[https://app.zenhub.com/files/242185115/0eb444a3-afff-49b4-b19f-682607af3e3f/download](https://app.zenhub.com/files/242185115/0eb444a3-afff-49b4-b19f-682607af3e3f/download)

FindIt
[https://app.zenhub.com/files/242185115/561c40a3-4f1f-4eab-9ffc-170717507e72/download](https://app.zenhub.com/files/242185115/561c40a3-4f1f-4eab-9ffc-170717507e72/download)

**Comment by mark-dce** [comment]
@dl-maura is there any way we could get the March/April data broken down hourly?  I was able to get something similar out of our Google Analytics by going to the "Behavior / Overview" and selecting "Pageviews" and "Hourly" options:

![image](https://user-images.githubusercontent.com/3064318/80739929-eead6280-8adc-11ea-823f-cf6ea40a27fb.png)

**Comment by dl-maura** [comment]
I got access to the brbl-dl view so I exported some new reports -- I'm also trying to use Feb. data because I realized we had 2 weeks of spring break in march so that skews results

[https://app.zenhub.com/files/242185115/162474f2-8138-4081-8d3d-6787c56cd505/download](https://app.zenhub.com/files/242185115/162474f2-8138-4081-8d3d-6787c56cd505/download)

[https://app.zenhub.com/files/242185115/ef518483-42c1-46b2-871b-1bd960eaf6bf/download](https://app.zenhub.com/files/242185115/ef518483-42c1-46b2-871b-1bd960eaf6bf/download)

Let me know if these are legible Mark, I know you can't hover over spots.
