### ISSUE TITLE
Child Object Reporting Bug?

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1033]
Similar problem to the parent object -- child says complete but it is actually failed
![Screen Shot 2021-01-28 at 10.27.25 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/aa1fe4ed-1e26-42f6-8f6a-4d722c394dd7)
![Screen Shot 2021-01-28 at 10.27.30 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/97f53a46-5771-4c5a-9dcd-aeecf5057f10)

**Comment by alishaevn** [comment]
we've determined that the issue here is that if any of the child objects have a status of `complete`, all of the child objects will show as complete. this is because the batch connection doesn't know about any of the individual child objects.

we are hoping to pair with max tomorrow to (hopefully) figure out how to make a batch connection aware of the child objects.

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-management/pull/484

**Comment by alishaevn** [comment]
# Expected Behavior
- child objects have their own batch connections
- all statuses reflect correctly for the parent and child objects

# Next Steps
- fix all of the failed specs
- test with a child object that doesn't "complete" to make sure that the correct status shows and is bubbled up
- confirm that the "recreate child oid ptiffs" option still works (need a csv with an oid that should work)

**Comment by dl-maura** [comment]
#1068 has the sheet linked that @martinlovell is working with if you all wanted to coordinate just trying one or two from that.

**Comment by mikeapp** [comment]
Looks good on test.
