### ISSUE TITLE
Assign batch job status when processing reassociations

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1057]
**Story**

Reassociations can fail in a number of ways:

* non-existent parent OID (source or destination)
* non-existent child OID
* non-integer order value
* ~~invalid `viewing_hint` (actually the code seems not to use this, if uploaded?)~~

**ACCEPTANCE**
- [x] Set an in-progress status at the start of the job
- [ ] Log a failure agains the child and one or both of the related parent(s) when these errors occur.
- [x] Set failure or success status at the end of the job

**Comment by DraxIndustries79** [comment]
Putting on hold for now, needs some decisions.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/531

- Adds method BatchProcess.batch_processing_event to store batch wide IngestEvents that aren't associated with an existing ParentObject or ChildObject
- Display those events on the batch show page.
- Generate batch wide IngestEvents for Reassociate Child batches when parent or child don't exist or order is not valid.  Batch continues to process other rows.
- Generate batch wide IngestEvent for Recreate PTIFF batches when a child oid does not exist.  Batch continues to process other rows.
- Updates batch table to show number of batch wide messages, updates batch show to list the messages
- Update batch form to force user to choose an option (instead of defaulting to Create Parent Objects to prevent errors)

After (batch index/new batch page):
![image](https://user-images.githubusercontent.com/32851993/109160102-5f47fe80-7743-11eb-85ad-89f521c02c53.png)

After (batch show page):
![image](https://user-images.githubusercontent.com/32851993/109160242-89012580-7743-11eb-94d2-1b4328615037.png)
