### ISSUE TITLE
Image Replacements

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1068]
We have some images we had to replace in the access master pair tree:
- [x] verify they are on access master drive
- [x] create batch process to force child ptiffs to be recreated
- [ ] run batch to update ptiffs where access master was updated
- [ ] run batch for ptiffs created when the script was creating ptiffs with bad image [0]

**Comment by martinlovell** [comment]
PR for batch to force recreation of PTIFFs based on a list of child oids:
https://github.com/yalelibrary/yul-dc-management/pull/502

Once this is deployed, we need to process a list of child oids in an environment where the access masters are available.  (not test or uat currently.)

We should also run this in test for the zip format PTIFFs with the bad JPEG followed by zipped images to fix the blocked PDF jobs.  This can not be done in test because the access masters are not available there.

**Comment by martinlovell** [comment]
Updated images needing new PTIFFs:
[https://app.zenhub.com/files/242185115/840eafa5-2272-48b4-9616-27b4d8a03c84/download](https://app.zenhub.com/files/242185115/840eafa5-2272-48b4-9616-27b4d8a03c84/download)

**Comment by martinlovell** [comment]
See card for reporting on ptiff update batch job:
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1075

There is some reporting, but overall progress of batch or parent objects is not fully functional.

**Comment by dl-maura** [comment]
Deploy this to staging Monday?
