### ISSUE TITLE
Fix Indexing of Container Information

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1077]
Right now, container information is ssim but this means we can't search by box number in the all fields like we intended. We need to make this a tesim.

Example: call num:"JWJ MSS 26" all fields:492 gets nothing but that is the box number, but "JWJ MSS 26" and 12441 works. Martin believes this is because that is the end portion and therefore makes a match but the 492 is the middle and isn't

- [x] change this in management
~~- [ ] change this in blacklight~~

**Comment by martinlovell** [comment]
- [ ] Update management to index to existing field: containerGrouping_ssim and new field: containerGrouping_tesim
- [ ] Deploy management and reindex all objects.
- [ ] Update blacklight to use new field containerGrouping_tesim rather than containerGrouping_ssim.
- [ ] Update management to only index to containerGrouping_tesim

**Comment by dl-maura** [comment]
for the management part:
https://github.com/yalelibrary/yul-dc-management/pull/506

**Comment by dl-maura** [comment]
Blacklight has draft pr, looks good on test, but requires re-index after management deploy before deploy

**Comment by dl-maura** [comment]
Revert to blacklight using the ssim and then remove it entirely in a future release so as not to disrupt display

**Comment by dl-maura** [comment]
Should I make this 2 tickets?

**Comment by DraxIndustries79** [comment]
Note: Maura making second ticket for BlackLight
