### ISSUE TITLE
BibID shows even when blank

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1083]
Orbis Record (BibID) still shows even when it has no data
![Screen Shot 2021-02-11 at 2.06.20 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/36f92f93-5519-491c-8191-74ca21b49b2f)

**Comment by maxkadel** [comment]
When a ParentObject is created in Management via the UI, values that aren't set are set to an empty string, rather than null. These are then passed into Solr (since they exist, they're just empty), and if you inspect the page in Blacklight, you see that the helper method has created an anchor link with an empty text value. 

![image](https://user-images.githubusercontent.com/45948126/107976297-53ac4900-6f87-11eb-9e95-924b2872dd76.png)

**Comment by maxkadel** [comment]
Solr record. To re-create, edit the ParentObject record in Management to remove the bib id and save, it should re-index to solr with empty strings as the values. 

![image](https://user-images.githubusercontent.com/45948126/107976630-dfbe7080-6f87-11eb-99bf-4a3c48588951.png)

**Comment by mikeapp** [comment]
Looks good on UAT.
