### ISSUE TITLE
Allow editing of users in management application

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1087]
**Story**

As a management admin, I want to be able to create and edit users on the system.

**Acceptance**

- [x] On the Users page, provide an option to edit a user.   The edit form should:
   - [x] Allow editing of the email address, and validate that one is provided
   - [x] Allow the toggling of the `deactivated` flag

**Comment by alishaevn** [comment]
@mikeapp currently none of the users who auth with CAS have an email. are we validating that all new users have emails? or that if someone tries to edit a user, they add an email?

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/00d6ea3e-adec-46fb-881f-c86b20009301)

**Comment by mikeapp** [comment]
If someone edits an existing user they should be required to add an email.

**Comment by dylansalay** [comment]
Co-author: Alisha Evans <alisha@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-management/pull/525

# Expected behavior
- users are editable from `/management/users`
- users can be deactivated
- new users require an email address
- if an existing user is edited, an email address must be added
- there is a user show page
- existing users will have an email address with the domain @connect.yale.edu

# Demo
|users page | edit page | show page |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/108768121-2540e780-750c-11eb-896b-abb18be1ecf7.png) | ![image](https://user-images.githubusercontent.com/29032869/108768213-3d186b80-750c-11eb-9eb9-8244c9955a12.png) | ![image](https://user-images.githubusercontent.com/29032869/108768172-31c54000-750c-11eb-9681-f61e4207672a.png) |

# Resources
- https://til.hashrocket.com/posts/af87b1eaa8-test-validation-errors-with-rspec
- https://medium.com/@tmikeschu/testing-html5-messages-with-rspec-selenium-5f5834c5af10

# Testing
- press "edit" by a user that isn't yourself
- check the check box underneath "deactivated"
- press "update user"
- you'll get an error to add an email
- add the email
- press "update user"
- in the users datatable click the "active" dropdown and select "inactive"
- you should see the user you just deactivated
- press "edit" next to their name
- uncheck the check box underneath "deactivated"
- press "update user"
- the user should again be listed as active

**Comment by mikeapp** [comment]
Looks good on UAT, was able to update my name and email.
