### ISSUE TITLE
Add first and last name properties for management app users

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1091]
**Story**

As a management application admin I'd like to have first and last names of users available.

**Acceptance**

- [x] The user model has first name and last name properties
- [x] The first and last names are editable and required
- [x] The first and last names are required when creating a new user

**Comment by alishaevn** [comment]
# Status
everything appeared to be working locally, but when we tried to deploy again we got the same time out fail in jenkins that we had on [1087](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1087). aws also gave us another validation error, but for first and last name. it seems to all work locally but to test, dylan and I both did a `cam down` and `cam up management`. now we're unable to log into the management app at all.
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/82ffed81-7afd-4acd-bfb3-65d2d4d6849d)

from the rails console, it shows that there aren't any users at all.
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/48f5fff0-61a0-4258-b2e6-1853d6197395)

if we can get the deploy figured out, this branch should be good to go.
dylan and I are both out of yale hours this week but if time allows, we'll try to look back at this on friday.

**Comment by dylansalay** [comment]
Co-author: Alisha Evans <alisha@notch8.com>
Co-author: Dylan Salay <dylan@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-management/pull/528

# Expected behavior
- existing users have a dummy name in the database that will need to be updated
- new users will require a first and last name
- user first and last name's are in the data table and are searchable
- user names are editable

# Demo
|users page | edit page | show page |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/108914532-538ff700-75e0-11eb-904e-adb794dfa18d.png) | ![image](https://user-images.githubusercontent.com/29032869/108914822-cac58b00-75e0-11eb-9314-1fd6d11509c9.png) | ![image](https://user-images.githubusercontent.com/29032869/108914987-0fe9bd00-75e1-11eb-9c7c-ccac3fb2b85c.png) |

**Comment by mikeapp** [comment]
Looks good
