### ISSUE TITLE
SPIKE: Review Ruby gems for authorization / role-based access control

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1097]
**Story**

In a future sprint we are planning to implement role-based access controls in the management interface.   Objects in the system will be assigned to "administrative sets", and each set will have at least two roles associated with it (e.g., user, read-only user).  System admins will have a separate role.

**Acceptance**

- [x] Review `rolify` https://github.com/RolifyCommunity/rolify for roles suport
- [x] Review the following commonly-used authorization gems.  
`cancancan` https://github.com/CanCanCommunity/cancancan
`pundit` https://github.com/varvet/pundit
- [x] Report on pros/cons for authorization gems

**Comment by FCRodriguez7** [comment]
**Some of my thoughts about Pundit and CanCanCan:** 
My initial vote went to Pundit.  Pundit has a formal distribution model and lots of documentation.   This gem seems to align with an open-source model familiar to the library.  Pundit has 12 opened PRs and 13 releases.  This could indicate low engagement and commitment from the creator and support community.  Simply put, the gem does not appear as mature as CanCanCan.  CanCanCan [a pain to type], CCC, [pronounce triple C] has an informal distribution model and lots of documentation.  This gem seems to align with an open-source model familiar to the library too.  CCC has 16 opened PRs and 63 releases. The CCC gem appears to have a wide audience and a larger community of users, 30,779. Additionally, the gem appears to be more mature than Pundit.

**Comment by DraxIndustries79** [comment]
Martin:  Approves either approach
Rob:  Notch8 typically uses CanCanCan; Pundit is often chosen because it appears to be the better choice for more complex requirements, but winds up resulting in poor user permissions admin practice and often goes unused because of complexity; Also Pundit is not as mature as CanCanCan
Maggie:  CanCanCan looks simpler for unit tests; Pundit is more flexible but more complicated

As of now, consensus is around CanCanCan.  We'll bang the gavel on that in standup 2/26.

**Comment by mikeapp** [comment]
This is helpful:
https://github.com/RolifyCommunity/rolify/wiki/Devise---CanCanCan---rolify-Tutorial
