### ISSUE TITLE
Rights field escapes link HTML

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1103]
**Story**

Rights field escapes link HTML.  Example: https://collections.library.yale.edu/catalog/16536583

![Screen Shot 2021-03-31 at 5.19.52 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/75979e4f-8a4d-493a-8649-5382786b91fa)

**Acceptance**

- [x] Rights displays HTML links as links
- [x] IIIF Manifest displays the link as a link ( see https://iiif.io/api/presentation/2.1/#html-markup-in-property-values )
- [x] Only `a` tags and their `href` attribute should come through; scrub other tags.  There's a Rails method for this.

**Comment by alishaevn** [comment]
co-author: dylan salay <dylan@notch8.com>
co-author: leaann bradford <leaann@notch8.com>

# PR
blacklight: https://github.com/yalelibrary/yul-dc-blacklight/pull/501
management: https://github.com/yalelibrary/yul-dc-management/pull/587

# Expected behavior
- links that are part of a rights statement will be sanitized to only show the `a` tag and `href` attribute
- that same link will display as a link instead of plain text
- if we desire the same behavior for other fields on the page, the `html_safe_converter` helper can be used

# Demo
| blacklight | management |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/113906807-7e499f80-9789-11eb-8721-e581ac1251c1.png) | ![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/6fa373d2-98a9-4f36-b0ea-28bee7e7848c) |

# Resources
- https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize

**Comment by alishaevn** [comment]
`Branch:1103-rights-field-escape-link,Deployed:2021-04-07T13:32:39-04:00 `

Noticed on test that different window lengths make the link in the rights statement behave differently. Either all of the link is clickable, the first 3 letters are clickable, or none of it is clickable.

The text in question is "WATCH File"

| width | clickable portion of text |
| --- | --- |
| 1700px | WATCH File|
|1648px | WATCH Fi |
|1640px | WATCH F |
| 1591px | WATC |
| 1541px| W |
|1218px | n/a |
| 1055px | WATCH File|
| 753px | WATCH File|
| 376px | WATCH File|

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/503

# Related PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/501

# Expected behavior
- all links that show on the right side of a show page should be clickable despite the window width
- we discovered that there was a `section` on the right side at certain widths, and that's what was covering the link. there's nothing in it anymore, so we removed it

# Testing instructions
- open the browser to some of the widths above (or close it it) and verify you can still click the link

# Resource
- https://github.com/projectblacklight/blacklight/blob/c310fc8cb07635cac8e2474b1afa9fafdb6c89de/app/views/layouts/catalog_result.html.erb

**Comment by alishaevn** [comment]
The ticket above hasn't been approved yet, but we pushed it to test and verified that it does work there.
`Branch:1103-rights-field-escape-link-2,Deployed:2021-04-07T18:57:30-04:00 `
