### ISSUE TITLE
Restrict access to Delayed Job Dashboard to sysadmins

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1117]
**Story**

The Delayed Job dashboard can cause performance issues (through live polling) and also allows cancellation of jobs, etc.   It should be restricted to sysadmins 

**Acceptance**

- [x] Access to the delayed job dashboard is restricted to logged in users with the sysadmin role
- [x] The menu option is not displayed in the left menu unless the logged-in user has the sysadmin role

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-management/pull/571

# Status
the delayed jobs menu item is only showing for users who are logged in and a sysadmin

I'm able to restrict a logged in user who isn't a sysadmin from accessing the delayed jobs path. however, they currently get redirected to '/management/users/auth/cas'. (existing behavior) I'm working on having them instead receive an "access denied" message, while only users who aren't signed in at all fallback to the cas path.

**Comment by alishaevn** [comment]
# Expected behavior
- signed out users:
  - cannot see the "delayed job dashboard" menu item
  - are redirected to `/management/users/auth/cas` if they try to manually access `/delayed_job` or any other endpoints after it (overview, etc.)
- authenticated users who are _not_ sysadmin's
  - cannot see the "delayed job dashboard" menu item
  - are shown an "access denied" page if they try to manually access `/delayed_job` or any other endpoints after it (overview, etc.)
- authenticated users who _are_ sysadmin's
  - can see the "delayed job dashboard" menu item and be taken to the overview page if they click it
  - are able to manually access `/delayed_job` and any other endpoints after it (overview, etc.)

# Demo
https://user-images.githubusercontent.com/29032869/112187668-89180800-8bbf-11eb-9cb5-fa01c7955969.mp4

# Resources
- https://github.com/ejschmitt/delayed_job_web#authenticating-with-devise-and-warden
- https://stackoverflow.com/a/38779554/8079848
- https://stackoverflow.com/a/37174557/8079848
- https://guides.rubyonrails.org/routing.html#route-globbing-and-wildcard-segments
