### ISSUE TITLE
SPIKE: Investigate Blacklight OAI-PMH provider options for MODS

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1126]
**Story**

Ladybird has an OAI-PMH provider from which various external sites harvest MODS data.   We would like to replicate this in the new system.   We've heard that there has been work done on the Blacklight OAI-PMH provider to extend it to provide MODS, but this is not out-of-the-box functionality.

**Acceptance**
- [ ] Investigate options for providing MODS via OAI-PMH from Blacklight and report back.

**Comment by orangewolf** [comment]
Here are the tickets I would propose along with some flesh and bones around how I think they can be tackled.

# Add the proper provider information to the `app/controllers/catalog_controller.rb`

See 
https://github.com/projectblacklight/blacklight_oai_provider#blacklight-configuration
Example:
```
    config.oai = {
      provider: {
        repository_name: 'Test',
        repository_url: 'http://localhost/catalog/oai',
        record_prefix: 'oai:test',
        admin_email: 'root@localhost',
        sample_id: '109660'
      },
      document: {
        limit: 25,            # number of records returned with each request, default: 15
        set_fields: [        # ability to define ListSets, optional, default: nil
          { label: 'language', solr_field: 'language_facet' }
        ]
      }
    }
```
**NOTE**: There is some thoughtwork that needs to happen as to what these values should be

# Define the mods format
Detail the correct format for mods that the OAI consumers are expecting. 

# Add mods format to Ruby-oai library
Blacklight-oai-provider formats are defined in http://github.com/code4lib/ruby-oai. See https://github.com/neubloc/ruby-oai/commit/7bd9ad0d75c983a96425ab5ae005d2701a17d705 as an example of this being done for Marc once upon a time. Fork ruby-oai and add support for our MODs needs. This work should result in a mods PR back to ruby-oai if possible.

# Connect MODs format to blacklight_oai_provider
Actually enabling the user to see mods data at /catalog/oai?verb=ListMetadataFormats
Fork the BlacklightOaiProvieder gem and connect it to the mods format. This may be as simple as adding a method to the BlacklightOaiProvider::SolrDocument concern. That seems to be the only place where DC is specified in that gem. This should be contributed back if possible.

# Add timestamp to records on index
As an oai consumer, I need a timestamp field in the solr index so that we know when records were most recently updated. This timestamp should be updated whenever the management application indexes the record in solr.

**Comment by orangewolf** [comment]
Draft PR here https://github.com/yalelibrary/yul-dc-blacklight/pull/487 I have installed the current version of the OAI provider. It needs a timestamp on the records, but once that is in place will show the oai_dc correctly.

**Comment by orangewolf** [comment]
@DraxIndustries79 @mikeapp gathered up my nodes from the week and pushed up the in progress PR. I didn't go so far as to create the tickets yet, since I felt like editing them here was easier than if we needed to edit the whole set. Let me know if you'd like me to drop them in to separate tickets, but in my mind it's just one ticket per section title above.
