### ISSUE TITLE
Display image tray for items with multiple images

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#114]
**STORY**
When I'm viewing a multipage work, I would like a thumbnail view of all the pages, so that I can quickly scan and jump through long works, instead of having to navigate one page at at time.

**ACCEPTANCE**
Given a manifest with more than one image or page,
- [x] UV displays thumbnails of the pages along the left hand side of the viewer

**MOCK-UP**
![image](https://user-images.githubusercontent.com/3064318/81606679-1cc25a80-9399-11ea-9bea-ce4eb99f6d9b.png)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/37

# Story
When I'm viewing a multipage work, I would like a thumbnail view of all the pages, so that I can quickly scan and jump through long works, instead of having to navigate one page at at time.

# Expected Behavior
- user's see thumbnails of all images in the left pane **when the browser window is 1200px or wider**
- user's can click the gallery view option in the top pane

# Demo
![Screen Shot 2020-05-14 at 9 48 34 AM](https://user-images.githubusercontent.com/29032869/81963014-64c7c400-95c9-11ea-8839-7378982ac2c5.png)

# Resources
- https://github.com/emory-libraries/dlp-lux/pull/93
- https://forum.omeka.org/t/universal-viewer-config-json/9451
