### ISSUE TITLE
Deleting parent leaves batch process in progress 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1157]
**Story**

Deleting (and recreating?) a ParentObject created by a "Create" job before the job completes leaves the job "in progress".

![Screen Shot 2021-03-15 at 10.18.25 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/fd672b66-e523-4adb-b35c-112e8cfceed2)

**Acceptance**

- [ ] Fix if straightforward, or report back.  Job should fail w/ appropriate message.

**Comment by martinlovell** [comment]
While experimenting with this, I found a potential issue when deleting and recreating a parent with the same OID.

ParentObject uses oid as the key with queuing jobs.  

Issue:
- Parent is created.
- Jobs are queued.
- Parent is deleted.
- New Parent is created with same oid.
- Old jobs for the old parent that was deleted get run on the new ParentObject.

ChildObject also uses oid as the key.

I'm not sure if this will cause problems other than running a few extra jobs in this rare situation, but I wanted to mention it.

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/581

# Expected behavior
- when a parent object is deleted, its and its child object delayed jobs are also deleted
- the batch process status remains "in progress"
- `batch_connection.status` still shows in progress
(the final 2 points were discussed in sprint planning on 04/06/2021 and mike/rebecca will discuss if/how to address it)

**Comment by alishaevn** [comment]
dylan and I looked at this on test and it works.

@mikeapp @rebeccahirsch, as you'll see in the screenshots below, the 2 points that I reference in the "expected behavior" part of the above comment, don't happen on the test environment.
- look at the`status` in the heading on both images below
- look at the `status` in the data table on both images below

the way that it's acting on test, _is_ the way we were suggesting it be done. unclear why it isn't showing that way locally...

| local | test|
| --- | --- |
| ![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/06a2587b-ef83-40e0-b758-b45fe76fa37f) | ![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/26c007cc-2dc2-46a4-8a1c-10a600c1fe10) |

https://images.zenhubusercontent.com/242185115/cfbff818-c288-484a-b2da-dba2728022dc/1157_test.mp4

**Comment by mikeapp** [comment]
Interesting that uploading the asset successfully in a later job changed the status in job #314.

![Screen Shot 2021-04-07 at 2.23.55 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/c2ea86b0-884b-4532-bc82-0ccd1ea2abf1)
