### ISSUE TITLE
Users table: default sort to NetID ascending

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1166]
Currently the Users table sorts by NetID descending

**Acceptance**

- [x] The Users datatable sorts by NetID ascending.

**Comment by dylansalay** [comment]
Co-author: Alisha Evans <alisha@notch8.com>
Co-author: Dylan Salay <dylan@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-management/pull/567

# Expected behavior
- The users datatable is ordered in ascending order by netid
- All other datatables are still ordered in descending order

# Demo
| Users | Batch Process |
|---|---|
|![Screen Shot 2021-03-17 at 4 16 17 PM](https://user-images.githubusercontent.com/50561476/111550922-5b087300-873c-11eb-8ac1-b8d63888b990.png)|![Screen Shot 2021-03-17 at 4 16 54 PM](https://user-images.githubusercontent.com/50561476/111550943-6196ea80-873c-11eb-8bc9-7e5ae009865d.png)|

**Comment by martinlovell** [comment]
I think the using options in the config is causing issues.  It's affecting the header filter: 

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/62f9c77a-21df-47f9-9774-06c7e5330b0f)
