### ISSUE TITLE
Index language codes in Solr when available;  for use in MODS and Dublin Core

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1173]
**Story**

Structured data formats such as MODS can allow use of both the language code and the English string.
See https://www.loc.gov/standards/mods/userguide/language.html for examples.

I believe you will need to use metadata from a Voyager record to test this.

**Accpetance**

- [x] The language code is mapped into MODS and DC when available from Voyager.
- [x] The languageTerm has the correct attributes, as in the second `languageTerm` example here:
```
<language>
  <languageTerm type="text">French</languageTerm>
  <languageTerm type="code" authority="iso639-2b">fre</languageTerm>
</language>
```
- [x] The handling of Ladybird data remains unchanged (i.e., remains `<languageTerm type="text">` with the name of the language, not the code)

**Comment by martinlovell** [comment]
Added languageCode_ssim to solr record in management with: https://github.com/yalelibrary/yul-dc-management/pull/599

OAI generation in blacklight can use languageCode_ssim to get the language code(s) from the solr record.  (In blacklight.)

**Comment by martinlovell** [comment]
PR for blacklight:
https://github.com/yalelibrary/yul-dc-blacklight/pull/527

**Comment by martinlovell** [comment]
For Dublin Code, languageCode_ssim is used _**instead**_ of language_ssim.  There doesn't seem to be an easy way to have dublin core first try languageCode_ssim and fall back to language_ssim if languageCode_ssim is nil.

See: https://github.com/projectblacklight/blacklight/blob/master/app/models/concerns/blacklight/document/semantic_fields.rb#L36

Let me know if I should dig a little deeper so that it does fall back to language_ssim for dc.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.5

**Comment by mikeapp** [comment]
I think this needs to wait on a management release as well.

**Comment by martinlovell** [comment]
Re-indexed ILS record on UAT to get language code into SOLR for testing: https://collections-uat.library.yale.edu/catalog/oai?verb=GetRecord&metadataPrefix=oai_mods&identifier=oai:collections.library.yale.edu:15811567
