### ISSUE TITLE
UV manifest URL should not include .json

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1194]
**Explanation**

The URL of the IIIF Manifests should not include the `.json` extension.   When the UV is instantiated,  the `.json` extension is included:

![Screen Shot 2021-04-01 at 10.29.15 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/489fe9d5-78a0-4b6e-bcaa-1eb2bba0b66b)

**Acceptance**

- [x] The `.json` extension is removed

**Comment by alishaevn** [comment]
co-author: dylan salay <dylan@notch8.com>
co-author: alisha evans <alisha@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/502

# Expected behavior
- The URL of the IIIF Manifests should not include the .json extension.

# Demo
| before | after |
|---|---|
|![Screen Shot 2021-04-07 at 10 42 23 AM](https://user-images.githubusercontent.com/50561476/113910737-07fb6c00-978e-11eb-9017-78bbf36eb888.png)|![Screen Shot 2021-04-07 at 10 42 44 AM](https://user-images.githubusercontent.com/50561476/113910766-1053a700-978e-11eb-927a-8595aeb1b78d.png)|

**Comment by alishaevn** [comment]
This is working on `Branch:1194-remove-.json-from-UV-manifest-url,Deployed:2021-04-07T18:36:29-04:00 `
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/6814c14b-96db-4042-8045-22e19c08db6c)

**Comment by FCRodriguez7** [comment]
| before | after |
|---|---||![Screen Shot 2021-04-16 at 9.21.44 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a67f19a0-fc12-4f6d-9bf3-7245f42e1280)|![Screen Shot 2021-04-16 at 9.20.49 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6b04422e-325c-4a93-a5d7-1996e2483c28)|
