### ISSUE TITLE
Make user(s) sysadmins when running in development environment

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1195]
**Story**
As a developer, I would like a way to either set all users to sysadmin during startup in development mode, or some way to specify one user to be sysadmin during startup in development mode.

User bootstrapping was updated so users are not made sysadmins. (A good thing)
However, in development mode with a fresh DB, no users will be sysadmins.

Work around: set yourself as sysadmin using rails c:
```
cam sh management
rails c
User.find_by_uid('NET_ID').sysadmin = true
```

**Acceptance**
- [x] When creating **new** users from the bootstrap file, make them sysadmins.
- [x] Existing users in the boorstrap file should also be made sysadmins if they are not
- [x] Users not listed In the bootstrap file should be left as-is (i.e., not deleted, not promoted to sysadmin).  Done in #1150?

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/586

# Expected Behavior
- users in the "authorization/cas_users.csv" file on S3 will be created as `sysadmin` in the local dev environment only
- we pushed the branch to test and followed the same steps in "testing instructions" below. the user was not made a sysadmin after running the seeds in the ecs container

# Demo
### on dev
https://user-images.githubusercontent.com/29032869/113777131-864d0500-96df-11eb-9e91-959daa4e5478.mp4

# Testing instructions
- sign in to the management app
- remove yourself as a sysadmin (through the UI or console)
- run the seeds in the container `bundle exec rails db:seed`
- verify in the ui that you're a sysadmin again
