### ISSUE TITLE
URLs not under /catalog return 404 HTTP response code but a blank page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1219]
**Story**
URLs not under /catalog return 404 HTTP response code but no human-readable content, for example: https://collections-uat.library.yale.edu/floof

See #936

**Acceptance**
- [x] 404 URLs under the root return an error page.

**Comment by alishaevn** [comment]
co-author: dylan salay <dylan@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/515

# Expected behavior
- invalid url's from the root endpoint will show the branded 404 page

# Demo
![Screen Shot 2021-04-20 at 12 11 57 PM](https://user-images.githubusercontent.com/29032869/115451181-b90ff680-a1d1-11eb-944e-399a34b88224.png)

# Resources
- https://stackoverflow.com/questions/1013152/one-controller-rendering-using-another-controllers-views

**Comment by FCRodriguez7** [comment]
in test environment: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0cfead39-187a-4a7b-a9e7-b469142e6b47)

**Comment by FCRodriguez7** [comment]
release v1.42.0
