### ISSUE TITLE
Message passing from Universal Viewer iframe to object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1225]
**Story**

We have two desired features that will require the page for an object to have the identifier of the image that the user has selected in the Universal Viewer.   The use cases are:

* The user wants to download the current image
* The user wants to display the full-text OCR/transcription for the current image

To make this possible, we'd like to have the UV pass this data to the the containing page.  Rob has indicated that Notch8 has done this work on other projects.

**Acceptance**
- [x] UV sends the image OID to the containing page. 
- [x] If UV is in book reader/2-up mode, OIDs of both visible pages are sent 
- [x] Provide a means of verifying the implementation, such as updating  the image ID in a hidden <div> in the object page or writing the data to the Javascript console.

**Comment by oraposa** [comment]
Please connect with @oraposa (Steve Fox) for pairing.

**Comment by alishaevn** [comment]
The second acceptance criteria item is blocked by https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/142.

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>
co-author: rob kaufman <rob@notch8.com>
co-author: steve fox <steve@curationexperts.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/519

# Expected behavior
- a parent object with "paged" set as the viewing hint
  - will show one child oid at a time in the hidden div with the id of `uv-pages` if in 1 page mode
  - will show one child oid at a time in the hidden div with the id of `uv-pages` if in 2 page mode **but** it's the first or last child oid
  - will show two child oids at a time in the hidden div with the id of `uv-pages` if in 2 page mode and it's not the first or last child oid
- a parent object _without_ "paged" set as the viewing hint
  - will show one child oid at a time in the hidden div with the id of `uv-pages`

# Demo
https://user-images.githubusercontent.com/29032869/116319911-28568f00-a76c-11eb-936d-586baad47cb2.mp4

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.5
