### ISSUE TITLE
Investigate failing PTIFFs and PDFs in PROD

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1227]
**Story**

Prod is showing a number of failures after the last reindex.

![Screen Shot 2021-04-18 at 2.54.29 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/ae4d9727-bef0-4cb2-88e5-1a46db0569f5)

**Acceptance**
- [x] Investigate and report back.

**Comment by martinlovell** [comment]
I noticed that some of the missing PTIFFs are from parent 2065323.

2065323 in a list from Jay 04/17/2020  (last year) and at that point had 187 children.
It has 245 now in LB.

The 187 children were copied on 5/15/2020.

Since it was previously copied, Jay's python script that generates the child list doesn't include it in a new child list.  So, it didn't make it to and more recent gap loads.

**Comment by FCRodriguez7** [comment]
A list of the child oids for investigation

**Comment by mlooney** [comment]
[https://app.zenhub.com/files/242185115/695da6b5-de49-497d-83dd-b36fc742b08c/download](https://app.zenhub.com/files/242185115/695da6b5-de49-497d-83dd-b36fc742b08c/download)


I think this is what you are looking for? if not, I can work backwards to get the parent, and find *all* the children.

**Comment by martinlovell** [comment]
Looking at some more of these, it looks there's a significant number that were ingested earlier when they had fewer children.
(They are pretty recently changed...some have different parents on LB test than on LB production.)
So, I think if we re-queue these based on the parent oids, and then do an image copy, a bunch of the missing access master failures will clear up.

I'm not sure of how to best identify items that are ingested and now have more children before we get the errors after a metadata refresh.

**Comment by mlooney** [comment]
[https://app.zenhub.com/files/242185115/87d4dfa4-5270-4b2f-a9fa-ecbd40778454/download](https://app.zenhub.com/files/242185115/87d4dfa4-5270-4b2f-a9fa-ecbd40778454/download)



list in format [[child,parent], ...]

**Comment by martinlovell** [comment]
Running into some missing images when re-processing the parents:

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/d966bf37-ccab-4af4-9050-5a5cf13e4f98)

These are the child OIDs: 
1457076
15534550
15812715
17305219
11553607

This is after re-scanning: /fc_Beinecke-807001-YUL/TIFS_FROM_JP2

I'll try re-scanning some other folders.

**Comment by rebeccahirsch** [comment]
From David: 

1457076--Image Missing, needs to be re-shot
15534550--Image Missing, needs to be re-shot
15812715--Image Missing, needs to be re-shot
17305219--Derivative TIFF here:

\\storage.yale.edu\home\DSU_Beinecke-CC0691-YUL\IMAGES-DERIVATIVE_TIFF-2020-2021\Patron_1781


11553607--Image Missing, needs to be re-shot

These are also missing: 1193077, 1193078, 1193079--Derivative TIFFs for these three here:

\\storage.yale.edu\home\DSU_Beinecke-CC0691-YUL\IMAGES-DERIVATIVE_TIFF-2020-2021\RIP_Patron_40

I would delete the missing OIDs for now so that the items can go through without them.
