### ISSUE TITLE
Image servers periodically unhealthy 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1237]
It looks like we've had the image servers become unhealthy again, even after our fix of the logging output. 

**Acceptance**
- [x] Investigate possible causes and report back

**Comment by mlooney** [comment]
I checked the disk usage on the instances over the last 7 days, they are all stable at 46%, nothing interesting in any of the other metrics.


checking logs shows some access problems on the 24th?


[1;31mERROR[0;39m [36me.i.l.c.a.TaskRunner[0;39m - run(): Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: ETAXD4GN7XQGJRKB; S3 Extended Request ID: 3fXYZtBX6Eu1oGn2y6Z7dyOevFZa8Nc2d0W2Kdb+PP2BR0jgQvzZLjgR3F8Qp++vhczfrRBeS4s=)

**Comment by mlooney** [comment]
A few mentions of:


2021-04-19 13:16:56Caused by: java.lang.IllegalArgumentException: The specified dimensional parameter is non-positive.
java.io.IOException: yul-dc-prod-images/ptiffs/99/10/01/79/1001799.tif

and:

Caused by: io.minio.errors.ErrorResponseException: We encountered an internal error. Please try again. (possibly related)

Occurred 4/19
