### ISSUE TITLE
Extract and upload full text for each page from Beinecke transcription files

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1256]
**Story**

The Beinecke has been transcribing works using a third-party platform (FromThePage).   We have exports of this data in TEI XML format (https://tei-c.org).  The TEI has references to the IIIF image URLs for each page embedded in the transcription.   These URLs contain the image/child OID for the page.   

**Acceptance**
The goal of this ticket is to write a utility that, given a TEI file:
- [x] Breaks out the transcription by page
- [x] Identifies the child/image OID for the page
- [x] Stores the transcription file in a pair tree in the Test environment's OCR S3 bucket (`yul-dc-ocr-test`) using the following scheme (see note below):
  - [x] all files are stored under under `fulltext` directory
  - [x] within the `fulltext` directory use the standard pairtree directory scheme (use the Partridge gem for this)   
  - [x] use the OID for the filename, with the `.txt` suffix

**Note:**  the `aws s3 cp  .... --recursive` command can be used to upload a local directory tree to the server, so it is going to be easier to write the text files to a pair tree locally and then copy it.

**Comment by martinlovell** [comment]
Do we have a representative set of tei files from FromThePage to use as samples?

**Comment by martinlovell** [comment]
Added initial parser with readme to yale git.

We can point it to an S3 bucket for the TEI files and upload files to S3 using pair tree.

**Comment by martinlovell** [comment]
Updated app so that it reads TEI from local directory (searching for all .xml files and parsing.)
Added option to write files locally for testing.

Uploaded 7438 documents to S3 for children from zip files from BRBL transcription project:

List of files:
[https://app.zenhub.com/files/242185115/3ca9e7b0-c80d-4afe-a4b9-3325f0b88164/download](https://app.zenhub.com/files/242185115/3ca9e7b0-c80d-4afe-a4b9-3325f0b88164/download)
