### ISSUE TITLE
Check for full text availability in Parent Object

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1258]
**Story**

As we implement full text indexing, it would be helpful to have a method on the parent object that lets us know whether it has full text available.

**Acceptance**
- Implement a `fulltext?` method on the ParentObject.  It should:
   - [x] Return `true` only if the parent has at least one child and a `.txt` file exists in the OCR bucket for the first child OID.
- [x] Display this value in the ParentObject's show page, e.g.   "Full text available: true"

**Comment by mikeapp** [comment]
@dylansalay  I've clarified the first item - i.e., just check the first child OID and if it has a .txt, assume the object has full text for all children.

**Comment by dylansalay** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>

# Ticket
https://github.com/yalelibrary/yul-dc-management/pull/602

# Expected behavior
- A ```full_text?``` method on a ParentObject returns true if a .txt file exists in the OCR bucket for the first child OID.
- This value is displayed on the ParentObject's show page, e.g. "Full Text Available: true"

# Demo
![Screen Shot 2021-05-07 at 8 38 52 AM](https://user-images.githubusercontent.com/50561476/117474370-b3bfe500-af0f-11eb-8090-46034f43b3e3.png)
![Screen Shot 2021-05-07 at 8 38 25 AM](https://user-images.githubusercontent.com/50561476/117474422-bb7f8980-af0f-11eb-8a6d-9b882a260370.png)
