### ISSUE TITLE
SPIKE: Solr full-text suggest component

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1279]
**Story**

We want to create a full-text suggest component for page-level content.   Before we do this, we need to understand the correct configuration.  There were issues earlier in the development cycle that caused us to turn off the suggest component.   Note that the suggestions would be based on the page-level full text, not other metadata, and we would want to use it only for the IIIF search service, not for general searches.

See:
https://github.com/projectblacklight/blacklight/issues/1972
https://lucidworks.com/post/solr-suggester/
and we removed one for other metadata in this commit:
https://github.com/yalelibrary/yul-dc-solr/commit/866826b127e500944416d79e9fc38a679714bd7c#diff-e6ea5f3240fbfd7151dab29d014a6880ff4ff74698ebfed575cddd43a0708fcb

**Acceptance**
- [ ] Research and document Solr suggest component configuration
- [ ] Document performance concerns and any need for increased resources on the Solr VM.

**Comment by martinlovell** [comment]
Generator from Gem: https://github.com/boston-library/blacklight_iiif_search/blob/master/lib/generators/blacklight_iiif_search/solr_generator.rb

**Comment by orangewolf** [comment]
Looks like this will create a seperate index which needs to have JUST the child transcriptions indexed.  The less we put in each document of this index the better. It is not the size of this index overall (though that can get problematic as it will be large) it is an individual entry getting to big that causes the suggest bug.


Blacklight-iiif-suggest uses this deprecated library (that was updated for Solr 8)
https://github.com/sul-dlss-deprecated/solr-tokenizing-suggester/releases

Most relevant quote:
https://github.com/projectblacklight/blacklight/issues/1972#issuecomment-435437908

Other links
https://lucidworks.com/post/solr-suggester/
https://solr.apache.org/guide/8_8/suggester.html
https://blog.griddynamics.com/utilizing-solr-suggester-for-typeahead-search-engines/

**Comment by orangewolf** [comment]
From cbeer https://share.getcloudapp.com/NQuoRY4Z

cbeer  11:32 AM
huh, i didn’t know BPL was using it. we gave up on the custom tokenizer because it was a pain to maintain across solr versions, produced some pretty large indexes with our corpus at least, and didn’t do that good a job helping our users get to stuff anyway.

Rob Kaufman  11:33 AM
are you doing something different for iiif in document search or did the whole feature get removed?

cbeer  11:33 AM
we still do search through https://github.com/sul-dlss/content_search/, just without the suggestion/autocomplete feature

Rob Kaufman  11:35 AM
thanks! prohibitively large and a pain to maintain were exactly the kind of warning signs I was looking for.  I'll talk to the team at Yale and see how they want to proceed before I dig too much further

cbeer  11:39 AM
yeah; if you need autocomplete, it’d be a good idea to figure out what your users actually want and figure out how to deliver good search suggestions, not just text matches from the document.
11:41
and you might need different approaches based on the type of document, quality of ocr, etc, etc.. which, for the amount of full-text searching we have, wasn’t worth the effort. at least from our sampling, users already knew what they were looking for by the time they got to the document and didn’t need our (somewhat useless) help.

Rob Kaufman  11:46 AM
that makes sense. the Yale text corpus is a lot smaller at least for now; which may make it more feasible. I'll chat with stakeholders and see what direction they want to go
