### ISSUE TITLE
Display the "format" of the work in search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#129]
**STORY**
As a cartographer, I would like to be able to scan the format of the materials in my search results, so that I can quickly identify which results might be images of maps

**DETAILS**
The ladybird source metadata contains a field called `format` which represents a small controlled vocabulary for the high-level format of the work.  In the current BRBL DL, this facet is called "Type of Resource".   We will need to update the current work fixtures to include the format field from ladybird.

**ACCEPTANCE**
- [x] When I search the application, search results display the `format` of each work
- [x] With the sample data, format includes (but is not limited to) the values 'text' and 'cartographic'

**Comment by edejesusyale** [comment]
With the change to the `voyager_indexing_service.rb` that Frederick and I made in #128, the format should be shown since the format field was already set up. After reindexing the fixtures to add the format field:  ![Screen Shot 2020-05-12 at 3.00.10 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/05145213-64fb-4312-91a5-19709cea0ed6)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/35

**Comment by FCRodriguez7** [comment]
Bess' example https://github.com/emory-libraries/dlp-lux/tree/master/spec/system Maybe look at these examples?
