### ISSUE TITLE
Put Label field before Caption on child object view/edit pages

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1294]
**Story**

![Screen Shot 2021-05-14 at 11.37.21 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f3c41c8c-d023-469d-8a9f-856cc7653de0)
edit page

The label field is more essential than the caption, so it should be displayed first on the Child Object view and edit pages.

**Acceptance**
- [ ] Label comes before caption on the child object view page
- [ ] Label comes before caption on the child object

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/624

# Expected behavior
- all instances of "label" and "caption" on a child object have been swapped so that "label" comes first

# Demo
| show | edit |
| --- | --- |
| <img width="600" alt="image" src="https://user-images.githubusercontent.com/29032869/118717320-c6bd9980-b7da-11eb-86df-528c0c85d9a3.png"> |<img width="711" alt="image" src="https://user-images.githubusercontent.com/29032869/118717374-d89f3c80-b7da-11eb-9ce7-9a45c4d047ce.png"> |

| list | new |
| --- | --- |
| <img width="1198" alt="image" src="https://user-images.githubusercontent.com/29032869/118717498-01273680-b7db-11eb-9066-28ebf9e32c8d.png"> | <img width="686" alt="image" src="https://user-images.githubusercontent.com/29032869/118717552-100de900-b7db-11eb-94c1-d4baa810f9f6.png"> |

**Comment by FCRodriguez7** [comment]
Management Release v2.37.0
