### ISSUE TITLE
Performance Test IIIF Server Options re: Pyramidal TIFF

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#13]

**Comment by edejesusyale** [comment]
[100 trials of requesting random widths and heights of a single image from L(oris) and C(antaloupe)](https://app.zenhub.com/files/242185115/d04f9980-8dba-4449-b102-4f2d83f558a5/download)

After investigation, there are currently only two image processors for Cantaloupe that will switch between the layers of a PTIFF: Java2DProcessor and JaiProcessor.

**Java2DProcessor**: There is an issue open on Cantaloupe about Java2DProcessor using ptiffs/tiled tiffs: https://github.com/cantaloupe-project/cantaloupe/issues/311. It is similar to the testing that I've done, with processing happening on the scale of seconds instead of milliseconds. This issue has been open since July and I don't believe work is being done currently to optimize that.

**JaiProcessor**: From what I have read, JaiProcessor is the most optimized processor. However, it is not currently being developed anymore and is starting to become deprecated.

**Comment by edejesusyale** [comment]
[50 trials with different sizes](https://app.zenhub.com/files/242185115/8ed41db3-1359-433c-af75-8f31d581db9e/download)

Frederick helped me sort through the other results and realized that the most time consuming requests from Cantaloupe was when the largest layer was used to process the request. The above has the results of making requests between the largest and 2nd largest layers. The ptiff has different colors for each layer for testing purposes. The largest layer is red and the second largest layer is green. As is seen in the excel, when requests are large enough to use the red layer, the time for cantaloupe to respond jumps by 30-70x.

**Comment by mark-dce** [comment]
We've settled on Cantaloupe for the development portion of Phase 1 and will revisit this issue if Cantaloupe does not perform as required during Phase 1 performance testing.
