### ISSUE TITLE
Use metadata from Ladybird rather than Voyager as the initial fixture data

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#131]
**ISSUE**
Our initial fixtures are populated with the Voyager metadata extracts, but the current BRBL DL is driven by metadata provided by LadyBird.  The LadyBird metadata can potentially have diverged from Voyager, so for initial comparison and testing purposes, we should use LadyBird as the metadata source for development.

**ACCEPTANCE**
- [ ] Sample fixtures are based on the ladybird OID-based metadata samples

**Comment by yjyale** [comment]
That's right. LadyBird oid should be the entry point, because oid is the unique identifier for each image. 

In the full set of records, could have at least 3 following scenarios:
1. Some images may have neither Voyager record nor ArchivesSpace record associated with. That means these images only have LadyBird records. (orphan child or independent singleton object)

2. Some images may only have either Voyager, or ArchivesSpace associated with, but not both.

3. Some images may share the same Voyager record or ArchivesSpace record. (multi children -> parent and/or grandparent relationship)

**Comment by RachelDCE** [comment]
Fixed as side effect of other work.
