### ISSUE TITLE
Implement autocomplete - Solr Update

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1327]
**Story**

We'd like to implement search suggestions/autocomplete per the IIIF Search API.  See https://iiif.io/api/search/1.0/#autocomplete and the gem documentation for more details.

**Acceptance**
- [ ] Implement the Solr changes resulting from the related spike

**Comment by martinlovell** [comment]
Since we just need starts with queries for now, we are going to try implementing it using facet queries against the child objects.

We are updating the child records to index both a tesim and tsim of the text.
tesim is used for searching as it is already, tsim is just for the facet query.  We don't want stemming for the facet query, but do for search.

We will also update fulltext_tsim on the parent to be fulltext_tesim so stemming works for non-iiif full text searching.

Queries for facets on the text field return terms:
http://localhost:8983/solr/blacklight-core/select?rows=0&facet.field=child_fulltext_tsim&facet=on&q=parent_ssi%3A2005512&facet.prefix=t

The Boston Library gem is not setup to work with the facet query results, but we can implement the suggest using some of the code from the gem.

This work in is in the fulltext_suggest_experiment branch currently.

**Comment by FCRodriguez7** [comment]
Approved PR: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/cdb3ec80-f48a-4ff4-8a6b-7e9c3794db22)
