### ISSUE TITLE
Orbis redirect to DL with call number search not working

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1340]
**Story:**
Click :[View a selection of digital images in the Beinecke Library's Digital Images Online database](http://beinecke.library.yale.edu/dl_crosscollex/callnumSRCHXC.asp?WC=N&SS=N&CN=Sh15_0162) on the Orbis record
https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=1329237

Problem 1: Got **No results found for your search**
Although the record exists: https://collections.library.yale.edu/catalog/16039409
(another record has the same issue: https://collections.library.yale.edu/catalog/30850093)
Problem 2: Call number does not show in the result page 

Note:  This appears to be an issue with partial matches not working.

**Acceptance:**
- [ ] Research whether we can match when the search text has the call number as well as additional text.

**Comment by martinlovell** [comment]
Oid: 16039409 (call number Sh15 0162) doesn't have the call number indexed in solr on collections.  It does have a callnumber in ladybird now, so authoritative metadata has a callnumber, but it's not reindexing because it's missing an image now.  (Maybe an image was added since the first ingest.)
Missing image is: 17382263

For https://collections.library.yale.edu/catalog/30850093, if I click the orbis link, and then the "View a Selection of ..." link in orbis to get back to collections, there are 7 results.  The last one is 30850093. It does appear in the results with the call number visible.  So, it seems like the partial match did find the record, although it is the last result.

**Comment by martinlovell** [comment]
Found image 17382263 for "Sh15 0162" on valkyrie POC and copied to pair tree, retried job for that ptiff.  Parent was indexed and now link from orbis works.
