### ISSUE TITLE
Add filter/sort capability to Child Objects data table

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1344]
**Story**

As a management user I'd like to be able to filter and sort in the child objects data table ( https://collections.library.yale.edu/management/child_objects ) like I can in the Parent Objects table.

**Acceptance**
- [x] convert child objects table from Rails to data table
The user can:
- [x] filter by child OID (i.e., same behavior as parent OID in parent data table)
- [x] filter by parent OID
- [x] The user can sort by any column
- [x] OPTIONAL: filter by caption (likely a performance issue here!)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/640

# Expected behavior
- the child objects table is now a datatable
- the user can:
  - filter by child OID
  - filter by parent OID
  - sort by any column
  - filter by caption

# Demo
https://user-images.githubusercontent.com/29032869/120396346-42dfd300-c2eb-11eb-9d8f-027b0a86c551.mp4

**Comment by FCRodriguez7** [comment]
Released management v2.39.0
