### ISSUE TITLE
Management UI App data table - styling

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1349]
**Story:** 

Modify the table to reflect the styling changes in the design mockup - addition of icons, placement of Pagination and Previous/Next components. 

https://xd.adobe.com/view/8f11c305-11c3-4fa2-8955-4f74f1f08942-da42/

**Acceptance:**
- [x] Update the Parent Objects page to reflect the styling in the adobe link above (everything apart from the navigation and header)
- [x] Update the Child Objects page to reflect the styling/layout of the Parent Objects page
- [x] Update the Admin Sets page to reflect the styling/layout of the Parent Objects page
- [x] Update the Users page to reflect the styling/layout of the Parent Objects page
- [x] Update the Batch Process page to reflect the styling/layout of the Parent Objects page
- [x] Update the Preservation page to reflect the styling/layout of the Parent Objects page
- [x] Update the Notifications page to reflect the styling/layout of the Parent Objects page

**Comment by alishaevn** [comment]
icons - https://fontawesome.com/v5.15/icons?d=gallery&p=2

**Comment by alishaevn** [comment]
question: for pages where the datatable doesn't extend full width (e.g. "sets"), do we:
a) want the border to be hidden and have the pagination/top buttons align with the end of the content?
b) want the entire table to extend full width and be flush with where the pagination/top buttons already are?


(I prefer b, but I haven't figured out yet how to make that happen without other undesired side effects)

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/646

**Comment by FCRodriguez7** [comment]
Released management v2.41.0

**Comment by alishaevn** [comment]
comment from pr 646
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/d51b9cf0-ab30-4466-892b-5db1215277cf)

**Comment by DraxIndustries79** [comment]
PR is only for part of the ticket.  Icons aren't complete yet
![Screen Shot 2021-06-04 at 11.23.08 AM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/5b4b02bb-9ec8-4985-a8cb-b796cfefcfb7)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/656

# Expected behavior
- font awesome has been installed
- the oid on the parent objects page redirects to the show object page in the management app
- the "eye" icon on the parent objects page redirects to the item in the blacklight app
- the "pencil" icon on the parent objects page redirects to the edit object page in the management app
- the "trash" icon on the parent objects page prompts the user to delete the object

# Demo
![image](https://user-images.githubusercontent.com/29032869/121230558-3b1cb300-c844-11eb-9fc2-272f4a232ea6.png)
![image](https://user-images.githubusercontent.com/29032869/121230612-4f60b000-c844-11eb-995d-084f64053908.png)

**Comment by dylansalay** [comment]
Is the Notifications table being used? I think we created this table before we came up with ingest_events. Perhaps it can be removed?

**Comment by alishaevn** [comment]
# PRs
- https://github.com/yalelibrary/yul-dc-management/pull/658
- https://github.com/yalelibrary/yul-dc-management/pull/659
- https://github.com/yalelibrary/yul-dc-management/pull/660
- https://github.com/yalelibrary/yul-dc-management/pull/661
- https://github.com/yalelibrary/yul-dc-management/pull/662

**Comment by FCRodriguez7** [comment]
Released management v2.43.0

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/663

# Expected behavior
- datatable typography has been applied to the 4 batch process pages
- all 4 pages follow the same overall styling of other datatable pages

# Demo
| batch processes | show page |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/121567501-7c8f9880-c9d3-11eb-9e13-cf5e0fc25099.png) | ![image](https://user-images.githubusercontent.com/29032869/121567606-9fba4800-c9d3-11eb-9891-6c6fa3264dc1.png)|

| parent bp | child bp |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/121567677-b6f93580-c9d3-11eb-8374-e51eda6be239.png) | ![image](https://user-images.githubusercontent.com/29032869/121567729-c5dfe800-c9d3-11eb-8d85-13e076565708.png) |

**Comment by mikeapp** [comment]
I think this has already been reported in Slack, but the icons are not appearing on UAT:
![Screen Shot 2021-06-11 at 1.28.00 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7ba717b2-755f-4f92-a27f-be2b53fe318c)

**Comment by FCRodriguez7** [comment]
Released management v2.44.2

**Comment by mikeapp** [comment]
Looks good!
