### ISSUE TITLE
SPIKE: Autocomplete is case sensitive

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1362]
**Story**

The autocomplete for full-text search is case-sensitive, but all index values are lowercased.

For example, with https://collections-demo.library.yale.edu/catalog/17049605 

Searching works fine:
![Screen Shot 2021-06-07 at 9.14.41 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/304cba3c-dfba-4b1b-bae9-e64c7f50bb54)

But no values suggested with uppercase:
![Screen Shot 2021-06-07 at 9.14.55 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/89d6de76-70c6-4637-81e0-326a18d27c06)

Lowercase does match:
![Screen Shot 2021-06-07 at 9.14.47 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/66874863-1b24-4441-82a6-07000da45744)

**Acceptance**
- [x] Search/matching should be case-insensitive
- [x] Displayed values from index should retain their case (e.g., "Spain" not "spain")

**Comment by martinlovell** [comment]
First checkbox is here: https://github.com/yalelibrary/yul-dc-blacklight/pull/567
Second checkbox may be much harder.

**Comment by martinlovell** [comment]
By adjusting the field type and the query, it was possible to retain case and do a case insensitive lookup.

However, the query needed to change to facet.contains from facet.prefix, so the behavior is different.  
There is a facet.contains.ignoreCase option but no facet.prefix.ignoreCase.  So, in order to ignore case, the query uses facet.contains:

https://github.com/yalelibrary/yul-dc-management/pull/657
https://github.com/yalelibrary/yul-dc-blacklight/pull/568
https://github.com/yalelibrary/yul-dc-solr/pull/23

Example with HORSE Horse and horse in the ocr text:
![case-suggest.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/79151aa3-95f7-4871-be7f-8255e09dcdcb)

Notice that "ors" matches horse now.  We'd need to test with larger documents to see how this affects the user.

**Comment by martinlovell** [comment]
I ended up needing to use Solr schema API to add the new dynamic field to an existing index.
I also had to setup new field type since the original choice (text_ws) didn't remove punctuation.

Both of these changes are in the schema.xml in the Solr PR, and are also applied as a migration which uses the schema API in the management PR.

**Comment by martinlovell** [comment]
Running tests locally after a fresh solr core (after cam down) requires running the newer Solr image.

Add to cameratarc:
```
ENV['SOLR_VERSION'] = '1362_fulltext_suggest_retain_case'
```

**Comment by mikeapp** [comment]
Looks good on demo.
