### ISSUE TITLE
Toggle for full-text display area 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1380]
**Story**

As a user, I'd like the option to show the transcription for the child object or object(s) that are selected in the Universal Viewer.    This will be shown beneath the Universal Viewer.

This issue focuses on creating the display area and button to toggle its visibility.  Issue #1370 will implement the display of the transcription text.

**Mock Up**

Closed:
![full_text_closed.jpg](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/465bdefc-613c-4d98-8716-22bbae6001c5)

Open, single page focus in UV:
![full_text_open.jpg](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/862e274d-c5d8-4ec9-b450-d3c78b9971b8)

Open, two-up view (IIIF viewing hint `paged`) in UV:
![full_text_two_up.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3d898376-79eb-4a30-ae07-79bddc966d48)

**Acceptance**
- [ ] For objects with full text available, a "Show full text" link/button displays beneath the UV viewer.
   - [x] The button is only displayed if the user has permission to view images
   - [x] The button is right-aligned
   - When clicked:
       - [x] An area below the UV is created, populated with static text ( "Lorem ipsum..").
       - [x] The button text changes to "Hide full text"
   - When open, clicking the button again should
       - [x] Remove the displayed text
       - [x] Change the text of the button back to "Show full text"

**Comment by dylansalay** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/581

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/581

# Expected behavior
- [x] For objects with full text available, a "Show full text" link/button displays beneath the UV viewer.
   - [x] The button is only displayed if the user has permission to view images
   - [x] The button is right-aligned
   - When clicked:
       - [x] An area below the UV is created, populated with static text ( "Lorem ipsum..").
       - [x] The button text changes to "Hide full text"
   - When open, clicking the button again should
       - [x] Remove the displayed text
       - [x] Change the text of the button back to "Show full text"

# Demo
| with full text | w/o full text |
| --- | --- |
| https://user-images.githubusercontent.com/29032869/122269564-35e9e480-ce92-11eb-83cd-882944372f04.mp4 |
https://user-images.githubusercontent.com/29032869/122269594-3e421f80-ce92-11eb-8d17-3bef78da78c6.mp4 |
