### ISSUE TITLE
Refactor activity_stream_reader.rb

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1385]
**Story**

The `lib/activity_stream_reader.rb` class was implemented early in development and is out of date.   It needs to be refactored to fit into the current application.   The code is not called by the application currently, but there is an existing rake task to invoke it.

The intent of this class is to trigger a metadata refresh for each ParentObject that has been impacted by an update in the upstream catalogs of record (ArchivesSpace and Voyager).   The catalog records are hierarchical and any update within the hierarchy might necessitate a refresh of a record.  As a result there can be more than one identifier (recorded as a DependentObject) associated with the parent.  

The high-level workflow is:
1. Read the Metadata Cloud Activity Stream, going backwards in time, and record all of the ASpace and Voyager URIs that have changed since the last time the job was run.
2. Determine which ParentObjects have DependentObjects that are in the change set.   (Note we are only doing this for records whose metadata source is ASpace or ILS/Voyager).
3. Queue a metadata update job for each ParentObject that has changed.

**Acceptance**
- [x] The job reads the activity stream and builds a set of object IDs that have been updated.  (This may be done, but review.)
- [x] The job determines which parent objects have dependent objects that are included in the set that has been generated from the activity stream.
  - [x] The `ActivityStreamReader.update_local_dependent_uris` method needs to be rethought; issue #1384 will ensure that the dependent URIs are kept up to date whenever a parent is reindexed.
- [x] The job queues a metadata update job for each parent object that requires an update.   (The code that downloads the metadata JSON record in `refresh_updated_items` is obsoleted by this approach.)
  - [x] It should trigger only one job per parent, regardless of how many dependent objects are found in the activity stream.   
  - [x] Only those parents with a metadata source of Voyager or ASpace should be updated.   Records that are using metadata from Ladybird should be ignored.
- [x] The job should log its activity (already done in the `process_activity_stream` method).

Note that there are millions of entries in the activity stream, at least in production Metadata Cloud.  It should be possible to create an ActivityStreamLog record with a recent timestamp; the code stops processing the activity stream when it reaches an event that has a timestamp earlier than the of time the last log record.

**Comment by martinlovell** [comment]
Added some additional requirements:
- [ ] Skip parents that have been updated since the most recent dependent items update
- [ ] Skip parents who have a SetupMetadataJob queued.
- [ ] Create a batch for the jobs in each activity stream run.  (Or should we create a separate batch for each parent?)

The original design read the entire activity stream if it had not be previously read.  Changed to start at the current time and only responds to new activity stream entries.

The last run time is changed to use the most recent date in the activity stream to avoid problems with server times being out of sync.

Some parents will be picked up on subsequent runs, but should be skipped based on the "skip" criteria.  This is because of date/time precision. Some entries will have the exact same time, so entries with dates equal to the last run time must be considered possible changes.

PR/WIP:  https://github.com/yalelibrary/yul-dc-management/pull/678

Next steps: Deploy to test, have someone modify some ILS and ASpace items in test.  (Using test voyager and test aspace.)  Then we can manually trigger an activity stream check.

**Comment by FCRodriguez7** [comment]
Released management v2.45.5
