### ISSUE TITLE
Move "delete"  button to Parent Object display page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1401]
**Story**

Both "delete" and "update metadata" are critical actions that should not be available in the Parent Objects datatable due to the potential for accidental modification of the wrong object.   We'd like to move them to the Parent Object display page.

This ticket addresses the "delete" button.

**Acceptance**
- [x] The delete button is removed from the Parent Objects datatable
- [x] The delete button is added near the bottom of the Parent Object display page as shown
- [x] Clicking the delete button retains the current behavior of showing a confirmation dialog.

![MoveButtons.jpg](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/42781d2b-60b0-412d-94b0-b1d08ada72b0)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/682

# Expected behavior
- the "delete" icon is removed from the "actions" column on the parent datatable
- a delete label, help text and button show at the bottom of the parent object show page

# Demo
![image](https://user-images.githubusercontent.com/29032869/123846190-e95acc00-d8c9-11eb-8c92-0114cb1fa278.png)

**Comment by FCRodriguez7** [comment]
Released management v2.45.6
