### ISSUE TITLE
Add fields to single item view - Titles & Keywords

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#144]
**STORY**
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

**NOTE**
Use the ladybird field name as the label for now.

**ACCEPTANCE**
The single item view for a work displays the metadata for the following fields when they are populated:
- [x] title
- [x] author (creator)
- [x] description
- [x] format
- [x] abstract
- [x] alternativeTitle
- [x] genre
- [x] geoSubject
- [x] resourceType
- [x] subjectName
- [x] subjectTopic

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/45

# Summary
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

# Expected behavior
When viewing a work that has the fields below, they will show up on the page:
- abstract
- alternativeTitle
- genre
- geoSubject
- resourceType
- subjectName
- subjectTopic

# Demo
![Screen Shot 2020-05-20 at 11 38 17 AM](https://user-images.githubusercontent.com/29032869/82485551-752be300-9a90-11ea-8fc2-436112efc804.png)


**the tests are currently failing on all new PR's. it's being worked on in another branch and that solution should fix our failed pipeline in CI too.**

**Comment by alishaevn** [comment]
Note:

In order to achieve the view above, Eric and I added strings to the `app/services/voyager_indexing_service.rb` file. (Seen below)

Those changes were not included in the MR so having this ticket work in production will rely on the management or performance team updating that file to map to the correct fields.

```
abstract_ssim: "this is an abstract",
alternativeTitle_ssim: "this is an alternative title",
genre_ssim: "this is the genre",
geoSubject_ssim: "this is the geo subject",
resourceType_ssim: "this is the resource type",
subjectName_ssim: "this is the subject name",
subjectTopic_ssim: "this is the subject topic"
```
