### ISSUE TITLE
Add fields to single item view - Identifiers

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#145]
**STORY**
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

**NOTE**
Use the ladybird field name as the label for now.

**ACCEPTANCE**
The single item view for a work displays the metadata for the following fields when they are populated:
- [x] oid
- [x] identifierMfhd
- [x] identifierShelfMark
- [x] box
- [x] folder
- [x] orbisBibId
- [x] orbisBarcode
- [x] findingAid
- [x] collectionId
- [x] edition
- [x] uri

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/51

# Summary
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

# Expected behavior
When viewing a work that has the fields below, they will show up on the page:
- oid
- identifierMfhd
- identifierShelfMark
- box
- folder
- orbisBibId
- orbisBarcode
- findingAid
- collectionId
- edition
- uri

# Demo
![image](https://user-images.githubusercontent.com/29032869/82940576-ea446000-9f49-11ea-8102-25188630b6c0.png)
