### ISSUE TITLE
Add Extent of Digitization facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#147]
**STORY**
As a scholar, I'd like to filter out results from my searches that aren't completely digitized, so that I can identify resources that I can access online in their entirety.

**NOTE** Use the Ladybird field names for field and facet labels for now.

**ACCEPTANCE**
- [x] There is a facet field for 'extentOfDigitization'
- [x] Search results display the 'extentOfDigitization' when available
- [x] Single item view pages display the 'extentOfDigitization' when available

**Comment by alishaevn** [comment]
Co-authored by [Frederick Rodriguez](frederick.rodriguez@yale.edu)

# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/48

# Summary
As a scholar, I'd like to filter out results from my searches that aren't completely digitized, so that I can identify resources that I can access online in their entirety.

# Expected behavior
- There is a facet field for 'extentOfDigitization'
- Search results display the 'extentOfDigitization' when available
- Single item view pages display the 'extentOfDigitization' when available

# Demo
![image](https://user-images.githubusercontent.com/29032869/82604083-96600280-9b68-11ea-91e9-4a692b888bd1.png)

![image](https://user-images.githubusercontent.com/29032869/82604116-a4158800-9b68-11ea-9151-5431851b29c3.png)

# Note
The `extentOfDigitization_ssim:` field in `voyager_indexing_service.rb` will need to be mapped to the correct path by the management team to make this work show up in production

**Comment by alishaevn** [comment]
Viewable at: https://collections-demo.curationexperts.com/?search_field=all_fields&q=
