### ISSUE TITLE
[Full Text] Hide "Full Text" option from simple search drop down

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1494]
**Story**

We do not want the "Full Text" option to appear in the simple search drop down.  Users should use the radio button instead.

This was included in #1389 but possibly missed?

**Acceptance**
- [x] The "Full Text" option does not appear in the drop down.  Current state show here:

![Screen Shot 2021-08-02 at 5.48.57 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/32cc0be3-ba0d-45bd-951a-a14473379038)

**Note:** May be better to update this in CSS since it's is not showing in all situations and may be an issue with JS.

**Comment by martinlovell** [comment]
Seems like the issue is that safari doesn't do anything with option element's css, like display:none.

It may be that the option has to be removed.  Since we select the fulltext option when the radio is selected, it may need to be added when the fulltext radio button is selected, and the select is hidden.  Or we could pass in the value without the select.

**Comment by mikeapp** [comment]
It looks like we are overriding the partial that renders this, so perhaps we can just exclude from the list as it is built?

**Comment by martinlovell** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/631

It seemed easiest to remove the option on "description" option selected, and put it back and select it when "full text" option is selected (and the select is hidden).

**Comment by martinlovell** [comment]
This has been deployed to UAT.
