### ISSUE TITLE
SPIKE: Approach for scheduling periodic updates

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1543]
**Story**

We'd like to be able to schedule regular metadata updates by polling the Metadata Cloud Activity Stream.  Code for this exists, see ActivityStreamReader.update in https://github.com/yalelibrary/yul-dc-management/blob/main/app/lib/activity_stream_reader.rb

The question is how best to schedule this.  Just use `delayed_job`?  Is there a better cluster-aware scheduling tool (similar to Java's http://www.quartz-scheduler.org)?  

**Acceptance**
- [ ] Identify the best approach to running this job (and possibly others) every x days/hours/minutes

**Comment by orangewolf** [comment]
We've used both https://github.com/tubbo/activejob-scheduler and https://github.com/amitree/delayed_job_recurring in the past.  I like https://github.com/tubbo/activejob-scheduler better because

1) it uses Rufus::Scheduler which is very flexible
2) it has a simpler syntax
3) it is worker agnostic - any activejob class is supported so it can be used on delayed_job, sidekiq, goodjob, whatever.

The downsides are that it hasn't seen a ton of maintenance or uptake and it has a naming conflict with Hyrax.  You'll see a PR that fixes that second one though.

With all the Rails background job schedulers (and really every scheduler I've ever used) there is a first run problem and a deadswitch problem.  If someone manually clears the background queue, these jobs will get cleared and need to be re-added with a rake task, process restart or controller action. And with any recurring event it is very hard to tell when something does not happen, so they can go unnoticed pretty easily.

To combat both of these things we pair recurring jobs with https://healthchecks.io checks.  That will give you an alert if the schedule job doesn't happen.  For this project I'd just recommend a "re-add scheduled jobs" button in the admin interface that can be clicked if the alert goes off. healthchecks.io is open source, so you can install your own instance if you want and is free up to 20 checks.  We pay the $48 a year for the first tier happily as much as a thank you for saving our bacon from time to time as anything.
