### ISSUE TITLE
Migrate select OIDs from the Music Theory Treatises collection to DCS

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1577]
**Story**

Migrate select OIDs from the Music Theory Treatises collection (PID 17) from Ladybird/FindIt to DCS

**Acceptance**
- [x] List of Parent OIDs to migrate: 15751145, 15751351, 15751587, 15737336, 15731192, 15735866, 15752625, 15752925, 15751989, 15752209, 15750889, 15736147, 15750554, 15744039, 15750839, 15750733, 15751769
- [x] Export image files from Fedora 
- [x] Import image files into the DCS pairtree
- [x] Import the objects into DCS in the `mus` admin set

**Comment by kcompsci** [comment]
FYI, the following OIDs are not Parent OIDs but are actually Complex Children form project 3: 1156935, 1154012. Can you please double check these two?

**Comment by motropuk** [comment]
@kcompsci Sorry about that, looks like I included two Voyager Bib ids here rather than OIDS for these items. Here is a corrected full list of parent oids 15751145, 15751351, 15751587, 15737336, 15731192, 15735866, 15752625, 15752925, 15751989, 15752209, 15750889, 15736147, 15750554, 15744039, 15750839, 15750733, 15751769

I have also updated the first checkmark under Acceptance at the top of this ticket, to include this updated list

**Comment by kcompsci** [comment]
@bobrice Can the blacklight user be granted with write permissions in UAT for the /usr/local/libshare directory? We're trying to run the rake task to copy the images but it's failing because the blacklight user can't write to that directory.

**Comment by MaggieZhaoYale** [comment]
INC2092642

**Comment by MaggieZhaoYale** [comment]
Test one parent: https://collections-uat.library.yale.edu/management/batch_processes/400/parent_objects/15751769

**Comment by motropuk** [comment]
@MaggieZhaoYale This looks fine. We can proceed with the whole collection into UAT

**Comment by motropuk** [comment]
Fine to move this collection to Production now
