### ISSUE TITLE
Provide Mgmt UI trigger for metadata load to Solr

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#162]
**ISSUE**
Currently, the fixture data is being indexed to Solr using a rake task from the command line.  This command is tine sensitive and must be run when deploying the application, creating fragile timing dependencies.

We would like to eliminate the timing dependency by changing this behavior to be triggered by a button on a page in the management web application. 

_Acceptance Criteria_
- [x] A system test/spec that runs a browser and clicks the button
- [x] For now, screenshots from Development environment of 
  - [x] page with button, 
  - [x] rake task called on button press (testing whether the rake task runs successfully should be a concern of the rake task, not the button story)

_Implementation notes_
Some of the work this will entail includes:
- Add the bootstrap gem (`gem 'bootstrap', '~> 4.0'`) (may include some additional work, there are tutorials out there, probably need to run yarn)
- Create a view (probably an `index.html.erb`)
- Setting up Capybara to drive a browser in tests, 
  - may include creating a test / development Dockerfile that adds Chromedrivers (see Blacklight app for how to add Chromedrivers, but try to add as separate layer, so it's not in our production build)
- Create a route to that page
- Make a button on that page that does the same thing as the `bundle exec rake yale:index_fixture_data` command line task currently does (that is, takes the existing fixture data and indexes it to Solr)

**Comment by orangewolf** [comment]
In regards to this ticket - it is usually a good practice to move all the heavy lifting out of a rake task leaving only a call to a service class or model (this may already be the case). This makes testing easier, but also means that implementing something like this controller link up stays internal to Rails (a controller calling a service class or model) instead of having to shell out, load rake which instantiates a new rails instance and then runs your task.

**Comment by mark-dce** [comment]
@orangewolf point taken - but let's move any refactoring of the rake task to a new ticket.   I'd like to keep the scope of this ticket small and focused on getting the button to call the existing code.
