### ISSUE TITLE
[On Hold] Distinguish finding aids links from other links brought in from Voyager 856 field

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1636]
**Story**

For objects in DCS that associated with parent metadata in Voyager (ILS), all links found in the 856 MARC field are assumed to be links to finding aids. There are many other types of links listed in the 856 field, in addition to finding aid links. This leads to examples like this https://collections-demo.library.yale.edu/catalog/15952265. The "finding aid" link here, is actually a link to the old BRBL. 

All links to finding aids in Voyager *should* have a subfield ‡3 delimiter in the 856 field (e.g., 856 42 ‡3). Other links *should* be structured 856 42 ‡y. 

However, the safest option here would be to assume all links in the 856 42 ‡3 that start with http://hdl.handle.net/10079/fa are finding aid links. All other links in the 856 field should map to 

**Acceptance**
- [ ] TBD

**Comment by mikeapp** [comment]
@motropuk  A change was made to Metadata Cloud so that Voyager items no longer receive a Finding Aid field.  I updated the metadata, take a look.   We'll need to think about the logic for this.  

I'd suggest that we create a separate ticket to filter the `resourceVersionOnline_ssim` values to exclude BRBL DL links, as suggested above.

**Comment by motropuk** [comment]
@mikeapp This looks good to me and is a good temp fix while we think this through further. I will create a follow up ticket for the BRBL (and other links - we have some ContentDM ones in there too).
