### ISSUE TITLE
Facet filtering displays when clicking on Archival Context breadcrumb

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1688]
**Story**

When clicking on a link below the repository level in a breadcrumb or archival context view, you are taken back to the search results screen with a list of results relevant to that part of the collection hierarchy. However, the facets for Collection (and soon Series) should display. Ideally, these facet headers would also be open and show the active faceting. 

**Acceptance**
- [ ] When clicking on a link in a breadcrumb at or below repository, user is taken to results screen with repository, collection and series facet displayed and open

**Comment by motropuk** [comment]
Need to check in with Archival Context team next week to flesh this out

**Comment by martinlovell** [comment]
FYI: The series facet is in flux because of some requested changes.
Here's a draft PR for it: https://github.com/yalelibrary/yul-dc-blacklight/pull/719
(So, after this PR, instead of going to the series_ssi facet, it should go to series_sort_ssi)

**Comment by K8Sewell** [comment]
Repository treated as facet
https://images.zenhubusercontent.com/242185115/fc2e53a0-ddcc-40b7-8edf-e096777dd095/screen_recording_2021_11_05_at_10_16_41_am.mp4

**Comment by DraxIndustries79** [comment]
Holding on this while we figure out what to do with breadcrumbs.

**Comment by K8Sewell** [comment]
Questions: Currently it's `sourceTitle_tesim` that's being pulled for the Collection Title on the search results page.  

- Should I go ahead and update that on the search result page so that it can be faceted from there as well?  
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/80460432-51ef-482b-bf59-00819d960c94)

Also, there are mechanisms to prevent collection title facets from being selected when repository facets are not also selected.  
- Should I remove the condition that a Collection Title cannot be selected without a Repository being selected?  
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9721bbb4-c692-45d4-8997-5e0e0e5e685a)

**Comment by martinlovell** [comment]
I don't think we should change the way collection is tied to repository.  

I took a look, and was able to get something working with the Found In links in this branch:
https://github.com/yalelibrary/yul-dc-blacklight/tree/hierarchy_links_to_facet

See:
https://github.com/yalelibrary/yul-dc-blacklight/commit/94818a2c0d958e886baccf9f5e82529bd9cb7837
It swaps out the links in the Found In helpers so that they open the other facets based on the level.

**Comment by martinlovell** [comment]
The archival group approved the functionality on Demo.
https://github.com/yalelibrary/yul-dc-blacklight/pull/722

**Comment by FCRodriguez7** [comment]
Released blacklight v1.55.4
