### ISSUE TITLE
SPIKE: Redirect deleted parent OIDs

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1696]
**Story**

When a Parent OID is destroyed by being merged with another, can that process redirect to a different parent OID at the same time?

Here’s an example:  
		
A staff member wants to delete https://collections.library.yale.edu/catalog/10081383 which is a single image from a scrapbook that is available in DCS in its entirety here https://collections.library.yale.edu/catalog/17451921?child_oid=17451962. When https://collections.library.yale.edu/catalog/10081383 is deleted, can there be a way to then redirect that deleted OID to https://collections.library.yale.edu/catalog/17451921?child_oid=17451962. 

Post Spike Task 
- [x] Jon to follow up with Daniel Lovins, Mark Custer and Alison Clemens with results of Spike

**Comment by fordmadox** [comment]
As an automated approach, the above would be great!  

If possible (as the same time, or to be added later), it would also be really nice to be able to override the redirect manually with something more specific when needed.  For example, in this case, https://collections.library.yale.edu/iiif/2/17451962/5320,2675,2500,3325/650,/0/default.jpg?t=1626729138755, would be a more accurate link since the deleted digital object was of that single image (not the entire scrapbook page).  There is a problem with the image-based link, however, since as is it results in a dead-end link if it were to be utilized as a redirect, but if that issue could be addressed with a URI that could frame the image and provide a link back to the entire digital object, that would be great (and quite useful, for a variety of other reasons, if we want to consider the DCS as a research-based tool).

**Comment by DraxIndustries79** [comment]
Kait and Rob will pair.  If necessary, we'll schedule follow-up meeting time for the group to talk through options and create a decision document.

**Comment by K8Sewell** [comment]
# Spike Research
During investigation we were able to prove that it's possible to redirect a url for a parent that has been deleted to another page.  By soft deleting parents, storing a small solr document with the redirect link, and by updating a few batch processes.

# Video
https://images.zenhubusercontent.com/242185115/83d57e93-04ea-4fda-90e3-f4f44e854147/screen_recording_2021_11_16_at_01_56_29_pm.mp4

# Takeaways
- parents should soft delete
- new ticket for reusing soft deleted parent oids
- new ticket to show soft deleted items in parent oid table
- parents will have redirected_to field which can hold a single url
- redirected_to field will be indexed in solr
- blacklight will not show redirected_to parents in searches
- blacklight will redirect redirected_to parents on show page
- new ticket to support setting redirect_to during "Delete Parent Objects" and during "Reassociate Child Oids"
- add redirected_to field on parent show page, parent edit form, maybe on parent table

**Comment by DraxIndustries79** [comment]
@motropuk will get some buy-in before we move forward with implementation tickets.

**Comment by motropuk** [comment]
We can close this. Have written to Yale team and will report back if we can move forward with creating tickets for suggested option

**Comment by fordmadox** [comment]
This looks great to me! 

If I understand correctly, the new 'redirected_to' field will also be editable on the parent show page?

**Comment by mikeapp** [comment]
I'd like to hear more about the proposed soft-delete implementation.  If this is a flag on the existing Parent Object model then we're going to need logic to exclude them from some activities (e.g., I doubt we want to update their metadata).  Also, does this imply soft-deleting any remaining children as well?
