### ISSUE TITLE
Reindex from AdminSet page Does not Update All Parents

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1733]
In production, the BRBL/Voyager update from the BRBL admin set page has been run multiple times.

Only some of the Parents have been updated.  (See last voyager update column in Parent Objects table.)

- [ ] Batch Update Metadata from the admin set page updates all parent objects that match.

**Comment by jpengst** [comment]
After investigating on production, it looks like the objects that aren't getting updated are failing their delayed job runs for various reasons:  
1.) undefined method `all_images_present?' for nil:NilClass
2.) undefined method `mets_doc' for nil:NilClass
3.) PDF Java app returned non zero response code for 800052316: javax.imageio.IIOException: Unsupported Image Type
4.) Child Object 11679526 failed to convert PTIFF due to Conversion script exited with error code 1.  
  
We don't think there is an issue with the actual Update Metadata functionality. The above issues are probably what's causing the updates to not trigger/record.

**Comment by martinlovell** [comment]
We ran the same set of Parents through an Update Parents batch job last night, and they all succeeded and updated.
When we ran the Update from the Sets page multiple times a pretty big percentage didn't update.  (Checking the update time using the parent object table, showed that a bunch (>20) never updated.)
So, I'm still concerned that something might be going on with kicking it off from the Admin Sets page.

(This was with a Set/Authoritative source that had only ~450 matches.  So, it should all queue in the first UpdateAllMetadata job.  So, it doesn't seem like it's the job splitting that's causing the problem.)

We do have a test that's passing: https://github.com/yalelibrary/yul-dc-management/blob/main/spec/jobs/update_all_metadata_job_spec.rb#L55
(with a where and multiple jobs split.)

I did go through cloudwatch and found the logs for one of the Job runs, and did not see any errors or anything else unexpected.

I'll try running the update again in off hours to test it again, and to better document the issue and logs if there is a problem still.
