### ISSUE TITLE
Remove second "title" from search result display

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#179]
The second title immediately below the title link is redundant 

![image](https://user-images.githubusercontent.com/3064318/83543934-c7bec380-a4c2-11ea-9773-bd29045a4147.png)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/69

# Story
The "Title" label for each search result is redundant

# Expected Behavior
- The "Title" label and text on the search results page is gone
- The "Title" label and text on the individual result page is gone
- Users can still search according to the "Title" when you click the "All Fields" dropdown
- Tests for the "Title" field have been removed

# Demo
- search results page
![image](https://user-images.githubusercontent.com/29032869/83577034-087d0380-a4e8-11ea-9f28-363322a817d8.png)

- individual result page
![image](https://user-images.githubusercontent.com/29032869/83577266-a53fa100-a4e8-11ea-882d-fba373654d9c.png)
