### ISSUE TITLE
SPIKE: Investigate Parent Object deletion timeouts

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1890]
**Story**

Deleting a parent object can result in a timeout in the browser when the object has more than a relatively small number of children.  The deletion does succeed.

**Acceptance**
- [x] The parent object is deleted without the user experiencing a timeout error.

**Comment by martinlovell** [comment]
Both parent and child have destroy hooks to remove active jobs from the database.
Those queries can be very slow if there are a lot of jobs in the database since they need to use a "LIKE" query starting with "%".

**Comment by martinlovell** [comment]
It seems related to the destruction of child_objects:

I tried removing the Job deletion from Delayable.delayed_jobs_deletion, but it still took a while to destroy all the children.
I tried removing papertrail and Job deletion, but it still took a long time to destroy each child.

Changing `dependent: :destroy` to `dependent: :delete_all` for ParentObject has_many relationship with children: delete was reasonably fast.  This would mean no papertail or Job deletion when children are deleted, and no removal from solr for child objects.  Children could be deleted from SOLR with one delete by query using "parent_ssi."

It seems reasonable to delete the children rather than destroy, as long as they are explicitly removed from SOLR.  Parent object deletion could delete from solr using parent_ssi to take care of the children.  Not sure about the jobs being left around, but we can probably deal with that in the Jobs themselves. (Maybe the jobs need to handle getting a nil child passed to them.)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/928

**Comment by martinlovell** [comment]
Updated PR with comment

**Comment by FCRodriguez7** [comment]
Released management v2.58.25

**Comment by mikeapp** [comment]
Looks good, deleted the object with 40 items instantly.

**Comment by FCRodriguez7** [comment]
This bug occurred between 48 and 50.
