### ISSUE TITLE
Add a Resource Type facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#192]
**ACCEPTANCE**
- [ ] I can narrow my search by faceting on the Resource Type

**Comment by DraxIndustries79** [comment]
Should be pattern matching from other facet PR's

**Comment by alishaevn** [comment]
# MR
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/192

# Story
Add a Resource Type facet

# Expected Behavior
- User's can filter by Resource Type
- Included the Resource Type in the facet's spec

# Demo
![image](https://user-images.githubusercontent.com/29032869/83785062-9d494380-a645-11ea-9089-06eb96e9c119.png)

**Comment by FCRodriguez7** [comment]
I merged the PR.
