### ISSUE TITLE
Increase size of images in sitemap

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1928]
**Story**

Our sitemap files link to the thumbnail image and the size is `!200,200`.   We should update this to match the image size we going to use for OpenGraph.  See #1249.

**Acceptance**
- [x] Change sitemap XML image references to `!1200,630`

**Comment by FCRodriguez7** [comment]
Failed examples:

rspec ./spec/requests/annotation_request_spec.rb:60 # AnnotationsController Full Text GET /annotation/ .. /fulltext not logged in or on campus returns a full text annotation
rspec ./spec/requests/annotation_request_spec.rb:65 # AnnotationsController Full Text GET /annotation/ .. /fulltext not logged in or on campus returns 401 for a full text annotation on Yale Only parent
rspec ./spec/requests/annotation_request_spec.rb:69 # AnnotationsController Full Text GET /annotation/ .. /fulltext not logged in or on campus returns 401 for a full text annotation because of mismatch parent
rspec ./spec/requests/annotation_request_spec.rb:73 # AnnotationsController Full Text GET /annotation/ .. /fulltext not logged in or on campus returns 401 for a full text annotation unknown visibility
rspec ./spec/requests/annotation_request_spec.rb:83 # AnnotationsController Full Text GET /annotation/ .. /fulltext while on campus returns a full text annotation
rspec ./spec/requests/annotation_request_spec.rb:88 # AnnotationsController Full Text GET /annotation/ .. /fulltext while on campus returns a full text annotation on yale only
rspec ./spec/requests/annotation_request_spec.rb:93 # AnnotationsController Full Text GET /annotation/ .. /fulltext while on campus returns 401 for a full text annotation because of mismatch parent
rspec ./spec/requests/annotation_request_spec.rb:97 # AnnotationsController Full Text GET /annotation/ .. /fulltext while on campus returns 401 for a full text annotation unknown visibility
rspec ./spec/requests/annotation_request_spec.rb:107 # AnnotationsController Full Text GET /annotation/ .. /fulltext while logged in returns a full text annotation
rspec ./spec/requests/annotation_request_spec.rb:112 # AnnotationsController Full Text GET /annotation/ .. /fulltext while logged in returns a full text annotation on yale only
rspec ./spec/requests/annotation_request_spec.rb:117 # AnnotationsController Full Text GET /annotation/ .. /fulltext while logged in returns 401 for a full text annotation because of mismatch parent
rspec ./spec/requests/annotation_request_spec.rb:121 # AnnotationsController Full Text GET /annotation/ .. /fulltext while logged in returns 401 for a full text annotation unknown visibility
rspec ./spec/requests/iiif_search_request_spec.rb:40 # Iiif Search IIIF search matches document when case does match
rspec ./spec/requests/iiif_search_request_spec.rb:46 # Iiif Search IIIF search matches document when case does not match
rspec ./spec/requests/iiif_search_request_spec.rb:52 # Iiif Search IIIF search includes proper "on" property in resources
rspec ./spec/requests/iiif_search_request_spec.rb:62 # Iiif Search IIIF search suggestion when searching for word not capitalized in original text returns matches to suggest search when case does match
rspec ./spec/requests/iiif_search_request_spec.rb:70 # Iiif Search IIIF search suggestion when searching for word not capitalized in original text returns matches to suggest search when case does not match
rspec ./spec/system/access_restrictions_spec.rb:88 # access restrictions an unauthenticated user does allow iiif_suggest for public works
rspec ./spec/system/access_restrictions_spec.rb:156 # access restrictions an authenticated user does allow iiif_suggest for public works
rspec ./spec/system/access_restrictions_spec.rb:161 # access restrictions an authenticated user does allow iiif_suggest for yale-only works
rspec ./spec/system/access_restrictions_spec.rb:225 # access restrictions a user on the network does allow iiif_suggest for public works
rspec ./spec/system/access_restrictions_spec.rb:230 # access restrictions a user on the network does allow iiif_suggest for yale-only works
rspec ./spec/system/advanced_search_spec.rb:131 # Search the catalog using advanced search searching gets correct search results from oid_ssi
rspec ./spec/system/advanced_search_spec.rb:234 # Search the catalog using advanced search sorting can sort by title
rspec ./spec/system/date_slider_spec.rb:109 # Blacklight Range Limit is able to search with the slider
rspec ./spec/system/single_item_pagination_spec.rb:53 # Single Item Pagination in the first item does not have "Previous" and should have "Next"
rspec ./spec/system/single_item_pagination_spec.rb:73 # Single Item Pagination in the third item has "Previous", but not "Next"
rspec ./spec/system/sitemap_show_spec.rb:113 # Sitemap Show renders elements with a hash that leads with 1
rspec ./spec/system/sort_in_search_spec.rb:128 # Search results should be sorted sorts by title desc
rspec ./spec/system/sort_in_search_spec.rb:174 # Search results should be sorted sorts by year sorts by year asc

[Coveralls] Outside the CI environment, not sending data.
app@5b4a83d8354c:~/webapp$

**Comment by FCRodriguez7** [comment]
I completed the work to get the PR to pass in the management application.  We may still need to complete or look into the blacklight application.

**Comment by K8Sewell** [comment]
PR for blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/771

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/773

**Comment by FCRodriguez7** [comment]
v1.60.12
