### ISSUE TITLE
Add a Publication Place facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#193]
**ACCEPTANCE**
- [x] I can narrow my search results by faceting on Publication Place

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/79

PR ready for review.  Thanks!

**Comment by K8Sewell** [comment]
![Screen Shot 2020-06-08 at 9.31.37 AM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9e934af7-5b7e-4b27-8755-1419794a1f43)

Question for future improvement: Is the desired UX to see continents, then countries, then cities, nested in a hierarchy rather than sorted alphabetically?
