### ISSUE TITLE
JSS works not on full text list

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1951]
**Story**

About 2800 works were polled for full text by @mikeapp   There are about 3200 JSS works total.

OIDs that were provided full text:
[https://app.zenhub.com/files/242185115/3979c3d5-db7a-447b-b1a0-df297ddeb742/download](https://app.zenhub.com/files/242185115/3979c3d5-db7a-447b-b1a0-df297ddeb742/download)

**Acceptance**
- [x] Determine which OIDs do not have full text (will need to diff the list above with an export from DCS)
- [x] Review OneDrive lists of parents/children for list of JSS items.  Determine whether any of the missing OIDs might have children.  If so, provide list of parent OID, child OID, child PID so Mike can run further exports.

**Comment by MaggieZhaoYale** [comment]
380 oids do not have fulltext
[https://app.zenhub.com/files/242185115/e0cd24a4-db2f-4df8-a193-8dca9d08deb6/download](https://app.zenhub.com/files/242185115/e0cd24a4-db2f-4df8-a193-8dca9d08deb6/download)

**Comment by MaggieZhaoYale** [comment]
@mikeapp The missing 380 oids were migrated to DCS a few months after the most JSS items since they were problematic items. 
The list of these 380 parents is in the valkyrie POC server 
valkyrie-poc.library.yale.internal: /usr/local/bin/jss_tasks/lib/tasks/pid_oid_remain.zip  or the folder pid_oid_remain
parent OID is the name of the csv, each csv has "oid" which is the child OID, "pid" which is the child PID.
