### ISSUE TITLE
[SPIKE] Regenerate PDFs only when necessary

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1953]
**Story**

Many jobs run through the entire Parent Object workflow, including PDF generation, even when not required.   PDF generation is very expensive, so we should skip it whenever we can.

PDF generation is required when:
- Metadata displayed in the PDF is changed
- Child images are changed

Some possible approaches:
- Checksum the JSON file sent to the PDF generator.  This would require removing the signed URLs from the JSON, as the change every time.  It would also require the inclusion of more data about the children (perhaps last modified dates?) to detect image updates.  The checksum would need to be stored on the parent for subsequent checks.
- Have batch jobs set a flag on the parent.  For example, if the metadata updates impact the PDF fields, or a child image is reprocessed, or children reordered, etc.   The PDF job could be skipped if the flag is not set.

**Acceptance**
- [x] Describe approach for skipping PDF generation when it is unnecessary

**Comment by martinlovell** [comment]
- Updated method that generates PDF json to have an option to replace the signed URL with the child modification date.
- Store the MD5sum of that json in metadata in S3

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/958

**Comment by martinlovell** [comment]
This can be tested by:

- Updating a parent to update the PDF and store the checksum.
- Wait for the PDF to generate and view it, remembering the generation time on the cover page.
- Then update that same parent...wait for the jobs to be complete. (The PDF job should be very quick, since it just has to check the checksum on S3)
- View the PDF and it should have the same generation time on the cover page.
