### ISSUE TITLE
Add a link to Resource Type on the show page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#197]
**ACCEPTANCE**
- [ ] The Resource Type field links to other works with the same value

NOTE: See #194 for a detailed example

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/83

# Story
Added a Resource Type link

# Expected Behavior
- An individual work has a Resource Type label with a link
- Included the Resource Type link in the display spec

# Demo
![image](https://user-images.githubusercontent.com/29032869/83795512-6c243f80-a654-11ea-8351-be814b0054be.png)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/83
