### ISSUE TITLE
[Design needed] Add link to Advanced Search directly to DCS homepage

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1998]
**Story**

As an end user of DCS, I would like to be able to access Advanced Search (https://collections.library.yale.edu/advanced) directly from the DCS homepage (https://collections.library.yale.edu/)

**Acceptance**
- [ ] Design created to outline where the link to Advanced Search should display
- [ ] Link added to homepage or new ticket created

**Comment by motropuk** [comment]
Perhaps Tracy could work on the design here

**Comment by tmacmath** [comment]
This is what I'm thinking of for the design: ![Screen Shot 2022-04-06 at 4.21.57 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/1a6029ed-5df4-4a69-8a75-b867fa5937c7)

**Comment by motropuk** [comment]
I like your design here @tmacmath. The suggestion to have advanced search on the homepage came from a few curators and public services staff, notably George Miles.

**Comment by tmacmath** [comment]
This design is pretty simple- what I did was add a border around <div class="input-group"> and add a div underneath (inside <form>). 

For input-group:

border: 5px solid rgba(0, 0, 0, 0.5);

For the added div (which I just gave a class of "adv-search-link"):

border: 30px solid rgba(0, 0, 0, 0.5);

For the link:

color: #ffffff; 
font-size: 14px; 
font-weight: 500;
font-family: MalloryMP-Medium;
text-decoration: underline; (only because of the white font)

**Comment by AKFosterDev** [comment]
PR ready for review https://github.com/yalelibrary/yul-dc-blacklight/pull/781

![Screen Shot 2022-04-07 at 2.56.18 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/1212f7fa-9d5e-42b5-ad79-da4a09ccd6c9)

**Comment by mikeapp** [comment]
Released blacklight v1.60.17
