### ISSUE TITLE
[ASpace Linking] Make DCS Parent Private when object is deleted or unpublished

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2117]
See #2067 for ASpace digital object linking testing ticket 

**Story**
When a record is unpublished in ArchivesSpace, it does not make Private or delete the object in Blacklight/Management; the object is disconnected from the metadata record, but remains visible in Blacklight with the previous metadata. 

When a record is deleted in ArchivesSpace, we would like the corresponding parent in Management to have its visibility changed to Private. 

Example Parent 10014129 in UAT [Blacklight](https://collections-uat.library.yale.edu/catalog/10014129)
Example Parent 10014129 in [Test ("UAT") ArchivesSpace](https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/781638?_ga=2.14261687.127531703.1653595396-738509661.1643218753)
Example Parent 10014129 in [UAT Management](https://collections-uat.library.yale.edu/management/parent_objects/10014129) 

Clicking on Metadata Cloud link in MGMT returns a message that the ArchivesSpace record is unpublished. 

**Acceptance Criteria:**
- [ ] When a record is deleted or unpublished in ArchivesSpace the corresponding parent in Management to have its visibility changed to Private.

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1027

**Comment by K8Sewell** [comment]
Deploying to test with release v2.59.44 - https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.44

**Comment by K8Sewell** [comment]
Promoting to UAT for testing

**Comment by martinlovell** [comment]
This will mark an aspace parent object private if for any reason the aspace record is not found or is restricted.

Including:
- Automatic nightly updates of aspace records.
- If an existing record is changed to have aspace as the source.
- The aspace URI is updated.

Some scenarios to consider:
1)  A user points a Ladybird record to Aspace, but puts the aspace URI in incorrectly, the parent will become private since the Aspace object is not found and considered deleted.  (Similarly, if it's pointed at a restricted aspace record, it will become private).
2) A user changes the Aspace URI to a restricted URI or one that does not exist.
3)  A user updates a parent that is private by setting it to Public or YCO.  After the save it is Public or YCO, but after the parent's metadata is updated, it becomes private again because the aspace object is restricted or not found.

The updates for parents occur asynchronously on the workers, and the system doesn't know what caused the update to be triggered.

Currently, for (1) and (2) it would still be in blacklight with the old data while the issue was resolved in management, but now it will become private.

It does add a processing message, so it should be possible to track down what happened through the batch if the change was done with a spreadsheet.  If it was done using the parent object form, there wouldn't be feedback unless we were to validate the aspace URIs through metadata cloud when the parent object form is submitted.

**Comment by sshetenhelm** [comment]
**Unpublish ASpace Archival Object Record**
Test with OID [900146747](https://collections-uat.library.yale.edu/management/parent_objects/900146747) / [(Blacklight)](https://collections-uat.library.yale.edu/catalog/900146747)
- Unpublished [Archival Object ASpace record](https://testarchivesspace.library.yale.edu/resources/3830#tree::archival_object_1235339) in ASpace TEST (connected to DCS UAT) & confirmed record was no longer active in [public view](https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1235338)
- Clicked 'Update this item' in UAT DCS
- Visibility was not changed from public to private, and [error displayed in Delayed Job Dashboard](https://collections-uat.library.yale.edu/management/delayed_job_dashboard/show/10225503)
- Left ASpace record as unpublished; can return to published when we finish testing

**Unpublish ASpace Digital Object Record** 
Test with OID [10011002](https://collections-uat.library.yale.edu/management/parent_objects/10011002) / [(Blacklight)](https://collections-uat.library.yale.edu/catalog/10011002)
- Unpublished all sections of [ASpace Digital Object Record](https://testarchivesspace.library.yale.edu/digital_objects/177587#tree::digital_object_177587) & confirmed record was no longer active in [public view](https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1079663) (although record still has digital object icon next to page name) 
- Clicked 'Update this item' in UAT DCS
- Visibility was not changed from public to private, and no error displayed in Delayed Job Dashboard
- Left ASpace Digital Object record as unpublished; can return to published when we finish testing

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1030

**Comment by martinlovell** [comment]
v2.59.46

**Comment by martinlovell** [comment]
Another fix to force the solr index after it's marked private.
It also makes sure that only aspace items have this sync from the source.

https://github.com/yalelibrary/yul-dc-management/pull/1031

**Comment by sshetenhelm** [comment]
OID 10011002 still visible in Blacklight after metadata update.

Also tried from scratch with OID [10010463](https://collections-uat.library.yale.edu/management/parent_objects/10010463)
[ASpace record](https://testarchivesspace.library.yale.edu/resources/2822#tree::archival_object_939726 ) / [Blacklight](https://collections-uat.library.yale.edu/catalog/10010463) 

Same result -- object in MGMT was marked as private, but the objects are still visible in Blacklight via "public view" link from MGMT and as search result

**Comment by sshetenhelm** [comment]
**Unpublish ASpace Archival Object Record**
In TEST with OID 800050557 [MGMT](https://collections-test.library.yale.edu/management/parent_objects/800050557) / [Blacklight](https://collections-test.library.yale.edu/catalog/800050557) / [ASpace](https://testarchivesspace.library.yale.edu/resources/5206#tree::archival_object_2063389)
- Unpublished ASpace record & closed record editor
- Updated metadata in MGMT
- Visibility switched to Private
- No longer visible in Blacklight

**Test # 2** with OID 800052201 [MGMT](https://collections-test.library.yale.edu/management/parent_objects/800052201) / [Blacklight](https://collections-test.library.yale.edu/catalog/800052201) / [ASpace](https://testarchivesspace.library.yale.edu/resources/4876#tree::archival_object_2019478)

- Unpublished ASpace record & closed record editor
- Updated metadata in MGMT
- Visibility switched to Private
- No longer visible in Blacklight

Looks like it works!
