### ISSUE TITLE
[ASpace Linking] Changing to 'Yale Community Only' Breaks Image in ASpace

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2118]
See #2067 for ASpace digital object linking testing ticket

**Story**
An object in DCS was changed from Public to Yale Community Only. This unpublished the manifest URI in ASpace. Because of that, the image did not display in ASpace, although the link to the digital object and the link to DCS remained published.

When an object is change to Yale Community Only, we would like to continue to have the link to the object displayed, but with the Yale Community Only icon as the image.

**Comment by martinlovell** [comment]
Is this something that can be handled on the Archive Space side?
So, aspace would follow this logic: "If the image-thumbnail file_version is not published, use YCO image (hosted on archives space) for the link."

(This is how DCS blacklight does it.  Management doesn't replace the thumbnail for blacklight. Blacklight knows when to display the image based on the permissions and blacklight decides what the image looks like, size, etc. to match it's UI.)

**Comment by ucancallmealicia** [comment]
@martinlovell Yes I think that could work. So when a record in DCS is created/updated to be Yale Community Only, the sync from DCS/MC should create a new, published file version in the record's ArchivesSpace digital object record for the YCO image, and make it the representative thumbnail. We do something like this for Kissinger materials in Find-It which are restricted - see https://archives.yale.edu/repositories/12/archival_objects/2068803.

**Comment by martinlovell** [comment]
@ucancallmealicia , I was hoping the thumbnail logic could happen in AS Pui.  So, it would just use a default image when it saw that the thumbnail was not published.  But, we could set something up like you said, where it unpublishes the IIIF manifest, but just swaps out the image for the YCO.  This might be better so that DOs from different source get to choose the image, or completely unpublish if necessary.  (The only downside I can think of is that someone couldn't figure out the YCO thumbnail from the  unpublished data in aspace since it wouldn't have the unpublished thumbnail with the link in it.)

We'd have to find a good place to put the image, since the one used by blacklight gets a new name when it's changed because of Rails asset management.  (I noticed the findit image is in https://libweb.library.yale.edu/pui-assets/....maybe we could use something like that.....I think we have some fonts that are statically hosted for DCS.  Maybe we could put it there.)

**Comment by ucancallmealicia** [comment]
@martinlovell I don't think we could do it in the PUI without a plugin, unfortunately. So yes, I'd suggest 1. unpublish the manifest file version, 2. either unpublish or delete the DCS thumbnail file version, 3. create new published file version with YCO thumbnail and make it the display thumbnail. I think we'd want to keep the DCS catalog link file version published and representative, so that clicking on the YCO image would still take the user to DCS.

Steve Wieda helped us with the image hosting when we implemented the PUI, so he might be a good person to talk to if there isn't already something set up for DCS (though it sounds like there might be)

**Comment by martinlovell** [comment]
Make sense.  I created a ticket for BL to get started: #2125 
And I'll create one in MC to handle YCO properly by creating a thumbnail file_version pointing to the image once the BL work is done.

**Comment by martinlovell** [comment]
The work for this ticket will be in #2125 and Metadata Cloud, so giving it a 0.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/metadata-cloud/pull/424

**Comment by martinlovell** [comment]
Sample YCO item in UAT: 
https://puitestarchivesspace.library.yale.edu/repositories/6/archival_objects/2584910

**Comment by motropuk** [comment]
Looks good in A@Y Test
