### ISSUE TITLE
Add last preservica update

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2140]
# Summary
Parent Object show page does not have 'last preservica update' listed.  Design decision needed to chose whether to put with other updates or in preservica section on Parent Object show page.

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3cb142f1-2926-42d3-8815-b661ea20017c)

# Acceptance
- [ ] 'last preservica update' added to parent object show page

**Comment by tmacmath** [comment]
Brought this up in our DSU meeting today - solicited feedback from the group, as they are our "power users". It was suggested that the link should be placed on the child object single item view page, as opposed to the parent object page, because the item is in Preservica at the image level. The link, then, should probably go beneath the links outlined in yellow: 

![child-object-single-item-view.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/b65dd438-6df9-4276-9089-1e4d7b15db1e)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/1034

**Comment by K8Sewell** [comment]
Sorry could I also get a review on this revert PR for the dependabot changes that I think broke the test deploy last time - https://github.com/yalelibrary/yul-dc-management/pull/1035 - before I cut a new release for management?

**Comment by K8Sewell** [comment]
release - [v2.59.50](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.50)
