### ISSUE TITLE
Add APA and MLA citations

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#218]
**STORY**
As an undergraduate writing a paper, I would like the system to provide properly formatted citations, so that I'm less likely to make errors transcribing or formatting my citations.

**ACCEPTANCE**
When I click on the "Cite" link in the Tools box on a single item show view,
- [x] I get a pop-up window with the citations for the work
  - [x] In MLA (Modern Language Association) format
  - [x] in APA (American Phycological Association) format

**PRIOR ART**
Gem: https://rubygems.org/gems/citeproc-ruby
Code: https://github.com/emory-libraries/dlp-lux/pull/552
Example: https://digital.library.emory.edu/catalog/890rr4xh2h-cor/citation
Other examples are available if needed.

**Comment by edejesusyale** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/113

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/114

# STORY
As an undergraduate writing a paper, I would like the system to provide properly formatted citations, so that I'm less likely to make errors transcribing or formatting my citations.

# ACCEPTANCE
Go to any record's display/item page.
Click on the "Cite" link in the Tools box on a single item show view and verify:
- [ ] You get a pop-up window with the citations for the work
  - [ ] Citation in MLA (Modern Language Association) format
  - [ ] Citation in APA (American Phycological Association) format

# DEMO
![image](https://user-images.githubusercontent.com/29032869/84811183-55b9a480-afc1-11ea-91de-4e1944578e66.png)

**Comment by alishaevn** [comment]
Viewable at https://collections-test.curationexperts.com/catalog/16414889
`Branch: v1.4.0, Deployed: 2020-06-17T11:59:31-04:00`

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/27a8c344-41dd-4b41-85f6-840185ede4ab)
