### ISSUE TITLE
Update DCS homepage highlight images

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2324]
**Story**

We need to update the Highlights section on the DCS homepage to reflect collections from across the library. We will retain current formatting for the Highlights section but will change out most of the images and associated links.

**Acceptance**
- [x] Update the highlights to include the new collections and links, per this document: https://docs.google.com/document/d/1q7EqFheYSTkSyPPtCLDWH4ZYsQL_DIj3pzzqYKun8Gs/edit?usp=sharing

**Comment by jpengst** [comment]
Some of the images are in a Portrait layout and don't fit the landscape layout of the highlight blocks:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/5ab2d29b-3f01-4134-b896-42b56df5a3e7)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/853

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.52](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.52)

**Comment by K8Sewell** [comment]
Looks good on Test
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/cd53bae5-6d1a-4714-8cc3-43fa89f5ad9a)

**Comment by K8Sewell** [comment]
Fixing - The one that raised the question for me was the Divinity link, as I saw that it links to https://collections-test.library.yale.edu/catalog?q=%22China+Records+Project+Miscellaneous+Personal+Papers+Collection%22&search_field= rather than https://collections.library.yale.edu/catalog?fulltext_search=1&q=%22China+Records+Project+M[…]tor_ssim+asc%2C+title_ssim+asc%2C+archivalSort_ssi+asc. The piece that's missing from that first link is the sort by creator bit (we want to have it sorted by creator A-Z rather than just a general collection search because of some potentially distressing images that come up when the results are unsorted)

**Comment by K8Sewell** [comment]
PR for fixing link - https://github.com/yalelibrary/yul-dc-blacklight/pull/855

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.53](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.53)

**Comment by K8Sewell** [comment]
Updated link looks good on Test
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d9ee311c-3e6b-4b82-b7d5-41d8a29dc0db)

**Comment by mikeapp** [comment]
Garvin doesn't return result, at least on UAT.

**Comment by sshetenhelm** [comment]
Since Garvin was migrated and has a PID, we could use the following link:
https://collections.library.yale.edu/catalog?f%5Bproject_identifier_tesi%5D%5B%5D=65

And this should be used for Litchfield:
https://collections.library.yale.edu/catalog?f%5Bproject_identifier_tesi%5D%5B%5D=71

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.54](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.54)

**Comment by K8Sewell** [comment]
Looks good on Test, deployed to UAT
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3cd2f3f8-707f-410c-89db-21be3e751e2a)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Ready to close.
