### ISSUE TITLE
Dependabot fixes for Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2350]
**Acceptance**
- [ ] Apply dependabot fixes to Blacklight

**Comment by K8Sewell** [comment]
Bumps `globalid`, `minitest`, and `zeitwerk` - https://github.com/yalelibrary/yul-dc-blacklight/pull/863
Bumps `rack` - https://github.com/yalelibrary/yul-dc-blacklight/pull/862

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.56](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.56)

**Comment by K8Sewell** [comment]
Looks good on Test but prevented from deploying to UAT because of mismatch in ruby version it appears - see image below.  Assumption is to correct ruby mismatch with nokogiri on `camerata` repo.  Taking back to in progress to do so.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3338d7c4-5c72-4f38-a4d8-e81739617e03)

**Comment by bobrice** [comment]
@K8Sewell I've changed the ruby version to 2.6 in the Jenkins job.  Could you try redeploying now and let me know if that was the fix.  It's what we did a few weeks ago to fix a similar problem.

**Comment by sshetenhelm** [comment]
Looks good on UAT, nothing weird noticed.
