### ISSUE TITLE
Display user-friendly field names in the UI

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#238]
**ACCEPTANCE**
- [x] The field names displaying for the facets should be human-readable. E.g., in the search limit UI at the top of this screen shot it should say `Identifier Shelf Mark` not `Identifier Shelf Mark Ssim`.
- [x] Confirm this is true for all facet-like fields linked from the show page

![Screen Shot 2020-06-15 at 1.26.20 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/6fa59dcb-41b2-4f4c-b879-1f8f6a5685ac)

**Comment by alishaevn** [comment]
I'm not sure this is actually an issue. When a new facet is added to the code, there is a "label" option. This is what the user sees, so as long as it's set as a human readable word/phrase, that's how it will show when you facet off of that option.

e.g.: `config.add_index_field 'extentOfDigitization_ssim', label: 'Extent of Digitization'`

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/29f33805-266b-4e37-8762-314da4214518)

**Comment by alishaevn** [comment]
Locally I don't see a `Identifier Shelf Mark` or `Identifier Shelf Mark Ssim` facet, so I'm not sure where the image in the description came from.

**Comment by mikeapp** [comment]
If you view an individual record you'll see the field - it is a link that triggers a search like this:

https://collections-test.curationexperts.com/?f%5BidentifierShelfMark_ssim%5D%5B%5D=Landberg+MSS+75

<img width="454" alt="Screen Shot 2020-06-17 at 2 22 57 PM" src="https://user-images.githubusercontent.com/1987952/84935027-25980180-b0a6-11ea-9864-e54bfb5966a7.png">

**Comment by alishaevn** [comment]
Thanks for the clarification!

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/134

# Story
Sometimes when you click the link on an individual show page it shows a human readable string and sometimes it shows the solr field label

# Research
Some of the values on an individual show page are created as links by using the `link_to_facet` field. When this link is clicked it does a search based off of that value. If the value is not listed as a facet, then you'll see the solr field label as the search result

# Expected Behavior
- All filtered fields, whether it's a facet from the main search page or a link from the individual show page, have the ability to be shown as a human readable string
- As we convert more values into searchable fields, a corresponding facet will need to be created with a `show: false` value

# Demo
![238](https://user-images.githubusercontent.com/29032869/85077511-55630a00-b177-11ea-9f84-217f37945cd8.gif)
