### ISSUE TITLE
Failed Job - GeneratePdfJob (2 of 3)

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2411]
# Summary
On Admin Set show page the Update IIIF Manifests button was clicked and triggered a large number of jobs.  Some failed.  This ticket aims to address the cause of the failure.

stack trace: No authoritative_json to create PDF for 2043793
sample failed job: https://collections-demo.library.yale.edu/management/delayed_job/failed?start=40#6739341

# Acceptance
- [ ] job no longer fails for error above

**Comment by sshetenhelm** [comment]
This happens when there is wrong information in the metadata fields -- in the cases I explored, there were problems with the bib and/or holding numbers that were fixed once the correct information was entered.

User error, not a system error. Moving to Review on UAT just so I can bring it up, we can close this.
