### ISSUE TITLE
Search Results Facets sidebar shortened

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2474]
When performing certain searches in DCS UAT using the 'Advanced Search' feature, some searches result in a shortened 'facets' left sidebar. Example:

![Image](https://user-images.githubusercontent.com/98423494/234031306-bcf36463-dd49-4f00-9d7b-681a976e1843.png)

The bug appears to be inconsistent. I have not been able to successfully replicate on DCS PROD because I have only found examples with Kissinger MS 2004, which has not been migrated to PROD yet.

**DOES HAPPEN:**

- Advanced Search - Call Number = MS 2004
- Advanced Search - Creator = Kissinger

**DOES NOT HAPPEN**

- Basic search, home page and top bar results list = “MS 2004”
- Basic search, home page and top bar results list = Kissinger
- Advanced search - Title = Kissinger
- Advanced search - Call number = RU 690 (Note - this call number has no full text info)
- Advanced search - Call Number = JWJ MSS 49 (Note - this call number DOES have full text info)
- Advanced search - Call Number = MS

The facets left side bar should remain the same size regardless of search performed or results.

**Acceptance**

- [ ] The facets left side bar remains the same size regardless of search performed or results.

**Comment by K8Sewell** [comment]
Cause: when certain terms like Kissinger are searched for the application inserts an <em> tag around the <section> for the sidebar.  Italicizing and scrunching the font causing the screenshot above.  Cause of inserting the em tag is unknown.

**Comment by martinlovell** [comment]
There are `<em>`'s in some titles.  E.g. 12480937 has `<em></em>` in the title.

See MC:  https://metadata-api.library.yale.edu/metadatacloud/api/ladybird/oid/12480937?mediaType=json&include-children=1
See Search: https://collections-uat.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=12480937
Show Page: https://collections-uat.library.yale.edu/catalog/12480937

Probably because of field highlighting, the title field is truncated in search results.  So, the closing tag is removed and the `<em>` started in the title is not closed, which causes problems with the facets.

All titles in search results are being truncated, whether or not they have an `<em>`: e.g. https://collections-uat.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=12482083 shows a truncated title in the results.

The only fields that we expect to have html are: description and rights, which aren't index fields or highlighted.

We could:
- [ ] Metadata cloud does strip tags for some archives space fields, including title.
We could add a similar option to ladybird fields and configure title (and maybe others) to strip tags.
- [ ] Remove the tags when indexing in management.
- [ ] Add two fields to solr, one with tags stripped for highlighting, one with tags for displaying the whole field.

**Comment by sshetenhelm** [comment]
If we strip the <em> from Ladybird, will it also remove the <em> from the object show page? (ex. Title in the one Martin linked). 

If so, and it's doable, let's do that. Everything needs to be reassociated anyway (and I know MS 2004 can be reassociated with Aspace).

**Comment by martinlovell** [comment]
@sshetenhelm , 
- It will remove the tags from all the title displays.  (Do you want the `<em>` on the show page? I think we can do that with 2 solr fields.)
- Should we strip tags from any other fields from ladybird other than title?  
- Verifying that we will strip all html tags, not just `<em>` to be safe, since the highlighting might cause issues with other tags. 
- Should we make the change on the metadata cloud side or during ingest into DCS?  (DCS is the only client that uses ladybird data from metadata cloud.)

**Comment by sshetenhelm** [comment]
1. Don't need it on the show page, I just want to make sure the text of em is not showing up--that the whole thing is gone. 
2. Let's add Rights and Description as well. 
3. Yes, strip all. 
4. The method you prefer is fine with me. Whatever is easier.

**Comment by martinlovell** [comment]
PR for metadata cloud:
Adds `stripTags` option for ladybird mappings.
Sets `stripTags` to true for `title` and `description`.

https://github.com/yalelibrary/metadata-cloud/pull/457

**Comment by MaggieZhaoYale** [comment]
merged the PR https://github.com/yalelibrary/metadata-cloud/pull/457

**Comment by sshetenhelm** [comment]
Looks good on UAT after resyncing metadata for MSSA set. Ready to close and THANK YOU!
