### ISSUE TITLE
Identify potential DCS/MARC/ASpace desired mapping discrepancies

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2491]
**Story**
As a staff user, I would like to know that fields identified in DCS as desired for index, display, search, and sort have been successfully implemented. 

**Acceptance**
- [ ] We identify important discrepancies between the working copy of the spreadsheet created by the metadata planning group (https://docs.google.com/spreadsheets/d/1OARV03IC1Y7m5B3fBYqNKSCXjsor4QvWJytM2ftr_ms/edit?usp=sharing), the Metadata Cloud API Debugger (https://metadata-api-test.library.yale.edu/metadatacloud/public/index.html), and DCS.
- [ ] We understand the source of those discrepancies.
- [ ] We address any high and medium priority discrepancies.

**Background**
We may need to look at this git repo for more up to date information: https://git.yale.edu/Library-IT/Metadata_Field_Mappings. Martin notes that when developing metadata cloud, we had talked about setting up JSON or some other way for metadata cloud to provide information to consumers on preferred labels and whether a field was for display or indexing or both. Martin doesn't think that was completed, so those decisions are made by consumers like DCS, but it may not be fully documented.

**Comment by martinlovell** [comment]
I forgot to mention that the active mappings are available here: https://github.com/yalelibrary/metadata-cloud/tree/test/src/main/resources. (See the various *map-<version>.json).

If you need access to that repo, let me know.

They may have drifted from https://git.yale.edu/Library-IT/Metadata_Field_Mappings.  

There are several pending PRs in  https://git.yale.edu/Library-IT/Metadata_Field_Mappings that may bring it closer to the active mappings. LIT typically didn't approve PRs in https://git.yale.edu/Library-IT/Metadata_Field_Mappings so that metadata experts could verify them.

**Comment by sshetenhelm** [comment]
@martinlovell I do not have access to that repo, could you please add me?

**Comment by DraxIndustries79** [comment]
Summer will point this when we move forward.

**Comment by sshetenhelm** [comment]
Created #2519 and #2520 in response
