### ISSUE TITLE
Improve CI cycle times

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#250]
In order to improve velocity of overall development, we want fast cycle times on our CI process. 

- [ ] Refactor our docker build as used by our CI process to cache gem installation. 
- [ ] This needs refactoring in both the Discovery (blacklight) application and the Management application

**Comment by orangewolf** [comment]
Story so far
Something isn't right when pulling and then. building an image. For example locally when I pull and then build, I would expect that most of the layers are then cached. This doesn't happen on Circle. I've tried changing the order of things, when to a single step, switched to machine executor, did a lot of ssh debugging, no avail. When I build and then build again I do get the cached version, so I do not understand why this approach doesn't work.

I do see that when I build inside SSH a second time (or build in the pipeline twice) the second one does use the cached layers and therefor skips the bundle, which is even more confusing.  I'm currently trying to do a build that is cached using circleci file caching, and then do a second build which will be the "real" build. I haven't had a ton of success there yet. We may have to move back to a more "in docker" based cache of the bundle (aka a base layer).  This should have been simple, but something is really odd with the way docker caching works in Circle and I am suspicious it has to do with trying to upsell the paid plan :-/

**Comment by orangewolf** [comment]
After uploading my notes from yesterday and today I had a "what if I just don't know anything" moment and went back and relearned Docker layer caching and building. It turns out it has changed significantly over the last couple years and that one key difference (caching in docker-compose is not the same as it is in regular docker) is something I didn't know. The `--cache-from`  flag is the secret sauce here and adding that means that if the bundled gems in master match that in the branch, docker builds are 1m again.
