### ISSUE TITLE
BUG: Full text status in Solr record is wrong

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2517]
**Story**
Some parents that have a status of 'Full Text Available -- Yes' have a listing in their Solr record of "has_fulltext_ssi": "No”. 

Examples:
[Parent 12479792](https://collections.library.yale.edu/management/parent_objects/12479792)

**Acceptance**

- [ ] Parents with text files attached have correct status in Solr

**Comment by mikeapp** [comment]
Noting that for the object above, the last successful index was in June (`"timestamp":"2023-06-07T00:05:39.444Z"`);  subsequent attempts have failed due to the Solr indexing error.

**Comment by martinlovell** [comment]
This is related to the "suggest" problem in SOLR.  We should be able to index it after we adjust the solr config.

Also, the "solr document" in the management app that displays on the parent object page doesn't include full text, so that view will always say "No". This was intentional, so that displaying the parent object page didn't require downloading all the full text etc.  Now that the extent_of_digitization is set in the DB, we could populate that field in this view.  

However, it's still possible that the solr document displayed on the parent object page does not match what is in SOLR if indexing failed or has not happened yet.  To see the actual value in SOLR, click the solr document link at the bottom of the page.

**Comment by martinlovell** [comment]
PR to populate solr document field with value in DB when displaying the solr document on the parent show page. (it's set in to_solr.)
https://github.com/yalelibrary/yul-dc-management/pull/1236

**Comment by jpengst** [comment]
Deployed to Test v2.62.5

**Comment by mikeapp** [comment]
Looks good on test

**Comment by mikeapp** [comment]
Looks good on UAT
