### ISSUE TITLE
Document all current metadata fields that display for an object in Blacklight single object page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2520]
In Response to #2491 

**Story**
Non-“technical” users of DCS would like to know exactly which metadata fields display in Blacklight when there is information available in those fields. We need to

* identify the fields that display and
* create documentation that is human-readable

From my understanding, this information is located in the catalog_controller.rb file in the yul-dc-blacklight GitHub repo.

**Acceptance**

- [x] Fields displayed are successfully identified 
- [x] Fields indexed for search are successfully identified
- [x] Search field suffixes are confirmed by engineering colleagues
- [x] Document listing and describing fields in human-readable way is created and added to DCS documentation in google drive

**Comment by alisonclemens** [comment]
Should we also confirm which fields are indexed for search?

**Comment by sshetenhelm** [comment]
Added criteria as per above comment. Summer will point when complete.

**Comment by martinlovell** [comment]
This is a wiki page in Git with some information: https://github.com/yalelibrary/yul-dc-documentation/wiki/Field-Names

**Comment by sshetenhelm** [comment]
Thank you for the link @martinlovell, that's super helpful!

**Comment by sshetenhelm** [comment]
Could some engineering folks please confirm the following?:

- _ssi = String is part of SOLR document, able to be searched, and able to be sorted
- 
- _ssim = String is part of SOLR document; will be searched, and is “multi-valued” 
- 
- _tesim = English text is part of SOLR document, able to be searched, and is “multi-valued” 
- 
- _tsim = Text is part of SOLR document, able to be searched, and is “multi-valued” 

What does “multi-valued” mean? Is that where the search may return similar values (ex. Searching for “cat” also returns “Cats”)?

**Comment by martinlovell** [comment]
Multi-valued means there can be more than on value put into that field.  So, if there are 2 call numbers, they get added as separate values in the same field.  (It's an array of values for one field.)

The "te" prefix is what enables the English stemming for plurals, etc.

The "String" values are not really searchable as free form text, they are useful for facets or stored values.  So anything starting with "s" instead of "t" in the suffix is generally a facet or some value we use but don't search as free form text (like "thumbnail_path_ss").

**Comment by sshetenhelm** [comment]
THANK YOU MARTIN!

**Comment by sshetenhelm** [comment]
Doc moved to drive; ready to close.
