### ISSUE TITLE
Compare 'More Information' pane to DCS parent metadata

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2544]
**Story**
Discrepancies have been discovered between the 'More Information' pane of the Universal Viewer and the metadata displayed below an object on the parent object display page in DCS. For example, objects associated with ArchivesSpace do not display the Creator in the 'More Information' pane of the Universal Viewer. We should compare the metadata on the page vs. the metadata in the UV for objects from all three data sources, note any discrepancies, identify what should be fixed, and make tickets to implement those fixes.

**Acceptance**
- [x] Compare and document aspace object page vs UV metadata fields
- [x] Compare and document ils object page vs UV metadata fields
- [x] Compare and document ladybird page vs UV metadata fields
- [x] Identify discrepancies 
- [x] Identify discrepancies that need to be addressed
- [x] Create tickets for future work

**Comment by sshetenhelm** [comment]
**ILS**

Missing fields between parent page and UV — 

* ‘Found In’ breadcrumbs are on parent object page, but not UV.
* Repository is on parent object page, but not UV. 
* Collection/Other Creator is on parent object page, but not UV.
* Related Resource Online is on parent object page, but not UV.
* Subjects list is on parent object page, but not UV.
* Rights is on parent object page, but not UV.

Difference in field order or label — 

* Extent of Digitization appears after Extent on parent page but after Call Number in UV.
* Published/Created on parent page, but Published/Created Date in UV

**ASPACE:**

Missing fields between parent page and UV — 

* Creator is on the parent object page, but not UV. (Worked on in #2547)
* Repository is on parent object page, but not UV (although repo info is included in Collection Note, which replicates Found In)

Difference in field order or label —

* Published/Created on parent page, but Published/Created Date in UV
* ‘Found In’ information is included in UV as ‘Collection Note’
* Extent of Digitization appears after Description on parent page but after Call Number in UV.
* Archives at Yale Item appears under Container/Volume on parent page, but under Finding Aid in UV
* Finding Aid appears under Archives at Yale item on parent page, but under Extent of Digitization (and above Archives at Yale item) in UV

**LADYBIRD:**

Missing fields between parent page and UV — 

* ‘Found In’ breadcrumbs are on parent object page, but not UV.
* Repository is on parent object page, but not UV.
* Collection/Other Creator is on parent page, but not UV.

Difference in field order or label —

* Extent of Digitization is under Extent on parent page but after Container/Volume in UV

@alisonclemens in terms of harmonizing the Parent Object Display Page in Blacklight and the Universal Viewer, how do you feel about the above discrepancies? Any high priorities or things we should not worry about?

@motropuk and @alisonclemens Should we tweak Ladybird fields if they might be 'quick fixes' or nah? Thoughts appreciated.

**Comment by alisonclemens** [comment]
Here are my notes, in **bold**

ILS:

Missing fields between parent page and UV —

‘Found In’ breadcrumbs are on parent object page, but not UV. **I think this is fine**
Repository is on parent object page, but not UV. **Better to have it included in UV, if possible, I think -- otherwise, information like call number (which is included in UV) is fairly meaningless**
Collection/Other Creator is on parent object page, but not UV. **Not sure what data field this is?**
Related Resource Online is on parent object page, but not UV. **Not sure what data field this is?**
Subjects list is on parent object page, but not UV. **I think that's fine (preferable, even)**
Rights is on parent object page, but not UV. **I'm ambivalent on whether or not this should be included in UV**
Difference in field order or label —

Extent of Digitization appears after Extent on parent page but after Call Number in UV. **For this and other field order/label questions, would it be alright to look at desired field order and labels for UV separately?**
Published/Created on parent page, but Published/Created Date in UV

ASPACE:

Missing fields between parent page and UV —

Creator is on the parent object page, but not UV. (Worked on in https://github.com/yalelibrary/YUL-DC/issues/2547) 
Repository is on parent object page, but not UV (although repo info is included in Collection Note, which replicates Found In) **I think it's fine to have it just in the Collection Note breadcrumb**
Difference in field order or label —

Published/Created on parent page, but Published/Created Date in UV
‘Found In’ information is included in UV as ‘Collection Note’
Extent of Digitization appears after Description on parent page but after Call Number in UV.
Archives at Yale Item appears under Container/Volume on parent page, but under Finding Aid in UV
Finding Aid appears under Archives at Yale item on parent page, but under Extent of Digitization (and above Archives at Yale item) in UV

LADYBIRD:

Missing fields between parent page and UV —

‘Found In’ breadcrumbs are on parent object page, but not UV. **I think that's fine**
Repository is on parent object page, but not UV. **If it's easy to fix, we might want to, but if it'll take any significant amount of time, perhaps we can just not worry about this**
Collection/Other Creator is on parent page, but not UV. **Not sure what data field this is?**
Difference in field order or label —

Extent of Digitization is under Extent on parent page but after Container/Volume in UV

**Comment by sshetenhelm** [comment]
Created #2558 for Repository work

[Example of object with Collection/Other Creator ](https://collections.library.yale.edu/catalog/17355881)
[Example of object with Related Resource Online](https://collections.library.yale.edu/catalog/2001862) (looks like link to RRO might be broken though?)

If the above two fields are not deemed necessary for More Information pane, we can close this ticket.

**Comment by alisonclemens** [comment]
@sshetenhelm Let's discuss this when you're back. My first instinct is that I think we could leave Collection/Other Creator off of the More Information pane, but that RRO might be helpful to include. But maybe we should plan to include both -- let's discuss

**Comment by DraxIndustries79** [comment]
Waiting for Summer to return

**Comment by sshetenhelm** [comment]
@alisonclemens I'm happy to leave Collection/Other Creator off unless there is a strong use case for adding that information that a stakeholder brings to us. Agree that RRO would be helpful. Will create ticket for that work, then we can close this ticket. We can look at this pane again during our stakeholder investigation sessions this fall.

**Comment by sshetenhelm** [comment]
Created #2571 for RRO work.
