### ISSUE TITLE
Confirm Voyager linking specs

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2573]
It is likely we will move forward with a single-record linking approach for the Voyager/DCS integration.

Martin and Maggie will need to meet with Yukari to scope out what is needed to turn the document from MetaDigets into actionable work.

**Acceptance**

- [x] We receive clean copy of linking approach from MetaDigets
- [x] Martin and Maggie meet with Yukari to scope
- [ ] Tickets for future work are created

**Comment by martinlovell** [comment]
Some examples from UAT:
https://collections-uat.library.yale.edu/catalog/16166158
https://metadata-api-uat.library.yale.edu/metadatacloud/api/digital_object_updates/57712/notes (Changed permission)
https://metadata-api-uat.library.yale.edu/metadatacloud/api/digital_object_updates/57715/notes (Changed barcode, same holding)


https://collections-uat.library.yale.edu/catalog/900148369
https://metadata-api-uat.library.yale.edu/metadatacloud/api/digital_object_updates/57717/notes (changed barcode, different holding)


https://collections-uat.library.yale.edu/catalog/11137289
https://metadata-api-uat.library.yale.edu/metadatacloud/api/digital_object_updates/57720/notes (change from ILS source to Aspace)
https://metadata-api-uat.library.yale.edu/metadatacloud/api/digital_object_updates/57724/notes (back to ILS)

**Comment by alisonclemens** [comment]
Have we discussed what we'll do in cases where there are multiple mfhds for the same collection? Here's an example: https://hdl.handle.net/10079/bibid/4505071

**Comment by DraxIndustries79** [comment]
Check in about creating future tickets.

**Comment by martinlovell** [comment]
Reviewers feedback:

1) I changed source for OID 17340024 from Ladybird to ILS. Bib 15765036, holdings 15736215. The holdings in test Voyager should have the updated 856s.
https://metadata-api-uat.library.yale.edu/metadatacloud/api/ils-linking-notes/17340024
 
2) I changed source for OID 17338201 from ILS to ArchivesSpace. I don’t work with ArchivesSpace, so am confused by not having the equivalent of a BibID to add. The notes initially read “no data available for this OID”. I changed it back to ILS, and the links updated.

3) Second try. Changed source for OID 900053855 from ILS to Archivesspace. I did not remove Bib 9082110, holding 9462821, item 8895183 in DCS. Notes say “null”. Check that the 856 links are removed in the MARC record.

4) Changed OID 17338219 (has ILS as source) from Public to Private. Matching 856 links should have been removed from MARC record (Bib 15976081). Nothing was recorded in notes.

5) Created OID 900963072. Data source: ILS Bib 5541436, holding 5541436. Check that links have been added to holding.


Notes based on the review:

#1 (OID 17340024) This looks good.  The notes look correct.  (Test Voyager didn’t change since we are not actually writing the data back yet.  If the notes look good, then it’s good.)

#2 (OID 17338201) It didn’t fully process the change because the ArchivesSpace URI wasn’t set. 
It’s not obvious on the edit page, but there is a spot for the ArchivesSpace URI next to the barcode.  I think it will remove the links once that’s set to a valid Aspace archival object.
This is expected, because it doesn’t try to update the Marc record until it is able to successfully update the metadata.
(See: https://collections-uat.library.yale.edu/management/parent_objects/17338201/edit )

#3 (OID 900053855) Similar to #2.  It needs a valid archival object URI for Aspace
(See:  https://collections-uat.library.yale.edu/management/parent_objects/900053855/edit )

#4 (OID 15976081) This is a bug in our system.  We will work on it. It should have removed the links as you expected.

#5 (OID 900963072) The parent doesn’t have any children, so it didn’t create a page in DCS. The system doesn’t update the marc until it is visible with children. I’m not sure of the best way to add at least one child.

**Comment by martinlovell** [comment]
New Issue: #2619
