### ISSUE TITLE
Blacklight OwP - user's request list

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2594]
**Story**

Design is required for the user's management of their requests in Blacklight.   Is this part of the `/bookmarks` page, or a new page?  How does the user navigate to it?   What does the list of new/approved/expired requests look like?

**Acceptance**
- [x] One or more page designs

**Comment by tmacmath** [comment]
What kind of requests are we talking about, just to clarify? Requests for digitized copies, other copies, etc.?

**Comment by sshetenhelm** [comment]
Requests for access to 'Open with Permissions' materials. 

They can pull files directly from DCS, there's no need to request that. 

For objects with aspace or orbis info, users can click through to descriptive records to request physical access. We might want to make that more clear in the future, but I don't want that to hold up this work.

**Comment by tmacmath** [comment]
@sshetenhelm Are we creating a separate Requests page for this (say, like the page with table in Orbis that shows which materials a patron has borrowed)?

**Comment by sshetenhelm** [comment]
As per Slack, we decided a separate request page would be good. I didn't see anything in the specs that would indicate we would need to think otherwise. I liked the table drawing you did. What specific info did you need -- exact fields for the table from the specs? 

We will need to update the Bookmarks list UI to indicate what has been requested and to link to list, but that will be in another ticket. We could have a link back to the bookmarks page from this request list page, and that could just be a button or something that sits at the top of the table.

Please let me know what else you need from me to move forward with this.

**Comment by tmacmath** [comment]
Hi-res mockup is complete; just putting together design specs.

**Comment by tmacmath** [comment]
Design Specs: 

A. Digital Access Requests header: 35px; #043669; YaleDisplay-Roman; border-bottom: none;

Table should be similar to the table in the Management App. 
	B. Table font: Mallory Medium, 16pt (default link color)
	C. Links: object title should link to the object in the DL; regular link color
        D. Table zebra striping: #ffffff;  alternating with #f2f2f2; (same as the table in the management app)
        E. Table border: 1px solid #dee2e6;
        F. Table header/field labels: font-size: 18px; font-family: Mallory-Medium; font-color: #043669;
        G. For table values that are not links: font-family: Mallory-Medium (400); font-size: 14px; font-color: #222529;
        H. For the sort icon, use Font Awesome or Bootstrap Glyphicons - I will provide a link to it, and if those don’t work well, I’ll find              something else. 


![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/642e2025-5971-49d6-a249-2741aabe4871)

**Comment by tmacmath** [comment]
I am currently researching better tools for delivering design specs. XD is not optimal, and others require paid subscriptions.

**Comment by sshetenhelm** [comment]
Thank you! Created #2724 for engineering work.

Ready to close :)
