### ISSUE TITLE
Adjust Sierra Call Number Mapping

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2610]
**Story**
The Call Number field for Law records mapping needs to be adjusted. Law states that the 099 field is removed in the digital record, and the call number is moved to 533 |n. They would like the Sierra mapping updated to reflect the 533 |n call number.

Original Sierra API work in #2595 

**Acceptance**

- [x] Sierra records pull Call Number from 533 |n

**Comment by martinlovell** [comment]
I added Sierra mappings to the debug client so that the callnumber mapping can be viewed: https://metadata-api-uat.library.yale.edu/metadatacloud/public/index.html

(I'm not sure of a bib id that has the callnumber in 533n.)

**Comment by sshetenhelm** [comment]
Will request record for example and confirm with Law before closing.

**Comment by sshetenhelm** [comment]
As per Law:

" In regards to the call number, I noticed the mapping seems to include 050 and 099. That would be great **if we can use both 050 and 533|n**, because we were debating which field to use. 533 will have the call number of the original resource, which for law tends to be a hicks call number, vs the lc call number in 050. However, please let me know if this is problematic in terms of executing a call number search in the url."

Example of e-variant with both 050 and 533 |n - b17203089

**Comment by martinlovell** [comment]
I'm not able to find a bib with ID 17203089 in Sierra, but found some issues with having two call numbers:

We currently only allow 1 CallNumber per record in Metadata Cloud. (It's a String property instead of a List of Strings.)

We can add 533n to the list or fields that we extract from, but if there were values in both 533n and 050, then it would combine them with a space separator into one value. I don't think that would work well.

DCS is configured so that it could store multiple callnumbers separately.  I'm not sure how that would affect display, but it should work well with search. So, DCS may not need updating to handle multiple call numbers.

There are some fields available in the Metadata Cloud records (all are String types):
localRecordNumber (This one is already indexed in DCS management, and searched for in Blacklight, but it is not displayed)
identifierShelfMark
callNumberWithPublicNote
(I'm not sure if any of these would be appropriate for 533.)

It is possible to adjust Metadata cloud to use a List of String to allow for multiple call numbers. That  would require some work and careful testing to make sure it doesn't affect any consumers or the DCS display.

**Comment by sshetenhelm** [comment]
Emailed Law on 2023.09.21 to see if any of the three identified MC fields might be appropriate for their needs. Also indicated that MC could be updated but it emphasized it would require significant testing/time resources.

**Comment by sshetenhelm** [comment]
As per Law, we can

- include the 533 |n in either localRecordNumber or callNumberWithPublicNote and 
- Keep the 050 in the original call number field

@martinlovell from a functionality perspective, is there any difference between localRecordNumber or callNumberWithPublicNote? Caitlyn says she thinks she's seen some 533 |n include notes with the call number so she's wondering if that would be better.

**Comment by sshetenhelm** [comment]
CallNumberWithPublicNote is mapped to the same fields as CallNumber for Voyager records (but adds a subfield z). 

Will including CallNumberWithPublicNote for Sierra objects on Blacklight cause anything strange to happen for Voyager records? For instance, causing the same info to appear twice in Blacklight for Voyager objects? Or is that… not a real problem? 

If we can, CallNumberWithPublicNote would probably be best to use for this purpose, as localRecordNumber is mapped to some things in Ladybird and Aspace and seem to have a different use case.

**Comment by martinlovell** [comment]
Yes, it would cause Voyager to show it twice with the $z added. But if $z wasn't populated, it would just be a duplicate.

We could map CallNumberWithPublicNote only if it was different than CallNumber in DCS for ILS and Sierra (so, only map it for ILS if $z added something), or we could not map CallNumberWithPublicNote for any ILS records in DCS.  

Even though we aren't using CallNumberWithPublicNote for ILS anywhere now, we should continue to map it in MC since those were the specifications we were given.
