### ISSUE TITLE
Fix Sorting from Preservica

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2621]
# Summary
The Preservica API doesn't sort as expected so to properly order the child objects we will need to update the logic that sets the order of the child objects when imported from Preservica.

As per David, "so it looks like the API returns as lexiographic sorting, which is alphabetic sorting of the numbers instead of numerically"

# Screenshot of Current Behavior

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/c87fd558-ffd5-46f1-93ab-59cd0e2cebb5)

# Acceptance Criteria
- [ ] Child objects imported from Preservica are sorted numerically

**Comment by motropuk** [comment]
@K8Sewell Leading zeros at the end of the filenames fixed the sort order in UAT https://collections-uat.library.yale.edu/management/parent_objects/900963073. I will update the filenames for the problematic object we have been working on in Prod and make sure that fixes the issue there too https://collections.library.yale.edu/management/parent_objects/10022080

**Comment by motropuk** [comment]
@K8Sewell Update from DPS 

"Sorry for not identifying that the API and UI would sort the items differently during the planning stages. I have done a some testing to confirm that changing the titles of IOs will change the sort order in the same manner as re-ingesting. This should allow for the correct order being presented by the API and not require re-ingesting.

A few caveats of this approach: 1) the title of the Asset(IO) and the name of the file held within that IO will not be same. This isn't an issue on the Preservica end, but if DCS depends on the IO name and file names matching, this approach won't work.

Following the above, the file delivered to DCS will have the original name, without the zero padding. While the IO title will have zero-padded version. I would also remove the .tif from the IO titles, since they'll no longer be matching the file names, unless this is something DSC expects. The result would be:

title="mssa_ru_0529_ACCN_1991_A_057_b1_f13_Correspondence to the Memorial Committee 1909-1917_010" holding the bit stream named "mssa_ru_0529_ACCN_1991_A_057_b1_f13_Correspondence to the Memorial Committee 1909-1917_10.tif"

I have asked DPS to go ahead and update the IO titles in Preservica Prod for https://collections.library.yale.edu/management/parent_objects/10022080 and will then resync with DCS to see if that works

**Comment by motropuk** [comment]
@K8Sewell the above fix from DPS worked in Production! Our problem object is now sorted corrected after a resync with Preservica https://collections.library.yale.edu/management/parent_objects/10022080

So I think we have a fix in place. Beyond documentating the above, maybe here @sshetenhelm https://docs.google.com/document/d/1_Hx8YQYO56EK_1-rQnBTSKQ5m_khhjY4ACMKeXW8oeU/edit#heading=h.setd0xhenfkb - this might be sorted, unless there are other changes you think we should make @K8Sewell?

**Comment by K8Sewell** [comment]
No, that's awesome to hear!  Thanks so much for your help here
