### ISSUE TITLE
Map Sierra 533 |n to CallNumberWithPublicNote - Metadata Cloud

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2640]
For Sierra, the 533 |n field should map to callNumberWithPublicNote.

**Acceptance**

- [x] Sierra 533 |n field maps to callNumberWithPublicNote in Metadata Cloud
- [x] Index callNumberWithPublicNote into callNumberWithPublicNote_ssim and callNumberWithPublicNote_tsim in Management if the ParentObject has "sierra" as the source.  (Do not index for ILS).

**Comment by martinlovell** [comment]
First PR: https://github.com/yalelibrary/metadata-cloud/pull/509 (Mapping for Metadata Cloud)

**Comment by martinlovell** [comment]
MC mapping is deployed to UAT. (I'm haven't found a BIB id that contains this field.  b17203089 is returning not-found.)

**Comment by martinlovell** [comment]
This bib has a value for that field: 1720320

**Comment by sshetenhelm** [comment]
Law has come back and decided that 533 |n, and only 533 |n, should map to the Call Number field. I can either A. Change the title/acceptance on this ticket or B. Make a new ticket. 

If we make a new ticket, I will pull it in Sprint and it should be done in this sprint so we can release the Sierra work.

**Comment by martinlovell** [comment]
I updated the mapping in Metadata Cloud, so sierra doesn't have a CallNumberWithPublicNote field, and the CallNumber field is 533n only. This is in UAT now.

Since there is no CallNumberWithPublicNote mapped for Sierra now, the code in Management and Blacklight doesn't necessarily need updating. (It will not be indexed in Management so it will not be displayed in Blacklight.)

**Comment by sshetenhelm** [comment]
Confirming that 533 |n is mapped to Call Number 
https://metadata-api.library.yale.edu/metadatacloud/api/1.0.1/sierra/bib/1720320?mediaType=json

Ready to close :)
