### ISSUE TITLE
OwP: Blacklight Parent Object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2653]
**Story**

For objects with OwP access, the Blacklight parent object page should display a message that indicates that access by request only.

**Acceptance**
On the Parent Object page, if the Parent has OwP access:

- [x] If the user is logged in *and* has been granted permission to access to the Parent OID, display the page normally
- [x] If the user is not logged in
  - [x] Display the message: `The material in this folder is open for research use only with permission. Researchers who wish to gain access or who have received permission to view this item, please log in to your account to request permission or to view the materials in this folder.`
  - [x] The words `log in` should be a login link
  - [x] The user should return to the page after logging in (this is the current behavior)
- [x] If the user is logged in and has not been granted permission access to the item:
  - [x] Display the message: `You are currently logged in to your account. However, you do not have permission to view this folder. If you would like to request permission, please fill out this form.`
- [x] In both cases (logged in or not) when the user has not been granted permission and thus is not authorized to see the digital content for the parent:
  - [x]  The UV should not display
  - [x] The text transcription should not display
  - [x] The PDF, Mirador, and Manifest links should be disabled

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/cac2e8a2-62f9-46ae-b339-c3dbb8188019)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/944

**Comment by mikeapp** [comment]
See comment in review

**Comment by mikeapp** [comment]
One more comment.

**Comment by K8Sewell** [comment]
Updated and ready for review again - https://github.com/yalelibrary/yul-dc-blacklight/pull/944

**Comment by K8Sewell** [comment]
Deployed to Demo

**Comment by K8Sewell** [comment]
I'm trying to set up some Open with Permission parent objects on demo but I'm not able to fetch the metadata for some reason.  Can I pair with someone to get these set up for testing?


https://collections-demo.library.yale.edu/management/batch_processes/124/parent_objects/800049872

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/65a0badd-8b47-48e3-a60c-d14aa53d9601)

**Comment by sshetenhelm** [comment]
Not sure what's up, but it pulled in some metadata for me. 

I've also made https://collections-demo.library.yale.edu/management/parent_objects/17297490 Open with Permission in Demo for testing purposes, and it has successful children so it displays on blacklight: 
https://collections-demo.library.yale.edu/catalog/17297490

**Comment by K8Sewell** [comment]
Thanks, @sshetenhelm !  Yep, metadata cloud was down for a bit yesterday but Martin restarted it.  Thanks for creating some more OwP objects to work with.

### Testing On Demo
User not logged in


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/694ae36a-b2ec-4afe-becd-77e997bb5524)



User logged in (without permission)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/0f29bfbe-7c54-4fe8-a3fe-8e1d63597886)


User logged in (with permission)

Incomplete - In order to get my user to agree to the terms and conditions associated with the permission set that the [2009400](https://collections-demo.library.yale.edu/catalog/2009400) object belongs to I would need to hop into the shell of the running container and manually create the permission request that would then need approved but unfortunately, I'm pretty sure I don't have access to that.  Will reach out for pairing time to test this.

**Comment by K8Sewell** [comment]
waiting until approval of permission request feature is built out so we can see a successful display of an OwP object

**Comment by laurenb33** [comment]
Everything looks good. I first looked at the object not logged in. The according messages showed up and the links for Manifest, PDF etc. were disabled. I signed in using the Login link in the message and it worked successfully. After approving my request in MGMT, I was able successfully view the object and all of it's metadata in DEMO UV.
