### ISSUE TITLE
OwP: Display T&Cs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2654]
**Story**

When an OwP request is initiated in Blacklight, the user must agree to the Terms and Conditions if they have not already done so.

Successful agreement to the T&Cs will result in the display of the request form.

**Acceptance**
- [x] Use the Management API to fetch the current T&Cs for the parent OID
- [x] If the user has not agreed to the T&Cs, display the T&Cs 
   - [ ]  Use the header/footer of the site layout, but without the search bar at the top or facets.
   - [x] Display the header text "You must accept the following terms and conditions in order to proceed" at the top of the page
   - [x] Display the T&C's title 
   - [x] Display the T&C's body
   - [x] A "Cancel" button should link back to the parent object page
   - [x] An "Agree" button should 
      - [x] cause the agreement to be saved to Management via API
      - [x] if saving is successful, display the request form  #2655 
- [x] If the user has already agreed to these T&Cs, display the request form
- [x] If the T&Cs call fails or an error occurs saving the agreement, redirect to the parent object display page with a flash message.

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/2b03b566-09b3-4815-a2e7-03b245651af7)

**Comment by martinlovell** [comment]
@mikeapp , the TermsAgreements are tied to PermissionRequestUsers.

We were wondering if they should be tied directly to the user (maybe with a `sub` property) since they may apply to multiple requests for the same PermissionSet, and a PermissionRequestUser isn't created until they agree to the terms.

Also, for PermissionRequest, there's a terms_approved property. We were thinking that should always be true initially since the user must agree before creating a request. Is it there for when the terms change? Should it be changed to false for all PermissionRequest that belong to a PermissionSet if the Terms are changed for that PermissionSet?
If that's the purpose, should it be set to true for all PermissionRequests belonging to a PermissionSet when the user agrees to the new terms?

**Comment by jpengst** [comment]
PR's:  
https://github.com/yalelibrary/yul-dc-blacklight/pull/959  
https://github.com/yalelibrary/yul-dc-management/pull/1314

**Comment by jpengst** [comment]
Floating footer and search bar:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/ff04065b-b47a-4f79-bd81-f352a2da2a3c)

**Comment by jpengst** [comment]
Bug PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/961

**Comment by sshetenhelm** [comment]
Looks good! Ready to close. Thank you :)
