### ISSUE TITLE
Ensure Asset Pipeline is correctly rendering

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#275]
**ACCEPTANCE**
- [ ] I get the expected CSS and visual styling for management application pages when I deploy it to ECS

**Comment by maxkadel** [comment]
Breadcrumbs
- We attempted to set up Bootstrap 4, but since we did so without running in production mode, it's completely possible we did so incorrectly (this includes me, because I made some yarn, etc., changes)
  - One change was moving application.css to application.scss, but it looks like (application.css is still referenced in a number of places)[https://github.com/yalelibrary/yul-dc-management/search?q=application.css&unscoped_q=application.css]
- We also commented out a line that was causing failing tests, seemingly because we didn't have any local css. May have taken the wrong approach here - see https://github.com/yalelibrary/yul-dc-management/blob/138653c9145614f943a083e9127e698eb35a03da/app/views/layouts/application.html.erb#L10

**Comment by orangewolf** [comment]
this is working properly when running the app locally.  I wonder if config.relative_url_root (or env RAILS_RELATIVE_URL_ROOT) is being set in production. since we access the app behind the loadbalancer under /management, this will need to be set for links to things like stylesheets to work properly. (I can investigate, just leaving notes here in case someone else grabs it)

**Comment by mark-dce** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/3064318/86934598-82189a80-c101-11ea-81d7-81337bb1701b.png">
