### ISSUE TITLE
Protect environments against DNS rebinding attacks

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#277]
**ISSUE**
Rails 6 added protection against DNS rebinding attacks.  Since we were inadvertently running in development mode on ECS, we ended up having to configure `config.hosts` to include our production domain names.  

There's a pretty good writeup of how this type of attack works and how to set the corresponding checks here: [DNS rebinding attacks protection in Rails 6](https://prathamesh.tech/2019/09/02/dns-rebinding-attacks-protection-in-rails-6/).  
*Also see:* [Configuring Middleware](https://guides.rubyonrails.org/configuring.html#configuring-middleware) in the Rails Guides.

We need to determine if we need anything other than the default behavior in development (only allow localhost) and production (don't check).  

We should consider allowing the following in production (using wildcards as described in the rails guide)
* *.curationexperts.com
* *.elb.amazon.com
* *.library.yale.edu

**ACCEPTANCE**
- [ ] Review the links above and any other relevant documentation
- [ ] Determine the appropriate settings for development
- [ ] Determine the appropriate settings for production
- [ ] Implement the desired settings in
    - [ ] yul-dc-blacklight
    - [ ] yul-dc-management

**Comment by maxkadel** [comment]
I think part of the issue is that the health checks run against a host other than `*.elb.amazon.com` (possibly the IP address), so when you deploy, they are never seen as healthy if you have any hosts configured for production (at least that's how it seems, hard to figure out when the services are flapping quickly). 

I think any work on this ticket should involve deploys of branches against the latest version of Camerata, and ensure that they still deploy successfully with the hosts.config.
