### ISSUE TITLE
Enable OwP Ingest with Preservica

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2836]
# Summary
No logic existed to handle the permission set value in a Preservica ingest.  The PR below sets up this logic and enables ingests with Preservica to correctly create parent objects with OwP visibility.

# PR
https://github.com/yalelibrary/yul-dc-management/pull/1387

**Comment by K8Sewell** [comment]
Deployed to UAT with release [v2.69.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.3)

**Comment by sshetenhelm** [comment]
- Confirmed was able to [create OwP parent using Preservica](https://collections-uat.library.yale.edu/management/batch_processes/1955/parent_objects/901623965), although still received PTIFF error (which is still in progress so understandable)
- @laurenb33 -- we need to make one of us a regular user instead of Sys Admin to test permissions for Perm Set non-admins

**Comment by sshetenhelm** [comment]
I am not an administrator or approver for the Permission Set "Test Permission Set 01," but as a regular user, I was able to create a parent that goes into that set: https://collections-uat.library.yale.edu/management/parent_objects/901623974 
Batch process - https://collections-uat.library.yale.edu/management/batch_processes/1960/parent_objects/901623974

...although still received the usual PTIFF errors.

**Comment by K8Sewell** [comment]
Summer, is it possible that you were still a sysadmin when the batch process - 1960 - was processed?  I checked this morning and you are presently a sysadmin so out of curiosity I updated myself to not be a sysadmin and removed myself from the test_01(key) permission set and when I tried with the csv you used in 1960 I got the not permitted message as expected.  I was not sure if you were set back to sysadmin since 1960 was processed - if so I'll keep investigating but thought it might be worth retesting if not.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/ca65951f-7201-4b94-be30-3964a0052c0a)

**Comment by sshetenhelm** [comment]
I'm 95% sure I was a regular user when I performed the process, but I will try again just to double-check.

**Comment by sshetenhelm** [comment]
1. Had Lauren make me normal user again
2. Logged into UAT in incognito browser to make sure nothing was cached or something
3. Uploaded spreadsheet with "kiss" Kissinger permission set in [BP 1967](https://collections-uat.library.yale.edu/management/batch_processes/1967/parent_objects/901623979)
4. Was able to create parent, but parent failed b/c of PTIFF error

Do you think this may be because I originally created the Kissinger set?

Screenshot: 


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/7d915909-ce1e-4427-a502-c0e54a104844)

**Comment by sshetenhelm** [comment]
Apparently I get to do whatever I want -- [this batch process](https://collections-uat.library.yale.edu/management/batch_processes/1970/parent_objects/901623981) is with the "new" set JP created

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1400

**Comment by jpengst** [comment]
Deployed to UAT v2.70.0

**Comment by sshetenhelm** [comment]
I've asked one of our staff members who have never been a SysAdmin in UAT to try and create a parent into a Permission Set they haven't been added to, in case there's something about my netID in particular that is linked with something. 
As long as regular, Never Been Sys'ed users can't create random OwP parents, we don't need this to be a blocker for the MVP release (although we should continue to investigate).

**Comment by sshetenhelm** [comment]
Confirmed that a Never Been Sys'ed user cannot create OwP object in OwP set they have not been added to: 

https://collections-uat.library.yale.edu/management/batch_processes/2061 

We can create a separate ticket to look into my superpowers, but I think the original goal of this ticket -- ensure OwP with Preservica ingests -- is completed.
