### ISSUE TITLE
[SPIKE] Universal Viewer - Block selected child image in parent

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2845]
**Story**
As part of the upcoming "Opt-In" feature development work, stakeholders may want to know if it is possible to require a user action to allow a single child image that is in a parent object to display. 

So, if a parent object has two child images, and the second is an "opt-in" image, can we leave the first image visible in the Universal Viewer with all metadata in the 'More Information' pane, but require the user to click something to see the second image in the UV (but the second image would still have metadata in the more information pane). 

**World's most beautiful mock-up**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/0d0bceca-4020-4d10-b587-3ab668a19e03)

**Acceptance**

- [x] Determine if it is or is not possible to require a user action to display a single child object image
- [ ] If possible, try to estimate the amount of "lift" required to make the change in blacklight _(ex. pretty easy, not easy but not impossible, would take 84 years, etc.)_
- [ ] If possible, try to estimate the amount of "lift" required to devise a way to designate these child objects in the Management App (batch process? on the child object page? etc.) _[NOTE: a response of "it is impossible to determine this until we have more specs" is acceptable]_

**Comment by jpengst** [comment]
Currently, there is no option in UV to require a user action. In order to do something like this, I think we would have to go into the UV code itself and add this feature ourselves. UV has a slack channel that I requested access to. Once I've been given access I can ask if they have any plans on adding something like this in later versions.

**Comment by jpengst** [comment]
https://iiif.io/api/auth/1.0/#clickthrough-interaction-pattern

**Comment by mikeapp** [comment]
The clickthrough examples on the UV demo page such as  https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb1818893x%2Fmanifest&xywh=-1611%2C-223%2C5864%2C4405  don't seem to be working.   I'm not sure what's supported in UV and Mirador (which we shouldn't forget about - it's going to be difficult to have a consistent experience in both viewers).

**Comment by jpengst** [comment]
Kait and I found a working example, that kind of does what we're looking for. The confirmation dialogue opens after you click "View": https://wellcomecollection.org/works/bxhrqs86  
  
However, this clickthrough example is for the entire collection of images and not for a specific image. So I'm not entirely sure if it's possible to enable this for a specific image, just because we haven't seen a working example of it.   

I think implementing this like the working example above would be at least an 8. And implementing this for a specific image would be at least a 5 if we can figure out how to implement for the object first.

**Comment by sshetenhelm** [comment]
In terms of "whole parent" alerts, Princeton has a useful example as well -- https://findingaids.princeton.edu/catalog/C1372_c47202-68234?onlineToggle=false
