### ISSUE TITLE
[BUG] Ensure Correct Worker Picks Up Correct Queues

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2860]
# Summary
A Save to S3 job, which is in the default queue, appears to have been picked up by the intensive worker instead of the regular one.  The ACCESS_MASTER_MOUNT on prod was s3 for the abandoned Save to S3 job's first run that failed.  When re-ran the job succeeded.

# Acceptance Criteria
- [ ] Intensive worker does not pick up any jobs on any queues except pdf and intensive_solr_index
- [x] Ensure ACCESS_MASTER_MOUNT is '/data' on production for the regular worker and 's3' for the intensive worker

# Engineering Notes
Abandoned Save to S3 job - https://collections.library.yale.edu/management/jobs/jobs/546d6829-cb03-4b8b-b1bf-3518b3e5cd9b?locale=en

Successful Save to S3 job - https://collections.library.yale.edu/management/jobs/jobs/43e0c2f0-2e15-4749-9737-c9fb30d1b0a1?locale=en

[teams discussion](https://teams.microsoft.com/l/message/19:3b846173e3bf4c84a3d154056c4bb447@thread.tacv2/1718227629631?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=2feb0d22-b950-4c85-8e0e-501978f59a2b&parentMessageId=1718227629631&teamName=Engineering%20Projects%20with%20Consultants&channelName=DCS&createdTime=1718227629631)

**Comment by sshetenhelm** [comment]
When testing the 'Recreate Child OID PTIFF' batch process, I received a "PTIFF not found" error for an image that is very clearly in Management. Here's the batch process:[https://collections.library.yale.edu/management/batch_processes/17211](https://collections.library.yale.edu/management/batch_processes/17211)
 
Error message:
`Child Object 32287832 failed to convert PTIFF due to Expected file originals/32/32/28/78/32/32287832.tif on S3 not found.	`
However, when I navigate to the [individual child object page](https://collections.library.yale.edu/management/child_objects/32287832), I can see the thumbnail and successfully download the PTIFF.

**Comment by sshetenhelm** [comment]
Retried the spreadsheet mentioned in the above comment, and [the batch process was successful this time](https://collections.library.yale.edu/management/batch_processes/17229). 

Was also able to complete a Preservica Resync, although I now realize it's with the object that has the same image saved for all the child images (whoops). But the good news is that it successfully completed this time (even if it completed... wrong). Not sure if that was helpful for this, but thought I'd add it. 

Any other tests to confirm this works?

**Comment by K8Sewell** [comment]
I don't think there are any other tests we need to do.

**Comment by sshetenhelm** [comment]
Cool! Ready to close. THANK YOU!
