### ISSUE TITLE
BUG: Allow regular Management users to press "Resync with Preservica" button

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2863]
**Story**
We would like to enable "Synchronize child objects" button at the bottom of a parent object page in Management for all users in Management. Currently, the button is visible to all DCS users, but only "enabled" for MGMT sys-admin. Non-SysAdmin users get the "Access Denied" message.

Stakeholders will need the ability to re-sync their parent objects with Preservica.

**Acceptance**
- [x]  Enable "Synchronize child objects" button in Management for all users with edit permissions for an admin set

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1409

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.6)

**Comment by K8Sewell** [comment]
Made myself a regular user and was able to trigger sync from presevica on Test.  Will promote to UAT for real testing since test preservica instance is only connected to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/d130862a-2617-42c5-856d-0e6690d882a7)





![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/17e10653-32ff-4669-a329-f1314cc62007)

**Comment by sshetenhelm** [comment]
Worked for me after being made a non-SysAdmin. Asking Lauren to test as well.
