### ISSUE TITLE
Line Coverage @ 0% : omniauth_callbacks_controller.rb 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#289]
As an ops manager, I want app > controllers > omniauth_callbacks_controller.rb near or at 95% so that there is less risk of inadvertent changes to functionality that would change behavior in production.

**Comment by edejesusyale** [comment]
Adding tests for this controller doesn't seem to be trivial due to devise not being able to route to the authorization within Rspec. There appears to be more configuration needed for either devise or omniauth to allow for correct routing within the tests to allow for suitable tests to be coded and ran.

**Comment by alishaevn** [comment]
maybe this will help??? https://gitlab.com/LordMike/gitlab/-/blob/master/spec/controllers/omniauth_callbacks_controller_spec.rb

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/164 - Need help from someone w/ CAS log in ability to pull down code and confirm that the CAS log in still works before merging this in.
