### ISSUE TITLE
Line Test Coverage @ 0% : search_history_controller.rb 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#290]
As a product owner, I want app > controllers > search_history_controller.rb  near or at 95% so that there is a better understanding of features included in the test coverage.

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/152

# Expected Behavior
- the "search_history_controller.rb" file has passing tests
- I took the test from the project blacklight repo and updated them so that they pass rubocop

# Resources
- https://github.com/projectblacklight/blacklight/blob/master/spec/controllers/search_history_controller_spec.rb
