### ISSUE TITLE
Spike: Investigate YUL-DC Handle Redirects

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2942]
@thescreamingmandrake was looking to see what repositories needs to be moved to the new Jenkins. A question was raised whether the YUL DC Redirects rep needed to be in the new Jenkins or not. Before the whispering root proceeds, we need to investigate what the redirect handles in the container lead to and whether they need to be updated to the new Jenkins. 

**Acceptance**
- [x] Investigate redirect handles 
- [x] Record findings
- [x] Report back to team

**Comment by thescreamingmandrake** [comment]
Code location of the redirects: https://github.com/yalelibrary/yul-dc-redirects

**Comment by laurenb33** [comment]
The only redirect I could find in the rep was http://brbl-dl.library.yale.edu/. I've never heard of the site or of anyone using it. The last commits were from 3-4 years ago, so it appears that the transition to the DCS happened several years ago.

**Comment by laurenb33** [comment]
Redirects for MARC records

**Comment by sshetenhelm** [comment]
It actually looks like there are still catalog records using this handle -- ex. https://search.library.yale.edu/catalog/9700046?block=Books 

Hover over link for 'View a digital image in the Beinecke Library's Digital Images Online database'

This object has not been reassociated yet, which is why the original link is still in the catalog record and not the automatically created one. There are still 68,760 Beinecke objects that are associated with Ladybird, so we may need a report from Voyager of these objects to see what others have this link. They will need either be manually replaced or have the handles kept until reassociation is complete.
