### ISSUE TITLE
[BUG] Sort by Year results list varies

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2944]
In Blacklight, there are discrepancies between the behavior of _Sort by Year, Ascending_ and _Sort by Year, Descending_. 

Sometimes _Sort by Year, Descending_ appears to work as expected and take into account the Volume/Container. Example:
https://collections.library.yale.edu/catalog?f%5BcallNumber_ssim%5D%5B%5D=YL+05+L48+tall&sort=year_isim+desc%2C+id+desc%2C+archivalSort_ssi+asc

However, sometimes sorting in search results works as expected but then “starts over” in _Descending_ Order when a publication name is changed:
https://collections.library.yale.edu/catalog?f%5Bproject_identifier_tesi%5D%5B%5D=28&per_page=100&q=&search_field=all_fields&sort=year_isim+desc%2C+id+desc%2C+archivalSort_ssi+asc

Even though _Descending_ seemed to work as expected, for these same materials, _Sort by Year, Ascending_ does not seem to include Volume/Container. Example:
https://collections.library.yale.edu/catalog?f%5BcallNumber_ssim%5D%5B%5D=YL+05+L48+tall&sort=year_isim+asc%2C+id+desc%2C+archivalSort_ssi+asc

Sometimes _Sort by Year, Ascending_ gives the same results as _Sort by Year, Descending_. Example: https://collections.library.yale.edu/catalog?f%5Bproject_identifier_tesi%5D%5B%5D=28&per_page=100&q=&search_field=all_fields&sort=year_isim+asc%2C+id+desc%2C+archivalSort_ssi+asc 

We would like
* Sort by Year, Ascending/Descending to display search results in order by date, and not “start over” when a publication changes
* Sort by Year, Ascending/Descending to take into account Volume/Container information, if possible

**Acceptance**

- [ ] _Sort by Year, Ascending_ displays search results in order by date, and doesn't “start over” when a publication changes
- [ ] _Sort by Year, Descending_ displays search results in order by date, and doesn't “start over” when a publication changes
- [ ] _Sort by Year, Ascending_ takes into account Volume/Container information (if possible)
- [ ] _Sort by Year, Descending_ takes into account Volume/Container information (if possible)

**Comment by jpengst** [comment]
We are currently sorting by `year_isim` from the solr record. The examples of the results "starting over" is because those objects do not have a `year_isim` attached to the solr record, so the sorting is then defaulting to the id and the year isn't being taken into account at all. The date being displayed for these records is coming from `date_ssim`, not `year_isim`, which is why it isn't sorting by those years.  
  
PR for adding `date_ssim` as a fallback sorting field: https://github.com/yalelibrary/yul-dc-blacklight/pull/1064
  
The successful year sorting results is because all of those records have a `year_isim` in their solr records.  
  
I don't think we can add Volume/Container to the Year sorting because some of these values do not include a year and some have the year at the end or middle of the string. Example is something like "Box 1" or "v.5 no.1 2006 Jan/Feb". In these examples, the sorting would sort based on the letters, not year.

**Comment by jillpe** [comment]
Waiting for Summer's feedback

**Comment by jpengst** [comment]
The date sorting works using year_isim. 
- Correct  
  
With the current PR, if there is no year_isim, then date_ssim will be used for sorting.  
- I've actually removed the date_ssim from the sorting because the date_isim data was inconsistent. Sometimes the date_isim would be something like `Jan 1900` instead of just the year.  
  
The reason the Legal Affairs journals appear to sort correctly in Descending is because of the order of the individual object OIDs, and not the dates. That's why the results appear the same in Ascending--since all records share the same dates (the years 2002-2006), they will display in the same order regardless of date of individual issue.  
- Correct. Since they all share the same year range, it then sorts by oid.  
  
And we can't do Container/Volume because of variances in descriptive practices across records.  
- Correct. Similarly to date_isim, the data is inconsistent.  
  
  
The PR does fix the last linked example in the ticket where the results were the same in asc/desc:  
https://github.com/yalelibrary/yul-dc-blacklight/pull/1064

**Comment by sshetenhelm** [comment]
Great, this is really helpful. So it seems like moving forward with the PR you've posted is fine, and I'll have to regroup with our metadata for digital objects group about inconsistent data. Let's move this ticket into Team Review and just address that PR since these are mostly metadata issues as opposed to "bugs."

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.8](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.8)

**Comment by sshetenhelm** [comment]
Looks good on test. Let's bump to UAT please.

**Comment by sshetenhelm** [comment]
Works as expected on UAT. Thanks! 

Ready to close :)
