### ISSUE TITLE
Cantaloupe v 6- Review new version

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2961]
**Story**
To prepare for upgrading our image servers after winter break, we should review both our current [IIIF image server repo](https://github.com/yalelibrary/yul-dc-iiif-imageserver) and the new Cantaloupe image server version **(targeting version 6, slated to be released at the end of November)** to understand if configuration options have changed. For example, the Ruby file -- is that more or less the same, or is there anything that we used that as changed?

After, we should make individual tickets for indivual changes -- ex. Pair Tree layout, Dynatract, Honeybadger, etc.

We should also consider boosting the image server RAM and turning on auto scaling.

**Acceptance**
The following team members review IIIF image server repo and new Cantaloupe version:

- [x] _[Kait]_
- [x] _[JP]_
- [ ] _[Other?]_
--
- [ ] New tickets are made for necessary work

**Comment by sshetenhelm** [comment]
Mike attended a IIIF meeting where it was stated that Cantaloupe version 6 will be released "at the end of the month." As such, I'd like us to please target version 6 instead of version 5 for release. I'll note that in the main body of the ticket as well.

**Comment by jpengst** [comment]
Here are the major changes with the upcoming 6.0 release (https://github.com/cantaloupe-project/cantaloupe/blob/develop/CHANGES.md#60)  
It looks like there are a couple configuration changes we need to make, but overall doesn't seem like a major lift.  
One of our endpoints needs to be adjusted:  
`endpoint.api.enabled` -> `endpoint.health.enabled`  
  
There's a mention of a Delegate Scripts change:  
`delegate_script.pathname` -> `-Dcantaloupe.delegate_script`. The release notes says this is VM argument, which takes precedence over the way we currently have it in the properties file. But I think this is an optional change? Sounds like they just added the ability to add a VM argument instead of the configuration key if we wanted.

**Comment by K8Sewell** [comment]
We are currently on Cantelope 4.1.11.  There are a number of changes needed to get us current as detailed in the [Upgrade Instructions](https://github.com/cantaloupe-project/cantaloupe/blob/develop/UPGRADING.md).  There will be more work to go from 4 to 5 than to go from 5 to 6 but I agree with JP - it doesn't seem like a major lift.  I would love to do a timeboxed spike to see how tough the upgrade is.
