### ISSUE TITLE
Display a message when images are "Yale Only"

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#298]
**ACCEPTANCE**
* When I am not logged in
* AND I view a Yale-Only resource
- [ ] Display a message about access to the image: "The digital version of this work is restricted to the Yale Community.  Please login using your Yale NetID or contact library staff to inquire about access to a physical copy."

**CURRENT BEHAVIOR**
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3064318/86143163-b8c73300-bab9-11ea-8122-925fd66f7e97.png">

**DESIRED BEHAVIOR**
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3064318/86143833-8bc75000-baba-11ea-8b0c-b009fbf87ed0.png">

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/157

# Expected Behavior
- logged out users see a message that says "The digital version of this work is restricted to the Yale Community.
Please login using your Yale NetID or contact library staff to inquire about access to a physical copy." for private works
- logged in yale users do not see that message
- Dev's can write up to 20 lines per "it" block instead of 5

# Demo
### Logged out
![image](https://user-images.githubusercontent.com/29032869/86283018-1b413180-bb95-11ea-806e-94ff72577361.png)

### Logged in
![image](https://user-images.githubusercontent.com/29032869/86283148-53487480-bb95-11ea-84e8-f65a2349cd27.png)
