### ISSUE TITLE
Yale fonts and colors

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#319]
**STORY**
Based on conversations with Matt Walker, we'd like to apply Yale branded visual styling to the discovery application.  We'd like to define key styles (colors, fonts, headings, etc.) to be easily reusable throughout the site and when adding new features and content.  Yale has developed a Component Library based on Bootstrap 4, which we can use as a starting point: https://yale-a11y.gitlab.io/ui-component-library/.

**ACCEPTANCE**
- [ ] Make a time-boxed effort to implement Yale branded CSS
- [ ] Identify any outstanding questions or issues for further discussion with Matt

**COVERAGE**
Implement as many of the layout elements described on this page as possible
- [ ] https://yale-a11y.gitlab.io/ui-component-library/examples

**Comment by FCRodriguez7** [comment]
https://yaleidentity.yale.edu/typefaces

**Comment by FCRodriguez7** [comment]
The Yale Mallory font:  https://drive.google.com/drive/folders/1X71ql42CehllK34o6KcF7brlCakP-e3k?usp=sharing

**Comment by FCRodriguez7** [comment]
Please provide your email if you would like access to the Mallory Yale Font folder.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/167

# Screenshots
### Home Page
* Updated header background to Yale Blue
* Updated h1, h2 to use MalloryMP-Bold font
<details>
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/36549923/87085677-1dcf0700-c1e5-11ea-90f6-1378533b85aa.png">
</details>

### Icons & Logo Included
* Mail, Facebook, Twitter, Instagram, YUL Logo, Music Thumbnail, X, and checkboxes
<details>
<img width="163" alt="image" src="https://user-images.githubusercontent.com/36549923/87085868-76060900-c1e5-11ea-851d-ae6419acd1d2.png">
<img width="51" alt="image" src="https://user-images.githubusercontent.com/36549923/87085928-8f0eba00-c1e5-11ea-84f1-bf57764645cc.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/36549923/87085956-9c2ba900-c1e5-11ea-9f27-e1eb91524e57.png">
<img width="146" alt="image" src="https://user-images.githubusercontent.com/36549923/87085975-a6e63e00-c1e5-11ea-9ff6-b0acb1e16f28.png">
</details>

**Comment by bess** [comment]
Because of the licensing attached to the Yale fonts, we are not allowed to redistribute them. Instead, we'll need to reference them as they are being served out by the main yale.edu website. For example, here: https://www.yale.edu/sites/all/themes/yale_blue/fonts_new/Mallory/Mallory/Mallory-Light.woff. @alishaevn and @Kait Sewell are working on a PR to add the fonts to our application, and they're following these guidelines. I don't think we'll need to reference the fonts again once they're in the bootstrap configuration, but just in case: do not add the fonts to our github repo, please use external references to them instead.

**Comment by alishaevn** [comment]
_Created a new PR so that the font files in the old one didn't get added to the code base._

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/168

Co-authored by: Kait Sewell <kait@notch8.com>

# Summary 
- Adds Yale branded colors as variables
- Adds Yale branded typefaces as variable
- Adds breakpoints as variables
- Sets up the structure for mobile first design in the header and footer sass files.

# Screenshots
### Existing Yale header
![Screen Shot 2020-07-09 at 4 26 38 PM](https://user-images.githubusercontent.com/29032869/87100395-23d2e100-c201-11ea-9002-47312849773b.png)

### Updated Yale header
![image](https://user-images.githubusercontent.com/29032869/87100445-4e249e80-c201-11ea-988d-4eb59c6a8266.png)

**Comment by alishaevn** [comment]
The updated header color was deployed to https://collections-test.curationexperts.com/ this morning.
