### ISSUE TITLE
Consolidate bin/get_params & bin/deploy scripts

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#328]
**STORY**
The get_params script is only required when another engineer built a cluster and the corresponding ecs_params file doesn't exist on the local machine.  The current deploy script detects this and gives the corresponding command to invoke, but does not automatically run the command.  There's no apparent benefit from having these two commands run separately, so the deploy script should just automatically run the params script as needed.

**ACCEPTANCE**
- [x] I can deploy to a cluster I haven't built without needing to manually run get_params first.
- [x] Documentation is updated correspondingly

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/91 ready for team review

Future refinement: moving the specifications of memory and cpu options to be optional arguments to the deploy scripts; refining the deploy-main script to detect whether the service exists, eliminating the need for the --enable-service-discovery option.  (Already implemented for solr, database; not changed in documentation yet because including the option as specified in documentation won't hurt anything.)
