### ISSUE TITLE
Update pagination controls to more closely match Yale styling and branding

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#387]
**ACCEPTANCE**
Given the pagination header styling shown in the [Digital Collections - Search Results] - both above and below search results. (https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758)
- [x] Update the discovery application to match the styling as closely as possible
- [ ] Write up a new ticket(s) for any parts of the design that are problematic to implement in blacklight

**NOTE**
Feel free to reach out to Matt Walker with any questions or proposed changes that might make it easier to implement the design.

*Top*
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/b1c073f7-1c53-4a50-b6ab-18ee0f33c90f)
*Bottom*
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/07dfbc3b-09a2-4544-b226-eb375a49b53a)

**Comment by FCRodriguez7** [comment]
**HEADER**
![Screen Shot 2020-07-28 at 1.12.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/35543286-7c17-4c4a-90fd-d929efa78066)


**FOOTER**
![Screen Shot 2020-07-28 at 1.12.17 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9d894fb4-f0a4-4f21-ba99-ae022853d071)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/227

**Comment by alishaevn** [comment]
# Story
Update the discovery application to match the styling as closely as possible

# Expected Behavior
(all colors listed match the Yale branding, not the default blacklight colors)
- The "previous" and "next" links are blue in the top navigation whether they are disabled or not
- The numbered page items are grey
- The "previous" and "next" links in the bottom navigation are blue when active and grey when disabled
- The "previous" and "next" links in the bottom navigation are to the left of the numbers because that's the default blacklight styling. The importance of changing that flow to match the design will be discussed with Matt when he's available
- The current page number is highlighted blue and the number is in white. That is the default way to denote page number and the design didn't designate another way to do it, so I left it that way

# Demo
#### Top
![image](https://user-images.githubusercontent.com/29032869/89951493-63199680-dbe0-11ea-8cbe-2f6175ab95c2.png)

#### Bottom
![image](https://user-images.githubusercontent.com/29032869/89951518-6d3b9500-dbe0-11ea-94dd-7b084b5d2406.png)

**Comment by K8Sewell** [comment]
Seeing updated pagination controls when I checkout this branch

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/69d5fe08-daa3-4fdf-ba42-e5c48fbe8a03)

**Comment by alishaevn** [comment]
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/45fb2d19-9d37-4948-a04d-16b8b2d65add)
