### ISSUE TITLE
Remove duplicate title listing in search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#422]
**ISSUE**
The title of a work is appearing twice in search results

**ACCEPTANCE**
- [ ] The second instance of the title is not present in search result listings

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3064318/89921129-e926e480-dbc2-11ea-9c80-416b222d22c6.png">

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/233

# Expected Behavior
- The "Title" property doesn't show up in search results
- The highlighting spec doesn't reference the "Title"

# Demo
![image](https://user-images.githubusercontent.com/29032869/90039301-4c744d80-dc7b-11ea-8099-4be12c403fe8.png)

**Comment by alishaevn** [comment]
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/871f81be-b825-4f97-ac69-52a6e126f402)
