### ISSUE TITLE
Refine facet styling

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#428]
# Summary
Feedback relayed from Matt on in progress facet design

# Acceptance Criteria
- [ ] 'Limit your search' needs to be bolded
- [ ] 'Limit your search' needs converted to MalloryMP-Black font
- [ ] Facet headers need converted to MalloryMP-Medium font
- [ ] Convert font size to px (8px facet header, 6px facet item, 7px 'limit your search')
- [ ] Reduce space between facet headers - there should be 16px between the top of one and the bottom of the other

# New UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/91b34d95-e168-4160-b5f7-96ae3b13b02e)

**Comment by alishaevn** [comment]
As info, we don't have access to all of the fonts on the zeplin board since we can only use a web linked version. For instance, Mallory vs MalloryMP. The fonts that we were able to find on the existing Yale site and currently have in the codebase are:
- YaleNew-Roman
- YaleNew-Italic
- Mallory-Light
- Mallory-LightItalic
- Mallory-Medium

**Comment by alishaevn** [comment]
#MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/235

# Expected Behavior
- 'Limit your search' has a font weight of 900, but is not as bold as in the design because we don't have the Mallory Black font
- 'Limit your search' is in the Mallory Medium font
- Facet headers are in the Mallory Medium font
- The facet titles and drop down items match the look of the design, but aren't the exact font-sizes in the design. If they were, they'd be too small
- Reduced the space between facet headers. It isn't exactly 16px between them though because the styles that were inherited from the blacklight app are set with `!important` so they can't be overridden.

# Demo
![image](https://user-images.githubusercontent.com/29032869/90196434-9dba3500-dd80-11ea-8fde-4d2e165ca41a.png)

**Comment by alishaevn** [comment]
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/29c0c27f-45f7-4faf-8f32-b2de4bffde8d)
