### ISSUE TITLE
Preliminary metadata grouping

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#494]
**ACCEPTANCE**
- [ ] We have a design for grouping metadata
- [ ] The item-level show page uses the (preliminary) groupings below

**Description**
* extentOfDigitization
* numberOfPages_ssim
* indexedBy (Beinecke collection name?)
* references (may contain same data as indexedBy
* abstract
* caption
* illustrativeMatter
* scale_ssim
* projection_ssim

**Keywords**
* format
* resourceType
* material
* geoSubject
* subjectEra

**Origin**
* copyrightDate
* date
* dateDepicted
* dateStructured
* digital (field name in metadata cloud - appears to be photographer/publisher)
* edition
* sourceCreated
* sourceDate
* source_ssim
* sourceEdition
* sourceNote
* sourceTitle
* publicationPlace
* publisher

**Itentifiers**
* repository
* partOf
* collectionId
* accessionNumber
* archiveSpaceUri
* box
* folder
* findingAid
* identifierShelfMark
* localRecordNumber
* oid
* orbisBarcode
* orbisRecord
* uri
* relatedUrl

**Usage**
* accessRestrictions
* itemPermission
* rights

**Migration Source** (Preview only)
*recordType

**Comment by DraxIndustries79** [comment]
Example: https://digital.library.ucla.edu/catalog/kxc8j200zz-89112

**Comment by K8Sewell** [comment]
Presently working on using css grid layout to define groups rather than over writing the render method in the blacklight helpers.  Will provide further update and link to branch before close of workday.

## Notes on categories and groupings
### Description
- [x] abstract_tesim
- [ ] caption - (no matching fields w/ caption)
- [x] extent_ssim
- [x] extentOfDigitization_ssim
- [x] illustrativeMatter_tesim
- [ ] indexedBy (Beinecke collection name?) - Collection Name is partOf_ssim which is listed in identifier category below
- [x] numberOfPages_ssim
- [x] projection_ssim
- [x] references_tesim
- [x] scale_tesim

### Usage
- [x] rights_ssim
- [ ] accessRestrictions (no matching fields w/ access)
- [ ] itemPermission (no matching fields w/ permission)

### Migration Source (Preview only)
- [x] recordType_ssi

### WIP
Keywords

    format
    resourceType
    material
    geoSubject
    subjectEra

Origin

    copyrightDate
    date
    dateDepicted
    dateStructured
    digital (field name in metadata cloud - appears to be photographer/publisher)
    edition
    sourceCreated
    sourceDate
    source_ssim
    sourceEdition
    sourceNote
    sourceTitle
    publicationPlace
    publisher

Itentifiers

    repository
    partOf
    collectionId
    accessionNumber
    archiveSpaceUri
    box
    folder
    findingAid
    identifierShelfMark
    localRecordNumber
    oid
    orbisBarcode
    orbisRecord
    uri
    relatedUrl

**Comment by K8Sewell** [comment]
Draft PR Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/29a036c1-2a9b-4c6a-a60c-44dc5f474ca5)

**Comment by K8Sewell** [comment]
https://github.com/UCLALibrary/ursus/blob/master/app/views/catalog/work_record/_access_condition_metadata.html.erb

**Comment by K8Sewell** [comment]
Basic bones in place, just wrapping up dynamic set up of the first 4 categories and tests.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8bad12a3-2378-40c7-90ed-ed751ec20245)

**Comment by K8Sewell** [comment]
Have successfully grouped the metadata with the implementation pattern suggested but in the process have broken all the links so will be working on this further but have updated the [Draft PR](https://github.com/yalelibrary/yul-dc-blacklight/pull/252/) with the most up to date work I have.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/34d6a9c2-06f0-40ca-b7a7-6605272eb291)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/252
