### ISSUE TITLE
SPIKE: Adjust pagination options for gallery view vs. list view

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#515]
**ISSUE**
When I'm in gallery mode, the pagination options aren't divisible by 3, so the bottom row of the gallery is always incomplete.

**ACCEPTANCE**
- [x] When I'm in Gallery Vie - Set the per-page item options to 9, 30, 60 and 99

- [x] When I'm in List View - Set the per-page item options to 10, 20, 50, 100

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/287

# Expected behavior
- in gallery view the "per page" option is 9, 30, 60 and 99
- in list view the "per page" option is 10, 20, 50, 100

# Demo
![515](https://user-images.githubusercontent.com/29032869/93277979-35dc7d00-f778-11ea-8191-a94e50a477b1.gif)

**Comment by dl-maura** [comment]
Works -- I confirmed the switch of options and also was able to use all the options (I didn't hand count but the numbers change and also there are more/less things)
![Screen Shot 2020-09-16 at 6.18.03 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6d176bb6-6b21-4e86-a717-036db478d96b)
![Screen Shot 2020-09-16 at 6.18.10 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/7633ffbc-806d-404f-a58a-c72c9135adfb)
