### ISSUE TITLE
Do not use personal credentials to access S3 in production

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#529]
**ISSUE**
On production like clusters running in ECS, we would like to use IAM roles instead of individual user credentials to access content stored in S3 buckets.

**ACCEPTANCE**
- [ ] The management application can access S3 when running in ECS without requiring individual IAM user AW_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY credentials

**DETAILS**
See [IAM Roles for Tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) for one possible strategy.

Also see "Adding Amazon S3 Read-only Access to your Container Instance Role" in [Amazon ECS Container Instance IAM Role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html)

**Comment by JzGo** [comment]
- Created a role [ecsRoleForYaleS3](https://console.aws.amazon.com/iam/home?#/roles/ecsRoleForYaleS3) utilizing the Yale-S3Access policy
- Have a branch on camerata to connect that role arn to the tasks: https://github.com/yalelibrary/yul-dc-camerata/compare/use_iam_role_for_s3?expand=1

As is the role is available to all containers in the task

**Comment by dl-maura** [comment]
@kbcarter @bobrice need to paid here for some yul specific permissions

**Comment by JzGo** [comment]
Draft PR for conditionally granting access to buckets based on cluster names: https://github.com/yalelibrary/yul-dc-camerata/pull/212

**Comment by JzGo** [comment]
Updated the PR to move all AWS credentials from base compose files to the compose.local files and confirmed that blacklight, management, manifests, images, and solr services all start up with these changes to camerata.

The change moves AWS credentials in these files:
- templates/iiif-images-compose.yml --> templates/iiif-images-compose.local.yml
- templates/iiif-manifest-compose.yml --> templates/iiif-manifest-compose.local.yml
- templates/management-compose.yml --> templates/management-compose.local.yml
- templates/worker-compose.yml --> templates/worker-compose.local.yml

**Comment by fnibbit** [comment]
Updated the branch to add the task role ARN to all four params files.  With those changes I do see the role being assigned to the tasks that I deployed to the yul-dc-infra cluster, but I don't see it working end-to-end (loading images on image server is busted for instance).  I bet that [mml or max]+[jez or me]+[bob or rick or keith] could suss this out together.

**Comment by fnibbit** [comment]
Redeployed to test bc I wasn't sure about the configuration of the infra s3 bucket.  Error messages from the image server show the cantaloupe application trying+failing to load credentials.  ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/3cc3b17b-2159-4d01-b93c-962508e6bd62)
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/b499b6d3-360e-4ea4-a2a7-d8db61e0bc10) Task definition shows that the selected IAM role was attached to the task.  
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/2cfddb79-0efa-41d7-894f-1bdded9dde5d) Error messages from the manifest container show it trying+failing to load from s3.  

This isn't as simple as it first sounded; it looks to be requiring code changes in at least two of our repositories (probably Management as well), and I would like to advocate for the use of a "machine user" set of credentials instead (or in the interim as we work to research how to make this actually work end-to-end).

**Comment by DraxIndustries79** [comment]
@kbcarter @bobrice @ra359 delete from parameter store:  DEPLOY_KEY_ID

**Comment by bobrice** [comment]
The key was deleted from the parameter store.

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/241 ready for review

**Comment by fnibbit** [comment]
Verifying this change is in use on a given cluster (I'm doing this on UAT; the images show the step just *before* actual verification): ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/869fc942-45c8-4e6c-8dcd-2fbb77cafc85)
Look at the values for DEPLOY_ACCESS_KEY and DEPLOY_KEY_ID in the parameter store

Go to the task definition for $CLUSTER_NAME-main
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/6e6d5464-cd3c-4135-867e-770577fcea0f)
Search the task definition for three occurrences of AWS_ACCESS_KEY_ID and AWS_SECRET_KEY; verify the values are the same ones set in the parameter store -- that is, the machine user's credentials rather than a set of personal credentials are in use.

Inspect the task definition for $CLUSTER_NAME-worker for the same two variables, which occur once in that task definition
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/09df40e2-3bf4-42e8-b705-ac89037c5938)
