### ISSUE TITLE
Refactor Metadata Grouping Presenter

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#557]
# Summary
Metadata grouping in the single item show page is functional but would benefit from being refactored for easier maintainability.

# Acceptance
- [x] Write a method that dynamically generates the presenters

# References
https://github.com/emory-libraries/dlp-lux/blob/154948c58c1586b68efa9de8af66c21986c34755/app/presenters/metadata_presenter.rb
https://github.com/yalelibrary/yul-dc-blacklight/tree/master/app/presenters/yul

**Comment by alishaevn** [comment]
# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/557

# User Story
DRY the code for developers.

# Expected Behavior
- there is 1 metadata presenter class that dynamically loads the correct yml file
- the show file dynamically renders the appropriate details on the individual show page
- there is 2 spec file for all metadata sections

# Demo
(nothing changed visually)
![image](https://user-images.githubusercontent.com/29032869/95254194-60987f00-07d4-11eb-8db1-273aabf1ec2c.png)
![image](https://user-images.githubusercontent.com/29032869/95254141-4ced1880-07d4-11eb-9f3b-4f5366cb4b0f.png)
