### ISSUE TITLE
Bug: Master Branch Unreleasable 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#565]
# Summary
Styling overlaps metadata on search results list view.

# Acceptance Criteria
- [ ] branch is updated to be releasable

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9beb7b91-7a7d-4da0-a5f8-99451c3ea1c9)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-09-11 at 4.27.05 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e3c9dd1c-5a5d-4976-b127-0923f0470908)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/278

# Expected behavior
- the gallery view of search results remains styled as the design intends
- the list view of search results looks like it did out of box, besides the title color being updated
- the yale restricted caption is in line with the title on an individual show page

# Demo
![565](https://user-images.githubusercontent.com/29032869/93115486-c5970400-f670-11ea-906a-109878e9c6b1.gif)

**Comment by alishaevn** [comment]
Branch:v1.17.3,Deployed:2020-09-15T09:47:00-04:00
