### ISSUE TITLE
Date Slider Styling 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#574]
**ACCEPTANCE**
- [x] Start and End dates should have borders on all sides (left border is currently missing)
- [x] Start date should be left aligned with other content in the facet
- [x] Apply Button should be right aligned with other content in the facet
- [x] Date entry and Apply button should all be the same height

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/2f10f5b9-ed41-4b08-a8e4-f4e780d6c7c8)

**Comment by FCRodriguez7** [comment]
I wrote to Matt about the styling of the data slider.

**Comment by FCRodriguez7** [comment]
Styling is off on the left button, I have attached an extreme example. ![Screen Shot 2020-09-15 at 9.31.44 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/09991cfc-56f6-4f3c-8d9f-3901e2a064d8)

**Comment by DraxIndustries79** [comment]
Still waiting for design specs to move this forward.

**Comment by dl-maura** [comment]
Don't need a design from Matt, just need to fix some of the button cutoffs etc.![Screen Shot 2020-10-06 at 1.21.11 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/01d9d476-92a9-449f-9c4c-ebdf81c3b935)

**Comment by martinlovell** [comment]
There are a few places where we override Bootstrap css classes without wrapping with a qualifying class.
(In search-bar.scss for example, we override form-control, etc.)

I think we should wrap those in some class and only apply those overrides in specific areas of the screen.

(This is related to this ticket, because the date range gem expects bootstrap CSS to apply in a certain way, but we override those styles for specific reasons that don't work with the gem.)

I think a good rule is to be very careful overriding bootstrap styles (except with selectors to point to certain areas of the screen.)  (Except maybe color schemes, etc.)  We could try to create a new bootstrap theme, but we'd have to be very careful that it worked for everything that uses bootstrap  (even code that isn't ours).

So, whenever you need to override bootstrap in a specific area, I would wrap it in a something with a class and use that to select the specific area.

**Comment by martinlovell** [comment]
I tried looking at this, but need to pair with someone who is more familiar with the CSS dependencies in the blacklight app.  (I can adjust the styles, but I'm not sure if I'm affecting other areas.)  We could just adjust the styles for the date slider with selectors, but if the original styling was there for the date slider then overriding it with more specific selectors will make it messy.

**Comment by FCRodriguez7** [comment]
There's a branch for this work: https://github.com/yalelibrary/yul-dc-blacklight/pull/354/files
