### ISSUE TITLE
STYLE: Title cutoff in Gallery View if Highlighted

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#575]
If I go to gallery view after searching, if the title was a highlighted hit, the title does NOT appear on the view.

You can recreate this by searching 'Cipher'. If I search 'Voynich', I get the same result but the title does show in full because it isn't a highlight.

Browser: Firefox
Code Ver: Branch:v1.17.3,Deployed:2020-09-15T10:38:34-04:00 

Search for Cipher -- Gallery:
![Screen Shot 2020-09-15 at 11.16.01 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/2db78fdc-a308-4942-9877-5ac8577e4a0b)

Search for Cipher -- Regular:
![Screen Shot 2020-09-15 at 11.16.08 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/53cf94ce-e8bf-490a-8caf-f34ec0ecdf62)

Search for Voynich:
![Screen Shot 2020-09-15 at 11.16.18 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/4405335b-d20f-46bb-86df-c241cdcc2e51)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/312

# Expected behavior
- searching for a word/phrase will show that word/phrase in the title in list view and gallery view

# Demo
![575](https://user-images.githubusercontent.com/29032869/93934465-0d083a80-fcd8-11ea-8e42-b9f9a4ff84e0.gif)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/312

# Expected behavior
- searching for a word/phrase will show that word/phrase in the title in list view and gallery view

# Demo
![575](https://user-images.githubusercontent.com/29032869/93942167-b9501e00-fce4-11ea-802d-9fddc9677308.gif)

# Resources
- https://stackoverflow.com/a/7317016/8079848
- https://stackoverflow.com/a/2165727/8079848
