### ISSUE TITLE
Develop complete list of services for blacklight app

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#61]
**STORY**
Running `docker-compose up web` should bring up all the services we need for the blacklight app

**ACCEPTANCE**
The docker-compose.yml file lists all of the yul-dc services:
- [x] db
- [x] images
- [x] manifests
- [x] blacklight
- [x] solr

See #61 #79 #80

**Comment by geekscruff** [comment]
Could this be re-written as:

Add a README to https://github.com/yalelibrary/yul-dc-blacklight on using docker in development.

**Comment by mark-dce** [comment]
If that's the right place to put the instructions for blacklight+manifest service+image service.

**Comment by alishaevn** [comment]
Per the conversation during sprint planning this morning, the initial ask for this ticket has been broken down into smaller, separate tickets. 

### OLD
**Document blacklight developer environment setup**

*STORY*
As a team member, I’d like some guidance about how to set up a dockerized development environment, so that I can start helping to work on the blacklight application quickly and easily.

*ACCEPTANCE*
- [ ] We have instructions for how to clone and launch a blacklight development environment
- [ ] We have a docker-compose.yml for all yul-dc services - images, manifests, blacklight, solr (via specific ticket)

### NEW
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/61
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/79
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/80

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/14
