### ISSUE TITLE
Advanced Search will clear if I switch from one view to another (Bugherd) HIGH VALUE

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#618]
See bugherd ticket: https://www.bugherd.com/t/lvDfEKWQx4Tan6RBXIxMtw

If I did an advanced search and then switch from gallery to list view, the search clears (and vice versa)

1.  Go to advanced search and go a search (I'm partial to gen mss in call number)
2. on the screen, switch to whatever view you aren't on (so gallery -> list or list -> gallery)
3. You'll see your search is wiped

**Comment by martinlovell** [comment]
It seems like this is related to advanced search removing values from `search_state` as it processes them and adds them to the query.

We use `search_state.to_h` for the "Advanced Search" link and the internal Blacklight code also uses `search_state.to_h` then merging to create the link for Gallery/List.

I'm not sure exactly how to do it, but we want to do is take the original parameter and merge those when creating the link.

I can get it to work by using `params.to_unsafe_h` in place of `search_state.to_h` in  `_search_form.html.erb` where it creates the "Advanced Search" link.
Similarly, if I override `_view_type_group.html.erb` to use `params.to_unsafe_h` in place of `search_state.to_h` the Gallery/List view do buttons work properly.

Since we don't want to accept all params (and since we don't want to use a method with the work unsafe in it's name) we should probably use params.permit().to_h and only permit the parameters we want to.  I'll look into what parameters we want to keep and try to get something working.

**Comment by martinlovell** [comment]
Added `pristine_search_state` to BlacklightHelper to return the original search_state unaltered by advanced search.
Used that method when generating links for Gallery/List and Advanced Search.

**Comment by dl-maura** [comment]
Seems to work now, I did find another bug I will make a ticket for
