### ISSUE TITLE
Batch Process High Level Status

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#649]
## Acceptance ##
For a given import or other batch process, I want to see the current top level status on the batch process index page. This high level view should list if the batch process is queued, in progress, completed successfully, completed with failures or completed with errors.

- [x] Add a status column (not data, just column, new ticket for data)
- [x] Add a job timestamp
- [x] Convert the bootstrap table to a data table

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/d06e5556-5564-4d5a-b86b-918c752657ee)

**Comment by alishaevn** [comment]
Co-author: JP Engstrom <jp@notch8.com>
Co-author: Rob Kaufman <rob@notch8.com>
Co-author: Shana Moore <shana@notch8.com>

# MR
https://github.com/yalelibrary/yul-dc-management/pull/343

# Expected Behavior
- removed the bootstrap table and added a data table
- status column is still a WIP
- job timestamps are viewable
- the "process id" and "view" words are linkable

# Demo
![image](https://user-images.githubusercontent.com/29032869/96616957-d9f59e80-12b7-11eb-9b54-f93f29a56caf.png)

# Resources
- https://github.com/jbox-web/ajax-datatables-rails#quick-start-in-5-steps

**Comment by alishaevn** [comment]
Paired with Max last Friday to bring him up to speed on our failing specs and he fixed them!

# MR
https://github.com/yalelibrary/yul-dc-management/pull/361

- Pulled from the last passing version of code
- Re-merged in master
- Found failing tests (different ones! fun!)
- Poked the internet about testing AJAX stuff with RSpec 
- Figured out we weren't using Capybara for System spec if js isn't set to `true`, set it to `true`, re-ran specs, got legit failure!
  - Fixed legit failure
