### ISSUE TITLE
Author -> Creator Everywhere in Discovery

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#651]
Looks like we're still calling the field 'Author' in the side facet and in the Sort By list. Could we change this to be consistent in all spots?![Screen Shot 2020-10-06 at 9.51.46 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/09f630dd-19fa-4906-9271-52cafdf65c33)

![Screen Shot 2020-10-06 at 9.51.35 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c9f9d784-0675-41ce-9519-6a5862ebb96b)

**ACCEPTANCE**
- [ ] All user-facing references to "Author" are changed to "Creator" throughout the discovery application.

**Comment by dl-maura** [comment]
Do we want to change this field to creator just in display, or in the solr as well? Seems like we should change it to creator even in the solr stuff (in management) for consistency within the app and with MC which uses the term creator, but then I will change the scope of the ticket.

**Comment by martinlovell** [comment]
It's unrelated to this card, but it would probably be good to change IdentifierShelfMark to CallNumber in Solr also, since that's the way it's mapped in MC's updated mappings, and that's how it's labeled in Blacklight.  (Until we start using the latest mappings, the old MC mappings will return it in IdentifierShelfMark, so it needs to be pulled from that field still.  After we update to the latest mappings we can get it in CallNumber, but the Solr field will already be correct.)

**Comment by dl-maura** [comment]
@martinlovell I can make a new ticket for solr cleanup/consistency then, if this is something we need to do on other things. We'll also need to do this for publication date (that's getting changed to something with creation, we're not sure on the label yet).

**Comment by dl-maura** [comment]
Made the change, all tests are passing, PR submitted:
![Screen Shot 2020-10-15 at 10.34.27 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/e1e81195-8591-4b9f-a22a-6fb663d4864f)

Found an unrelated bug (it exists in collections-test), that I will file a ticket for (putting this here to remind myself)
