### ISSUE TITLE
Install Dynatrace agent on docker containers

### ISSUE THREAD

**Issue by bobrice** [yalelibrary/YUL-DC#660]
Install Dynatrace agent on docker containers
- [x] See this working in a deployed environment
- [x] Dynatrace is not enabled configure reporting in local environment

Dynatrace on:
- [x] Solr
- [x] Postgres
- [x] Blacklight
- [x] Management
- [x] Workers
- [x] IIIF Image
- [x] IIIF Manifest

**Comment by dylansalay** [comment]
Currently we have this set up so we can monitor our Docker containers locally. Ideally we would only be able to see the containers for deployed containers.

**Comment by fnibbit** [comment]
What we're investigating at this point:
(1) Is the logged-in-to-dynatrace state saved/pushed in the docker image?
(2) Is that host we found in the dynatrace output actually the manifest image we pushed up 
to yul-dc-test?
(3) if 1 is no and 2 is yes, how did yul-dc-test-main get logged in to dynatrace? 
/ how do we make sure clusters we want monitored get logged in too?
(4) if 1 is yes, how do we make it so local spin-ups use a different un-monitored image?
(5) is the monitoring of the workers working? Should we set the DYNATRACE_TOKEN variable
on any other clusters than prod and the non-existent ingest so that new EC2 instances
get monitored?

**Comment by dylansalay** [comment]
We are able to confirm that we are seeing the deployed iiif_manifest service in the Dynatrace dashboard. We deployed to yul-dc-infra from the branch dynatrace_preload_env.
Note that the ip address matches in the two screenshots below.
Dynatrace
![Screen Shot 2020-10-21 at 1.42.08 PM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/31f87989-3d9c-4167-9b5d-5480807939f6)
AWS
![Screen Shot 2020-10-21 at 1.42.19 PM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/61518bbc-354d-4a7b-81dc-77907b194916)

**Comment by dylansalay** [comment]
We want to set the --set-infra-only=true flag for Dynatrace OneAgent Installs

**Comment by mark-dce** [comment]
From the Dynatrace Docs:
"There's no need to modify your Docker images, modify run commands, or create additional containers to enable Docker monitoring. Simply install OneAgent on your hosts that serve containerized applications and services."
https://www.dynatrace.com/support/help/technology-support/cloud-platforms/other-platforms/docker/basic-concepts/how-dynatrace-monitors-containers/

**FARGATE**
Have we investigated "Run-Time Injection" instead of "Build Time Injection" for Fargate containers.  It appears we may have more configuration options in run-time injection.

https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/integrations/deploy-oneagent-on-aws-fargate/#expand-1091run-time-injection

**EC2**
https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/integrations/deploy-oneagent-on-ecs/

**Comment by dylansalay** [comment]
@mark-dce @fnibbit @orangewolf I did some research and I think this response does a good job of outlining the pros/cons of build-time vs run-time OneAgent injections - https://answers.dynatrace.com/questions/231860/proscons-of-build-time-vs-run-time-deployment-opti.html

Given all of the installation issues we've encountered with the build-time injection I think it makes sense to give the run-time injection a try, especially if we can add the OneAgent installer parameters/flags and make Bob's job a little easier. @bobrice do you have any concerns/opinions? I specifically want to highlight one of the concerns of run-time injection -> "If there's a network failure, a proxy issue, or something that makes it impossible to download the agent, your app won't start."

There is also the "Deploy OneAgent on Elastic Container Service (EC2)" option that Mark listed above, which also allows for the addition of OneAgent installer parameters/flags.

**Comment by dylansalay** [comment]
Installation Options: 

1.) Integrate OneAgent on Web App for Containers: [Build-time injection](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/microsoft-azure-services/oneagent-integration/integrate-oneagent-on-web-app-for-containers/)
OR
Deploy OneAgent on AWS Fargate: [Build-time injection](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/integrations/deploy-oneagent-on-aws-fargate/#expand-1090build-time-injection)
-Both set of instructions appear to be the same. 

Pros
- Already configured for 5/6 services (Not working in Postgres Container)
- You avoid this network risk. But, again, you can avoid it using deployment strategies and keep using run time integrations.
- Your docker container is immutable - it never changes. This can be a security requirement in certain organizations depending on how they manage docker images / repositories.

Cons
- Not possible (According to Dynatrace) to set OneAgent installer parameters, for example --set-infra-only=true
- The docker container will be a little larger
- If you want to update the agent, you need to rebuild the docker image
- Will not work with Postgres Container. According to Dynatrace Tech Support - "since this integration is PaaS: https://www.dynatrace.com/support/help/shortlink/aws-fargate and Postgres is written in C, that is why you are not seeing the OneAgent collect any information."

2.) Run-time injection: [Run-time injection](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/integrations/deploy-oneagent-on-aws-fargate/#expand-1091run-time-injection)

Pros
- The docker container image will be a little smaller, since the agent is downloaded later.
- The docker container will always get the latest bits (if you specify 'latest' in the URL string)

Cons
- Also will not work with Postgres Container (According to Dynatrace Tech Support) because it is PaaS. 
- If there's a network failure, a proxy issue, or something that makes it impossible to download the agent, your app won't start.
- If you do not use rolling updates [example] this could have severe consequences. If you use rolling updates, and have a strategy that does not continue a deploy until the 'last' container is running, then there's really no problem.

3.) Deploy OneAgent on Elastic Container Service (EC2) [ECS](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/integrations/deploy-oneagent-on-ecs/)

Pros
- Can set OneAgent installer parameters, for example --set-infra-only=true
- ECS orchestrates the execution of the OneAgent task on each container instance that is part of the cluster
- Lots of configuration options

Cons
- Also will not work with Postgres Container (According to Dynatrace Tech Support) because it is PaaS. 
- No experience implementing

4.) Deploy Dynatrace OneAgent as a Docker container [OneAgent as a Docker container](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/other-platforms/docker/installation-and-operation/deploy-dynatrace-oneagent-as-docker-container/)

Pros
- Can set OneAgent installer parameters, for example --set-infra-only=true [Options](https://www.dynatrace.com/support/help/shortlink/oneagent-docker#custom-installation-with-command-line-parameters)
- Running OneAgent as a Docker container gives you full-stack visibility into your complete containerized environment. This includes deep monitoring of supported applications, services, and databases.

Cons
- https://www.dynatrace.com/support/help/technology-support/cloud-platforms/other-platforms/docker/installation-and-operation/deploy-dynatrace-oneagent-as-docker-container/#limitations
