### ISSUE TITLE
Allocate Space on Storage@Yale for access masters

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#70]
**ISSUE**
We would like to begin moving access masters to a consistent location and structure, so we need new storage space provisioned on Storage@Yale

**ACCEPTANCE**
- [ ] We have space to store 
- [ ] The shares can be accessed via a single mount point
- [ ] The top level of the directory tree is divided into 100 buckets identified 00, 01, 02,...99

**Comment by bobrice** [comment]
@mark-dce Assuming that storage would be object, not file storage.  If that's the case, then a single name space that contains these 100 bucket definitions is fine.  No need to break up storage like we do in Fedora/Findit because there's no volume size limit. There is a file size limit of 5TB.  

Is it the project plan to move the masters to a new location or use them from their current home?

Either way, I will open a ticket with Central ITS Storage Team to get a test and prod volume of object tier set up for us.

**Comment by bobrice** [comment]
Storage has been provisioned for Lakeisha's work in YUL-DC#82
