### ISSUE TITLE
[CHECK] Alternative Title displays URI when using ILS data

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#736]
For OID 2005512, change data source to ILS.   Alternative Title will display a URI:

![Screen Shot 2020-10-28 at 10.38.38 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a5878a72-1cd5-420a-a006-9d15ea17f927)

**Comment by dl-maura** [comment]
Looks like alternativeTitle is mapping to the loc name authority record @martinlovell want to mention this to metadata working group or should I email? It is looking like that in test, so it isn't something that's been changed yet.

**Comment by dl-maura** [comment]
This looks to be fixed with new MC mappings: https://collections-demo.library.yale.edu//catalog/2029300

**Comment by FCRodriguez7** [comment]
Is this the correct behavior?  This is what happens when the source is changed to ILS:

**Show Page**
![Screen Shot 2021-07-12 at 3.17.30 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4184bf20-5263-44b0-a75f-57992900ffc6)

-----

**Data** 
![Screen Shot 2021-07-12 at 3.18.14 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5f97b095-a4e1-483a-80a5-71857950b237)

-----

**The original metadata source:** 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/827a54d2-e4a7-4169-b4ae-d1187e8900a6)

**Comment by mikeapp** [comment]
Encountered in production: https://collections.library.yale.edu/catalog/31941087

![Screen Shot 2021-07-15 at 10.14.41 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/15924c5c-b119-469a-b970-7ce1203a8e18)
