### ISSUE TITLE
Dynatrace runtime install

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#755]
- use a run-time rather than build-time install approach for dynatrace in
 - [x] workers
- [ ] blacklight
- [ ] management
- [ ] iiif-manifest
- [ ] iiif-image
- [ ] solr
- [x] postgres
- [ ] set install flags consistently across containers

**Comment by mlooney** [comment]
use pattern established in psql image.

Requires modification to camerata templates to ensure CLUSTER_NAME and DYNATRACE_TOKEN are present in the runtime environment, and modification to docker build to inject the installation into the boot sequence

**Comment by dylansalay** [comment]
Postgres
![Screen Shot 2020-11-10 at 9.17.24 AM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/a7f0ae52-07fc-4059-96e0-c6d12c66db23)
![Screen Shot 2020-11-10 at 9.19.29 AM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/8fe05d82-9e9f-4de6-8577-6af15a5e6432)

**Comment by dylansalay** [comment]
Error logs 
[https://app.zenhub.com/files/242185115/a84ae162-5a2a-4305-ae42-29dcdaa43e95/download](https://app.zenhub.com/files/242185115/a84ae162-5a2a-4305-ae42-29dcdaa43e95/download)

**Comment by fnibbit** [comment]
Notes on the docker image build process for solr that I'd like someone who understands docker images better than I do to look at: 

What exactly happens when we build a new image of this on circleci?
notes from reading through .circleci/config.yml and the output of 'circleci config process .circleci/config.yml'
  branch:
    build-and-push
      - setup_remote_docker
      - checkout
      - docker/check
        looks around for environment variables
      - docker/build
        pull yalelibraryit/dc-solr:master from dockerhub
        pull the image from dockerhub for yalelibraryit/dc-solr:$CIRCLE_SHA1 if it exists
        put together $docker_tag_args, I *think* it winds up being just the circle sha
        'docker build --cache-from yalelibraryit/dc-solr:master -f ./Dockerfile $docker_tag_args .'
      - docker/push
        'deploy' step:
          pulls together a list of docker tags, I think it winds up being just $CIRCLE_SHA1
            for each tag, 'docker push docker.io/yalelibraryit/dc-solr:${tag}'
    publish-latest
      - setup_remote_docker
      - docker/check
        looks around for environment variables
      - docker/pull
        pull the image from dockerhub for yalelibraryit/dc-solr:$CIRCLE_SHA1
      - generate a branch name without special characters
        'echo "export CLEAN_BRANCH=`echo $CIRCLE_BRANCH |sed 's#[^[:alnum:]._-]##g'`" >> $BASH_ENV'
      - docker-tag
        docker tag yalelibraryit/dc-solr:$CIRCLE_SHA1 yalelibraryit/dc-solr:$CLEAN_BRANCH
      - docker/push
        list of tags I think containing only $CLEAN_BRANCH
        docker push docker.io/yalelibraryit/dc-solr:${tag}
  version tags that are of the form v{number}.{number}.{number}, exactly:
    publish-github-release, which is the same as publish-latest, except using $CIRCLE_TAG instead
    of $CLEAN_BRANCH as the dockerhub tag.

What happens when someone manually builds a new image of this following the readme instructions? 
  [from a local checkout of the yul-dc-solr repo, so docker-compose would find the docker-compose file that lives in the yul-dc-solr repo, not a camerata-related docker-compose.]
  export SOLR_TAG=$(git rev-parse --short HEAD)
  docker-compose build 
  docker tag <image id> yalelibraryit/dc-solr:<version>
  docker push yalelibraryit/dc-solr:<version>

Does it matter to either of these processes whether a previous image with the same tag
exists in dockerhub?  Is there relevant caching? Is there *ir*relevant caching?  (Note that there
have been far fewer automated builds, and far more recent manual builds, of postgres and solr than
of the rails apps.)

**Comment by orangewolf** [comment]
Does it matter to either of these processes whether a previous image with the same tag
exists in dockerhub? 

when an image is pushed the primary thing that goes up to dockerhub is the SHA for that image. The tag it uses is a pointer to that SHA. When a new image is pushed claiming that tag name, the tag is pointed to the new sha.  The old image still exists under its original sha, just the pointer no longer points to it.

Is there relevant caching?

any layer not changed is cached. So if dynatrace is last in the build process all previous layers are cached. The result of RUN commands are assumed to be atomic (the same RUN line should give the same result each time) there for RUNs are considered unchanged unless a layer above them changes.  This means (for example) an apt install won't get re-run even if upstream packages get updates, because Docker assumes it has not changed.  All caching is by layer (each step in the file makes is a layer). Once a layer is updated, all subsequent layers are then updated and considered new.

 Is there irrelevant caching?

this would happen if (and as far as I can tell only if) Dynatrace updated the library. If they did, we'd need to force rebuild the layer or make sure one of the previous layers in the file was changed.

**Comment by DraxIndustries79** [comment]
Created a follow-on ticket to replicate across containers.
