### ISSUE TITLE
Generate JSON from the parent & child objects for PDF generation

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#760]
**STORY**
The PDF generation java application takes a JSON file as its input to generate the cover page and add metadata to image pages in the PDF.  We need a mechanism to transform the Solr JSON into suitable JSON for the Java 

**ACCEPTANCE**
Given the Solr JSON for an item in the management application,
- [x] I can use the PDF generation application to create a cover page with the desired content
Since we don't have this code wired to the ingest pipeline,
- [x] Any errors in the JSON conversion process are logged
- [x] Attach/link to a sample of the JSON generated in the development environment
- [x] Attach/link to a sample PDF generated using the JSON

**NOTE**
Similar to #762 (Manually Generate PDFs) We can decouple this ticket from #766 (Automatically Generate PDFs) by manually running the PDF generation and saving the output to the expected location in S3

**Comment by dl-maura** [comment]
New PDF:

- Title
- Call Number
- Creator
- Date
- Rights statement (need new solr field)
- Container Information: LadyBird is Box + Folder, ASpace/Voyager allows more so ‘Container Information’ would cover all, so may be different solr fields?
- Generated (Time/Date of PDF generation)
- Terms of Use Link
- Link to Item in New DL
- Placeholder for Contact, but this doesn’t exist now so might just have to come back to it
- For each image page, look for a title for the image in these fields in order until it finds one: caption_ssim (exists in LB), page_label (not a solr field yet, only for Goobi incoming). If neither have values, BE BLANK instead of image number

If any more info is needed (solr fields), let me know.

**Comment by martinlovell** [comment]
Please see: https://github.com/yalelibrary/yul-dc-management/tree/pdf_generation_concern

**Comment by martinlovell** [comment]
Sample PDF generated from JSON from ParentObject.pdf_generator_json:

https://drive.google.com/drive/folders/1NqlMaQpb2Ijr2lJHVbG8ryOEBMQOymYy?usp=sharing

**Comment by martinlovell** [comment]
For testing, since we can't run the job in the container until we get Java/Rails container setup, you can

- generate the JSON using the container
- run the java app on the JSON to create PDFs not in the container.  (If you do all 45, create a bash script to generate them all.)
- upload PDFs to S3.

If you add the code below to ParentObject (just for testing purposes), then in "rails c" create the JSON with `ParentObject.create_pdf_jsons` (first create pdf_testing folder in management folder)

**(This generates json for all ParentObjects, so not good for a full database....just for Testing with 45 parents.)**
After you generate the PDFs, you can upload them to S3 in the pairtree from the container using "rail c" with `ParentObject.upload_pdfs_to_pairtree`


```

  def self.create_pdf_jsons
    parent_objects = ParentObject.all
    parent_objects.each do |parent_object|
      oid = parent_object["oid"]
      json = parent_object.pdf_generator_json
      File.open("./pdf_testing/#{oid}.json", "w") { |file| file.write json } if json
    end
  end

  def self.upload_pdfs_to_pairtree
    parent_objects = ParentObject.all
    parent_objects.each do |parent_object|
      oid = parent_object["oid"]
      if File.exist? "pdf_testing/#{oid}.pdf"
        if !S3Service.s3_exists? "#{Partridge::Pairtree.oid_to_pairtree(oid)}/#{oid}.pdf"
          S3Service.upload_image("pdf_testing/#{oid}.pdf", "#{Partridge::Pairtree.oid_to_pairtree(oid)}/#{oid}.pdf", "application/pdf", nil)
          puts "Uploaded pdf_testing/#{oid}.pdf to #{Partridge::Pairtree.oid_to_pairtree(oid)}/#{oid}.pdf"
        else
          puts "Already uploaded #{oid} to #{Partridge::Pairtree.oid_to_pairtree(oid)}/#{oid}.pdf"
        end
      else
        puts "Can't find pdf file for #{oid}"
      end
    end
    puts "Done"
  end
```

**Comment by martinlovell** [comment]
Sample PDF

[https://app.zenhub.com/files/242185115/7222bec1-3c4a-4c1d-b7d6-c1c6fbcd65b9/download](https://app.zenhub.com/files/242185115/7222bec1-3c4a-4c1d-b7d6-c1c6fbcd65b9/download)

**Comment by martinlovell** [comment]
Another Sample PDF generated from PTIFFs for Quality check:
https://drive.google.com/file/d/1x6s4CIN_7fU3kXAwRiDrDr-nh9_fiVMb/view?usp=sharing

**Comment by martinlovell** [comment]
Should we use https://guides.library.yale.edu/about/policies/access for the terms of use link?

**Comment by dl-maura** [comment]
Yes, that is the correct link

**Comment by martinlovell** [comment]
The link has been update in the management app.
