### ISSUE TITLE
Finalize PDF cover page and metadata requirements

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#768]
**ACCEPTANCE**
- [x] Decide on what metadata to include on the cover page
* OPTION 1.1: Include all the available metadata on the item show page on the PDF cover page
* OPTION 1.2: Include a specific list of field from the parent object on the PDF cover page (if choosing this option, add the specific list of fields to ticket #760)
- [x] Decide on what metadata to include on individual image pages
* OPTION 2.1: Do not include child-level metadata on individual image pages in the PDF
* OPTION 2.2: Include specific child-level metadata fields on individual image pages (e.g. caption, label) (if choosing this option, list the specific metadata fields to include for child images in ticket #760)

**Comment by dl-maura** [comment]
Also added to 760 but here you go:

New PDF:

- Title
- Call Number
- Creator
- Date
- Rights statement (need new solr field)
- Container Information: LadyBird is Box + Folder, ASpace/Voyager allows more so ‘Container Information’ would cover all, so may be different solr fields?
- Generated (Time/Date of PDF generation)
- Terms of Use Link
- Link to Item in New DL
- Placeholder for Contact, but this doesn’t exist now so might just have to come back to it
- For each image page, look for a title for the image in these fields in order until it finds one: caption_ssim (exists in LB), page_label (not a solr field yet, only for Goobi incoming). If neither have values, BE BLANK instead of image number
-
