### ISSUE TITLE
Improve Focus indicator color contrast

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#821]
**DETAILS**
See issue 8 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] Check with Kara on what is left
- [x] Hover focus indicators have higher contrast color
- [ ] Optional: focus outline is thicker.

**Comment by dl-maura** [comment]
Get more information (check if color is still ok, and on thickness suggestion)

**Comment by dl-maura** [comment]
From Kara:
Yes, the arrow color looks great! As for guidance on the thickness, that is not currently a requirement or success criterion. In the future, thickness of focus indicators will be a requirement; but UI elements, such as icons, just need to have proper color contrast.

Following up with her on the focus indicator thickness, I had thought she was pointing to the arrows but it turns out she was pointing to the focus box around the arrows.
