### ISSUE TITLE
Blacklight Application needs to know when you are "On Campus"

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#862]
# Acceptance #
There should be service or controller method that returns true if a request IP is on campus and false if it is not on campus.  This should be fed from a list found in an ENV variable on application startup.  Adding the ENV var and creating its initial states for dev and prod environments should be considered part of this ticket.

**Comment by martinlovell** [comment]
We need a new variable to store a list of IPs and IP ranges using slash notation. e.g. 192.168.0.0/16

SSM has a StringList type, but since we might be passing it in via environment variables, we could use a comma separated string in SSM.  (Max SSM String length is 4096).

The list of IP ranges does not change frequently.

For development purposes, we can use a default or all private IP ranges: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1

The blacklight app will need a code which takes an IP and checks it against this list.

**Comment by orangewolf** [comment]
Martin's example from Search frontend
```
 def self.on_campus?(ip_addr)
    # check passed string against regexp from standard library
    return false unless ip_addr =~ Resolv::IPv4::Regex
    APP_CONFIG['YALE_IP_RANGES'].any? do |ir|
      IPAddr.new(ir) === ip_addr
    end
  end
```

APP_CONFIG would need to be ENV, but otherwise this seems like a reasonable approach

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/410

**Comment by maxkadel** [comment]
Question: Is there a cheap experiment we can do to make sure this is working as expected in deployed environments? Like, could we put something boring behind a controller that's like "Congrats, you're on campus!" vs. "You need to be on campus!" but that doesn't expose anything real?

**Comment by dl-maura** [comment]
Deploy to staging
