### ISSUE TITLE
Ingest Yale Only objects to TEST

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#900]
**STORY**
As a repository owner, I would like to be able to deliver Yale Community Only objects, so that Yale community members can conduct scholarship using restricted resources.

**ACCEPTANCE**
- [x] Give the list to people
- [x] All of the Yale Only Items from the pre-gap object list are available to logged in or network connected users on the **TEST** blacklight site.
- [x] Confirm that the items show up as "Yale Community Only" in the management application
- [x] Confirm that the "yale community only" setting is indexed into solr
- [x] Write up tickets for any objects that don't import as expected. - see #927

**Comment by maxkadel** [comment]
Instead of bumping the workers on collections-test up and down twice, I think it makes sense to pair the update metadata ticket to the ingest ticket. So, on an environment:

- [ ] Bump up workers
- [ ] Update metadata on all parent objects
- [ ] Ingest Yale Only objects
- [ ] Take workers back down

**Comment by maxkadel** [comment]
Issues: 
* Uploading CSVs is still relatively slow - ran into 504 gateway timeouts on 1000 line long CSVs

**Comment by dl-maura** [comment]
We are getting a refresh of LB test data to fix some of the fail errors

**Comment by maxkadel** [comment]
As of Friday morning, 12/11/2020:
* On Yale VPN seeing the thumbnail for if I were *not* on Yale VPN
![image](https://user-images.githubusercontent.com/45948126/101916582-27460c00-3b95-11eb-848d-7fe7b50aed70.png)
* 948 PDF failures right now. https://app.honeybadger.io/projects/72674/faults/70329075 . Martin is investigating whether it's actually due to the resizing pre-processing that the error message references, or whether it could still be a memory error.
  * At the time of the failures, there were 8 containers, each of which appeared to be running one worker process, as far as I could tell from the AWS ECS dashboard.

**Comment by maxkadel** [comment]
e.g. 
* https://collections-test.library.yale.edu/management/parent_objects/2053918 
* https://collections-test.library.yale.edu/catalog/2053918 
Logged in:
![image](https://user-images.githubusercontent.com/45948126/102017575-cbff4f80-3d35-11eb-9a51-04601737b937.png)
Logged out, on VPN:
![image](https://user-images.githubusercontent.com/45948126/102017609-ecc7a500-3d35-11eb-9a42-63810ca00d34.png)

**Comment by mark-dce** [comment]
Closing this because restrictions are clearly being read and indexed into Solr.  The system is honoring the restrictions in regards to login.  I have written up a separate ticket to deal with correctly handle network address based access/restriction - see #927 *VPN Users should not see restricted icon for Yale Community objects*
