### ISSUE TITLE
Replace Carousel with random image load

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#913]
**ACCEPTANCE**
 - [x] Update the hero images to reflect the styling in zeplin
 - [x] Each time I reload the homepage, display a different random hero image (instead of a carousel)

**NOTE**
This can probably be done on the server side with ERB or client side with Java.  Small preference for server side.

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/438

# Summary
- the first PR to address the ticket above
- will do a second PR later to make the hero image change on refresh

# Expected behavior
- there's a single hero image
- styled according to the mobile, tablet and desktop views in zeplin

# Demo
https://share.getcloudapp.com/4guO1GyK

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/445

# Expected behavior
- the hero image changes on page refresh
- while you won't get the same image back to back, you may get image 1, then image 2 and then image 1 again
- making sure that the new image is not the same as the last one may on occasion take a few seconds as the computation runs again

# Demo
https://share.getcloudapp.com/6quxYl2J

**Comment by mikeapp** [comment]
I'm seeing a broken image on collections-test.

![Screen Shot 2020-12-15 at 4.46.32 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/1ed473a3-2656-4dac-9941-2ba41b623a7e)

**Comment by alishaevn** [comment]
This work is present on https://collections-test.library.yale.edu/, `Branch:v1.36.6,Deployed:2020-12-16T11:13:18-05:00 `

**Comment by alishaevn** [comment]
This work is present on https://collections-uat.library.yale.edu/, `Branch:v1.36.6,Deployed:2020-12-16T11:22:11-05:00 `
