### ISSUE TITLE
Enable Gzip compression for JSON responses

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#941]
**Story**

The IIIF Presentation Validator ( https://iiif.io/api/presentation/validator/service/  ) reports:
`The remote server did not use the requested gzip transfer compression, which will slow access. (Content-Encoding: )`

**Acceptance**
- [ ] IIIF manifests should use gzip transfer compression, since we're sending a lot of very repetitive JSON.

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/529

# Status
we attempted two ways to solve this:
 - using zlib (see commit [6f9f2f](https://github.com/yalelibrary/yul-dc-blacklight/pull/529/commits/f4a529e8e6e55f02052460563d3ff0d3346f9f2f) )
 - using headers (see code at: https://github.com/yalelibrary/yul-dc-blacklight/pull/529/files)

currently the second option is giving the error below
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/a33ce398-9ac0-42f2-a2f7-607c18292ace)

**Comment by mikeapp** [comment]
There’s apparently Rack middleware that can be configured to do this, see the reference to `config.middleware.use Rack::Deflater` in https://pawelurbanek.com/rails-gzip-brotli-compression. Do not worry about Brotli compression discussed in that article.

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/529

# Expected behavior
- browsers that have gzip enabled will use gzip compression
- browsers that don't have gzip enable, won't use gzip compression

# Demo
| w/o compression | with compression |
| --- | --- |
| <img width="1440" alt="Screen Shot 2021-05-04 at 12 21 47 PM" src="https://user-images.githubusercontent.com/29032869/117044101-e32de200-acc2-11eb-8a6f-790dba943e99.png"> | <img width="1440" alt="Screen Shot 2021-05-04 at 12 23 04 PM" src="https://user-images.githubusercontent.com/29032869/117044124-ec1eb380-acc2-11eb-94ee-89ad92395e78.png"> |

# Resources
- https://pawelurbanek.com/rails-gzip-brotli-compression
- https://thoughtbot.com/blog/content-compression-with-rack-deflater
- https://www.dwightwatson.com/posts/request-specs-for-rackdeflate

**Comment by dylansalay** [comment]
We compared page reload times on collections-test and the production site. Collections-test, which currently has the gzip compression enabled, reloaded 1+ seconds faster.
